<?php

/*
|--------------------------------------------------------------------------
| «انتخاب کشور سرور مجازی خارج» — /vps/compare-locations (fa / en / tr)
|--------------------------------------------------------------------------
| نیتِ جست‌وجوی این صفحه «مقایسه/کدام کشور» است، نه «خرید سرور خارج» که
| /vps/international مالکش است؛ دو صفحه برای یک نیت یعنی رقابت با خودمان.
|
| ⚠️ قواعدِ محتوا:
|   · هیچ عددِ تأخیر (ms) این‌جا نیست. تا پایشِ واقعی نداریم هر عددی ساختگی
|     است — صفحه کاربر را به ابزارِ پینگ می‌فرستد تا خودش بسنجد.
|   · قیمت، تعدادِ پلن و شهرها زنده از CloudCountry::served() می‌آیند؛ کشوری که
|     امروز پلنِ فروختنی ندارد اصلاً نمایش داده نمی‌شود، حتی اگر این‌جا ردیف دارد.
|   · 🔴 هیچ ادعای VPN/فیلترشکن/«دور زدن فیلتر» — قوانینِ /aup. کاربردها
|     همان چیزهایی‌اند که واقعاً می‌فروشیم: سایت، توسعه، ترید، ریموت، ذخیره‌سازی.
|     ForeignVpsFinderTest این مرز را روی خروجیِ رندرشده قفل می‌کند.
*/

return [

    'meta' => [
        'fa' => [
            't' => 'بهترین کشور برای سرور مجازی خارج کدام است؟ مقایسه آلمان، هلند، فنلاند و آمریکا',
            'd' => 'مقایسهٔ زندهٔ کشورهای سرور مجازی خارج: قیمت، تعداد پلن و شهرها. با پاسخ به دو سؤال، مناسب‌ترین کشور برای سایت، برنامه‌نویسی، ترید یا ریموت دسکتاپ را ببینید.',
            'badge' => 'انتخاب کشور سرور خارج',
            'h1' => 'سرور مجازی خارج:', 'h1_g' => 'کدام کشور برای کار شما بهتر است؟',
            'lead' => 'کشور سرور را باید بر اساس محل کاربران و نوع کار انتخاب کرد، نه صرفاً ارزان‌ترین قیمت. سرور اروپایی برای مخاطب ایران و اروپا تأخیر کمتری دارد، آمریکا و سنگاپور برای کاربر همان قاره‌ها، و لندن برای ترید کنار سرور بروکرها. پایین‌تر با دو سؤال پیشنهاد اختصاصی بگیرید.',
            'crumb' => 'مقایسه کشورها',
        ],
        'en' => [
            't' => 'Best Country for an International VPS — Germany vs Netherlands vs Finland vs USA',
            'd' => 'Live comparison of international VPS locations: prices, plan counts and cities. Answer two questions to see the best country for a website, development, trading or remote desktop.',
            'badge' => 'Choose a VPS location',
            'h1' => 'International VPS:', 'h1_g' => 'which country fits your workload?',
            'lead' => 'Pick a server country by where your users are and what you run on it — not only by the lowest price. European locations suit audiences in Europe and the Middle East, the USA and Singapore suit users on those continents, and London suits trading next to broker servers. Answer two questions below for a tailored suggestion.',
            'crumb' => 'Compare locations',
        ],
        'tr' => [
            't' => 'Yurt Dışı VPS İçin En İyi Ülke Hangisi? Almanya, Hollanda, Finlandiya ve ABD Karşılaştırması',
            'd' => 'Yurt dışı VPS lokasyonlarının canlı karşılaştırması: fiyatlar, plan sayıları ve şehirler. İki soruyu yanıtlayın; web sitesi, yazılım geliştirme, trading veya uzak masaüstü için en uygun ülkeyi görün.',
            'badge' => 'VPS lokasyonu seçimi',
            'h1' => 'Yurt dışı VPS:', 'h1_g' => 'işiniz için hangi ülke daha uygun?',
            'lead' => 'Sunucu ülkesini yalnızca en düşük fiyata göre değil, kullanıcılarınızın nerede olduğuna ve üzerinde ne çalıştıracağınıza göre seçin. Avrupa lokasyonları Avrupa ve Orta Doğu kitlesine, ABD ve Singapur o kıtalardaki kullanıcılara, Londra ise broker sunucularına yakın trading için uygundur. Aşağıdaki iki soruyla size özel öneri alın.',
            'crumb' => 'Lokasyon karşılaştırma',
        ],
    ],

    'ui' => [
        'fa' => [
            'pill_countries' => ':n کشور خارج', 'pill_plans' => ':n پلن فعال', 'pill_from' => 'شروع از :price',
            'pill_live' => 'قیمت‌ها زنده از فروشگاه',
            'cta_quiz' => 'پیشنهاد کشور بگیر', 'cta_table' => 'جدول مقایسه',
            'quiz_t' => 'دو سؤال، سه پیشنهاد',
            'quiz_d' => 'پاسخ‌ها فقط در مرورگر شما پردازش می‌شوند و جایی ذخیره نمی‌شوند.',
            'q1' => '۱. سرور را بیشتر برای چه کاری می‌خواهید؟',
            'q2' => '۲. مهم‌ترین اولویت شما چیست؟',
            'p_price' => 'کمترین قیمت', 'p_choice' => 'بیشترین تنوع پلن', 'p_near' => 'نزدیکی جغرافیایی به ایران',
            'quiz_btn' => 'نشان بده', 'quiz_hint' => 'یک کاربرد و یک اولویت انتخاب کنید.',
            'res_t' => 'پیشنهاد ما برای شما', 'res_rank' => 'پیشنهاد :n',
            'res_plans' => ':n پلن', 'res_from' => 'از :price', 'res_go' => 'دیدن پلن‌های :country',
            'res_again' => 'تغییر پاسخ‌ها',
            'table_t' => 'مقایسهٔ کشورها با قیمت زنده',
            'table_d' => 'ارزان‌ترین پلن هر کشور، تعداد پلن‌های قابل خرید و شهرهای موجود — مستقیم از فروشگاه، بدون عدد دستی.',
            'th_country' => 'کشور', 'th_cities' => 'شهرها', 'th_plans' => 'پلن‌ها', 'th_from' => 'شروع قیمت', 'th_best' => 'مناسب برای', 'th_link' => 'پلن‌ها',
            'per_mo' => 'ماهانه', 'see' => 'مشاهده',
            'empty' => 'فهرست کشورها در حال به‌روزرسانی است. برای مشاوره تماس بگیرید.',
            'uses_t' => 'هر کاربرد، کدام کشور',
            'uses_d' => 'خلاصهٔ منطقی که پیشنهاددهنده بر اساسش کار می‌کند — تا بدانید چرا.',
            'uses_top' => 'گزینه‌های اول:',
            'check_t' => 'پیش از خرید، این چهار مورد را بسنجید',
            'check' => [
                'محل کاربران: سرور را نزدیک بیشترین کاربران بگذارید، نه نزدیک خودتان.',
                'تأخیر واقعی: پیش از تصمیم، پینگ و مسیر شبکه را از اینترنت خودتان تا شهر مقصد بسنجید.',
                'ترافیک ماهانه: برای دانلود، بکاپ یا استریم، سقف ترافیک از قدرت CPU مهم‌تر است.',
                'قانون و داده: برای دادهٔ کاربران اروپایی، نگهداری در اتحادیهٔ اروپا الزامات GDPR را ساده‌تر می‌کند.',
            ],
            'ping_cta' => 'تست پینگ آنلاین',
            'faq_t' => 'پرسش‌های متداول سرور خارج',
            'cross_t' => 'صفحات مرتبط',
            'cross_intl' => 'خرید سرور مجازی خارج', 'cross_hourly' => 'سرور مجازی ساعتی', 'cross_trading' => 'سرور مجازی ترید',
            'cross_windows' => 'سرور مجازی ویندوز', 'cross_iran' => 'سرور مجازی ایران', 'cross_aup' => 'قوانین استفاده',
        ],
        'en' => [
            'pill_countries' => ':n countries', 'pill_plans' => ':n live plans', 'pill_from' => 'from :price',
            'pill_live' => 'Live store prices',
            'cta_quiz' => 'Get a recommendation', 'cta_table' => 'Comparison table',
            'quiz_t' => 'Two questions, three suggestions',
            'quiz_d' => 'Your answers are processed in your browser only and are not stored.',
            'q1' => '1. What will the server mainly be used for?',
            'q2' => '2. What matters most to you?',
            'p_price' => 'Lowest price', 'p_choice' => 'Widest plan choice', 'p_near' => 'Closest to the Middle East',
            'quiz_btn' => 'Show me', 'quiz_hint' => 'Pick one use and one priority.',
            'res_t' => 'Our suggestion for you', 'res_rank' => 'Option :n',
            'res_plans' => ':n plans', 'res_from' => 'from :price', 'res_go' => 'See :country plans',
            'res_again' => 'Change answers',
            'table_t' => 'Locations compared with live prices',
            'table_d' => 'Cheapest plan per country, number of orderable plans and available cities — straight from the store, no hand-typed numbers.',
            'th_country' => 'Country', 'th_cities' => 'Cities', 'th_plans' => 'Plans', 'th_from' => 'From', 'th_best' => 'Best for', 'th_link' => 'Plans',
            'per_mo' => 'monthly', 'see' => 'View',
            'empty' => 'The location list is being refreshed. Contact us for advice.',
            'uses_t' => 'Which country for which workload',
            'uses_d' => 'The reasoning the recommender uses — so you know why.',
            'uses_top' => 'Top choices:',
            'check_t' => 'Check these four things before you buy',
            'check' => [
                'Where your users are: place the server near most of your users, not near you.',
                'Real latency: measure ping and the network path from your own connection to the target city first.',
                'Monthly traffic: for downloads, backups or streaming, the traffic allowance matters more than CPU power.',
                'Law and data: for EU users\' data, hosting inside the EU simplifies GDPR obligations.',
            ],
            'ping_cta' => 'Online ping test',
            'faq_t' => 'International VPS FAQ',
            'cross_t' => 'Related pages',
            'cross_intl' => 'Buy an international VPS', 'cross_hourly' => 'Hourly VPS', 'cross_trading' => 'Trading VPS',
            'cross_windows' => 'Windows VPS', 'cross_iran' => 'Iran VPS', 'cross_aup' => 'Acceptable use policy',
        ],
        'tr' => [
            'pill_countries' => ':n ülke', 'pill_plans' => ':n aktif plan', 'pill_from' => ':price\'dan başlayan',
            'pill_live' => 'Mağazadan canlı fiyatlar',
            'cta_quiz' => 'Öneri al', 'cta_table' => 'Karşılaştırma tablosu',
            'quiz_t' => 'İki soru, üç öneri',
            'quiz_d' => 'Yanıtlarınız yalnızca tarayıcınızda işlenir ve hiçbir yerde saklanmaz.',
            'q1' => '1. Sunucuyu ağırlıklı olarak ne için kullanacaksınız?',
            'q2' => '2. Sizin için en önemli öncelik nedir?',
            'p_price' => 'En düşük fiyat', 'p_choice' => 'En geniş plan seçeneği', 'p_near' => 'Orta Doğu\'ya yakınlık',
            'quiz_btn' => 'Göster', 'quiz_hint' => 'Bir kullanım ve bir öncelik seçin.',
            'res_t' => 'Size önerimiz', 'res_rank' => ':n. seçenek',
            'res_plans' => ':n plan', 'res_from' => ':price\'dan', 'res_go' => ':country planlarını gör',
            'res_again' => 'Yanıtları değiştir',
            'table_t' => 'Canlı fiyatlarla lokasyon karşılaştırması',
            'table_d' => 'Her ülkenin en ucuz planı, satın alınabilir plan sayısı ve mevcut şehirler — doğrudan mağazadan, elle yazılmış rakam yok.',
            'th_country' => 'Ülke', 'th_cities' => 'Şehirler', 'th_plans' => 'Planlar', 'th_from' => 'Başlangıç', 'th_best' => 'Uygun olduğu iş', 'th_link' => 'Planlar',
            'per_mo' => 'aylık', 'see' => 'Görüntüle',
            'empty' => 'Lokasyon listesi güncelleniyor. Danışmanlık için bize ulaşın.',
            'uses_t' => 'Hangi iş için hangi ülke',
            'uses_d' => 'Öneri aracının kullandığı mantık — nedenini bilmeniz için.',
            'uses_top' => 'İlk seçenekler:',
            'check_t' => 'Satın almadan önce bu dört şeyi kontrol edin',
            'check' => [
                'Kullanıcılarınızın konumu: sunucuyu size değil, kullanıcılarınızın çoğuna yakın yerleştirin.',
                'Gerçek gecikme: karar vermeden önce kendi bağlantınızdan hedef şehre ping ve ağ yolunu ölçün.',
                'Aylık trafik: indirme, yedekleme veya yayın için trafik kotası CPU gücünden daha önemlidir.',
                'Hukuk ve veri: AB kullanıcılarının verileri için AB içinde barındırma GDPR yükümlülüklerini kolaylaştırır.',
            ],
            'ping_cta' => 'Online ping testi',
            'faq_t' => 'Yurt dışı VPS hakkında sık sorulan sorular',
            'cross_t' => 'İlgili sayfalar',
            'cross_intl' => 'Yurt dışı VPS satın al', 'cross_hourly' => 'Saatlik VPS', 'cross_trading' => 'Trading VPS',
            'cross_windows' => 'Windows VPS', 'cross_iran' => 'İran VPS', 'cross_aup' => 'Kabul edilebilir kullanım politikası',
        ],
    ],

    /*
    | کاربردها — کلیدها همان کلیدهای وزن در `countries.*.uses` هستند.
    */
    'uses' => [
        'eu_site' => ['icon' => 'globe',
            'fa' => ['t' => 'سایت یا اپ برای کاربران ایران و اروپا', 'd' => 'اروپای مرکزی و غربی کوتاه‌ترین مسیر شبکهٔ بین‌الملل را تا خاورمیانه و اروپا دارد؛ فرانکفورت و آمستردام دو هاب اصلی تبادل ترافیک‌اند.'],
            'en' => ['t' => 'Website or app for Middle East & European users', 'd' => 'Central and Western Europe offer the shortest international routes to both the Middle East and Europe; Frankfurt and Amsterdam are the two main traffic exchange hubs.'],
            'tr' => ['t' => 'Orta Doğu ve Avrupa kullanıcıları için site veya uygulama', 'd' => 'Orta ve Batı Avrupa, hem Orta Doğu\'ya hem Avrupa\'ya en kısa uluslararası rotaları sunar; Frankfurt ve Amsterdam iki ana trafik değişim merkezidir.']],
        'dev' => ['icon' => 'code',
            'fa' => ['t' => 'برنامه‌نویسی، CI و کار با مخازن بین‌المللی', 'd' => 'محیط توسعه و بیلد روی سرور خارج به Docker Hub، npm، PyPI و GitHub دسترسی پایدار و سریع دارد و دانلود وابستگی‌ها کندی نمی‌گیرد.'],
            'en' => ['t' => 'Development, CI and package registries', 'd' => 'A build and development server abroad gets fast, stable access to Docker Hub, npm, PyPI and GitHub, so dependency downloads stop being the bottleneck.'],
            'tr' => ['t' => 'Yazılım geliştirme, CI ve paket depoları', 'd' => 'Yurt dışındaki bir geliştirme ve derleme sunucusu Docker Hub, npm, PyPI ve GitHub\'a hızlı ve kararlı erişim sağlar; bağımlılık indirmeleri darboğaz olmaktan çıkar.']],
        'trading' => ['icon' => 'trend',
            'fa' => ['t' => 'ترید، متاتریدر و ربات معاملاتی', 'd' => 'برای ربات معاملاتی، نزدیکی به سرور بروکر از قدرت سخت‌افزار مهم‌تر است. بسیاری از بروکرها سرورشان را در لندن یا نیویورک دارند؛ سرور بروکر خود را اول بررسی کنید.'],
            'en' => ['t' => 'Trading, MetaTrader and bots', 'd' => 'For a trading bot, proximity to the broker\'s server matters more than raw hardware. Many brokers run their servers in London or New York — check yours first.'],
            'tr' => ['t' => 'Trading, MetaTrader ve botlar', 'd' => 'Bir trading botu için broker sunucusuna yakınlık donanım gücünden daha önemlidir. Birçok broker sunucusunu Londra veya New York\'ta çalıştırır — önce kendi brokerınızı kontrol edin.']],
        'remote' => ['icon' => 'monitor',
            'fa' => ['t' => 'ریموت دسکتاپ و ابزارهای کار از راه دور', 'd' => 'برای کار روزانه با ریموت دسکتاپ، تأخیر کم مهم‌ترین عامل است؛ کشورهای اروپایی نزدیک‌تر معمولاً تجربهٔ روان‌تری می‌دهند.'],
            'en' => ['t' => 'Remote desktop and remote-work tools', 'd' => 'For daily remote desktop use, low latency is the key factor; nearer European countries usually feel smoother.'],
            'tr' => ['t' => 'Uzak masaüstü ve uzaktan çalışma araçları', 'd' => 'Günlük uzak masaüstü kullanımında düşük gecikme en önemli etkendir; yakın Avrupa ülkeleri genellikle daha akıcı bir deneyim sunar.']],
        'global' => ['icon' => 'users',
            'fa' => ['t' => 'کاربران در آمریکا یا آسیا', 'd' => 'اگر مخاطب اصلی در آمریکای شمالی یا شرق آسیاست، سرور را در همان قاره بگذارید؛ آمریکا و سنگاپور هاب‌های اصلی این مناطق‌اند.'],
            'en' => ['t' => 'Users in the Americas or Asia', 'd' => 'If most of your audience is in North America or East Asia, host on that continent; the USA and Singapore are the main hubs for those regions.'],
            'tr' => ['t' => 'Amerika veya Asya\'daki kullanıcılar', 'd' => 'Kitlenizin çoğu Kuzey Amerika veya Doğu Asya\'daysa sunucuyu o kıtada barındırın; ABD ve Singapur bu bölgelerin ana merkezleridir.']],
        'storage' => ['icon' => 'hdd',
            'fa' => ['t' => 'بکاپ، دانلود و ترافیک زیاد', 'd' => 'برای بکاپ و سرو فایل، سقف ترافیک ماهانه و قیمت هر گیگ دیسک تعیین‌کننده است؛ کشورهای شمال اروپا معمولاً از نظر هزینه به‌صرفه‌ترند.'],
            'en' => ['t' => 'Backups, downloads and heavy traffic', 'd' => 'For backups and file serving, the monthly traffic allowance and price per GB of disk decide; Nordic locations are usually the most cost-efficient.'],
            'tr' => ['t' => 'Yedekleme, indirme ve yoğun trafik', 'd' => 'Yedekleme ve dosya sunumu için aylık trafik kotası ve GB başına disk fiyatı belirleyicidir; Kuzey Avrupa lokasyonları genellikle en ekonomik olanlardır.']],
        'learn' => ['icon' => 'cap',
            'fa' => ['t' => 'آموزش لینوکس و پروژهٔ آزمایشی', 'd' => 'برای یادگیری و تست، ارزان‌ترین پلن کافی است؛ با پرداخت ساعتی حتی می‌توانید بعد از چند ساعت سرور را حذف کنید.'],
            'en' => ['t' => 'Learning Linux and test projects', 'd' => 'For learning and testing, the cheapest plan is enough; with hourly billing you can even delete the server after a few hours.'],
            'tr' => ['t' => 'Linux öğrenimi ve test projeleri', 'd' => 'Öğrenmek ve test etmek için en ucuz plan yeterlidir; saatlik ödemeyle sunucuyu birkaç saat sonra silebilirsiniz bile.']],
    ],

    /*
    | کشورها. `region` برای اولویتِ «نزدیکی» است (eu/cis نزدیک‌تر از na/asia —
    | جغرافیا، نه ادعای ms). وزن‌ها ۰..۳.
    */
    'countries' => [
        'DE' => ['region' => 'eu', 'uses' => ['eu_site' => 3, 'dev' => 3, 'trading' => 1, 'remote' => 3, 'global' => 1, 'storage' => 2, 'learn' => 2],
            'fa' => 'فرانکفورت محل DE-CIX، یکی از بزرگ‌ترین نقاط تبادل ترافیک اینترنت دنیاست؛ محبوب‌ترین انتخاب کاربران ایرانی برای سرور خارج.',
            'en' => 'Frankfurt is home to DE-CIX, one of the world\'s largest internet exchange points — the most popular foreign location among our users.',
            'tr' => 'Frankfurt, dünyanın en büyük internet değişim noktalarından DE-CIX\'e ev sahipliği yapar — kullanıcılarımızın en çok tercih ettiği yurt dışı lokasyon.'],
        'NL' => ['region' => 'eu', 'uses' => ['eu_site' => 3, 'dev' => 3, 'trading' => 2, 'remote' => 2, 'global' => 1, 'storage' => 2, 'learn' => 2],
            'fa' => 'آمستردام با AMS-IX از پراتصال‌ترین شهرهای اینترنت اروپاست؛ گزینهٔ متعادل برای سایت، توسعه و سرویس‌های بین‌المللی.',
            'en' => 'Amsterdam, with AMS-IX, is one of Europe\'s best-connected internet cities — a balanced choice for websites, development and international services.',
            'tr' => 'AMS-IX ile Amsterdam, Avrupa\'nın en iyi bağlantıya sahip internet şehirlerinden biridir — site, geliştirme ve uluslararası hizmetler için dengeli bir seçim.'],
        'FI' => ['region' => 'eu', 'uses' => ['eu_site' => 2, 'dev' => 2, 'trading' => 0, 'remote' => 1, 'global' => 1, 'storage' => 3, 'learn' => 3],
            'fa' => 'هلسینکی در شمال اروپا معمولاً از به‌صرفه‌ترین لوکیشن‌هاست؛ مناسب بکاپ، ذخیره‌سازی و پروژه‌هایی که هزینه در آن‌ها اولویت دارد.',
            'en' => 'Helsinki in Northern Europe is usually among the most cost-efficient locations — good for backups, storage and cost-sensitive projects.',
            'tr' => 'Kuzey Avrupa\'daki Helsinki genellikle en ekonomik lokasyonlardandır — yedekleme, depolama ve maliyet odaklı projeler için uygundur.'],
        'FR' => ['region' => 'eu', 'uses' => ['eu_site' => 3, 'dev' => 2, 'trading' => 1, 'remote' => 2, 'global' => 1, 'storage' => 2, 'learn' => 2],
            'fa' => 'پاریس برای مخاطبان فرانسه و جنوب و غرب اروپا انتخاب طبیعی است و در اتحادیهٔ اروپا قرار دارد.',
            'en' => 'Paris is the natural pick for audiences in France and Southern/Western Europe, inside the EU.',
            'tr' => 'Paris, Fransa ve Güney/Batı Avrupa kitlesi için doğal bir seçimdir ve AB içindedir.'],
        'SE' => ['region' => 'eu', 'uses' => ['eu_site' => 2, 'dev' => 2, 'trading' => 0, 'remote' => 1, 'global' => 1, 'storage' => 2, 'learn' => 2],
            'fa' => 'استکهلم برای مخاطبان کشورهای شمال اروپا مناسب است و در اتحادیهٔ اروپا قرار دارد.',
            'en' => 'Stockholm suits audiences in the Nordic countries and sits inside the EU.',
            'tr' => 'Stockholm, İskandinav ülkelerindeki kitleye uygundur ve AB içindedir.'],
        'AT' => ['region' => 'eu', 'uses' => ['eu_site' => 3, 'dev' => 2, 'trading' => 1, 'remote' => 2, 'global' => 1, 'storage' => 1, 'learn' => 2],
            'fa' => 'وین در اروپای مرکزی، برای مخاطبان اروپای مرکزی و شرقی موقعیت جغرافیایی خوبی دارد.',
            'en' => 'Vienna in Central Europe is well placed for audiences in Central and Eastern Europe.',
            'tr' => 'Orta Avrupa\'daki Viyana, Orta ve Doğu Avrupa kitlesi için iyi konumdadır.'],
        'GB' => ['region' => 'eu', 'uses' => ['eu_site' => 2, 'dev' => 2, 'trading' => 3, 'remote' => 2, 'global' => 1, 'storage' => 1, 'learn' => 1],
            'fa' => 'لندن مرکز مالی اروپاست و سرور بسیاری از بروکرهای فارکس آن‌جاست؛ برای ترید با تأخیر کم گزینهٔ اول.',
            'en' => 'London is Europe\'s financial centre and many forex brokers run their servers there — the first choice for low-latency trading.',
            'tr' => 'Londra Avrupa\'nın finans merkezidir ve birçok forex brokerı sunucularını orada çalıştırır — düşük gecikmeli trading için ilk tercih.'],
        'US' => ['region' => 'na', 'uses' => ['eu_site' => 0, 'dev' => 3, 'trading' => 2, 'remote' => 1, 'global' => 3, 'storage' => 2, 'learn' => 1],
            'fa' => 'آمریکا برای کاربران آمریکای شمالی و سرویس‌هایی که به APIهای مستقر در آمریکا وصل می‌شوند مناسب است.',
            'en' => 'The USA suits North American users and services that talk to US-hosted APIs.',
            'tr' => 'ABD, Kuzey Amerika kullanıcıları ve ABD\'de barındırılan API\'lerle çalışan hizmetler için uygundur.'],
        'SG' => ['region' => 'asia', 'uses' => ['eu_site' => 0, 'dev' => 2, 'trading' => 1, 'remote' => 1, 'global' => 3, 'storage' => 1, 'learn' => 1],
            'fa' => 'سنگاپور هاب اینترنت جنوب شرق آسیاست؛ برای مخاطبان آسیا و اقیانوسیه.',
            'en' => 'Singapore is the internet hub of Southeast Asia — for audiences in Asia-Pacific.',
            'tr' => 'Singapur, Güneydoğu Asya\'nın internet merkezidir — Asya-Pasifik kitlesi için.'],
        'RU' => ['region' => 'cis', 'uses' => ['eu_site' => 1, 'dev' => 1, 'trading' => 0, 'remote' => 2, 'global' => 1, 'storage' => 1, 'learn' => 2],
            'fa' => 'روسیه برای مخاطبان روسی‌زبان و کشورهای مستقل مشترک‌المنافع انتخاب مناسبی است.',
            'en' => 'Russia is a good fit for Russian-speaking audiences and CIS countries.',
            'tr' => 'Rusya, Rusça konuşan kitle ve BDT ülkeleri için uygun bir seçimdir.'],
    ],

    'faq' => [
        'fa' => [
            ['q' => 'بهترین کشور برای سرور مجازی خارج کدام است؟', 'a' => 'پاسخ یکسانی ندارد: برای سایتی که کاربران ایران و اروپا دارد آلمان و هلند معمولاً بهترین‌اند، برای ترید کشور محل سرور بروکر (اغلب انگلیس یا آمریکا)، و برای بکاپ و ذخیره‌سازی کشورهای شمال اروپا مثل فنلاند به‌صرفه‌ترند.'],
            ['q' => 'سرور خارج را با ریال می‌شود خرید؟', 'a' => 'بله. قیمت‌ها به تومان نمایش داده می‌شوند و پرداخت با درگاه ایرانی یا کیف پول حساب انجام می‌شود؛ نیازی به کارت ارزی ندارید.'],
            ['q' => 'تحویل سرور خارج چقدر طول می‌کشد؟', 'a' => 'پس از پرداخت، سرور به‌صورت خودکار ساخته می‌شود و اطلاعات ورود در پنل و ایمیل شما قرار می‌گیرد؛ معمولاً ظرف چند دقیقه.'],
            ['q' => 'دسترسی root دارم و هر سیستم‌عاملی نصب می‌شود؟', 'a' => 'بله، دسترسی کامل root یا Administrator دارید و از فهرست توزیع‌های لینوکس و ویندوز می‌توانید انتخاب کنید. استفاده باید مطابق قوانین استفادهٔ سرورنت باشد.'],
            ['q' => 'آیا بعد از خرید می‌توانم کشور سرور را عوض کنم؟', 'a' => 'جابه‌جایی مستقیم بین کشورها ممکن نیست؛ سرور جدید در کشور مقصد می‌سازید، داده را منتقل می‌کنید و سرور قبلی را حذف می‌کنید. با پرداخت ساعتی این جابه‌جایی کم‌هزینه است.'],
            ['q' => 'تأخیر (پینگ) هر کشور از ایران چقدر است؟', 'a' => 'به اپراتور اینترنت و مسیر روز بستگی دارد و عدد ثابتی نیست. پیش از خرید، با دستور ping یا mtr از اینترنت خودتان تا شهر مقصد اندازه بگیرید.'],
            ['q' => 'ماهانه بخرم یا ساعتی؟', 'a' => 'برای سرویس همیشه‌روشن، ماهانه ارزان‌تر است. برای تست، آموزش یا کار چندساعته، پرداخت ساعتی از کیف پول به‌صرفه‌تر است.'],
        ],
        'en' => [
            ['q' => 'What is the best country for an international VPS?', 'a' => 'It depends: for a site serving the Middle East and Europe, Germany and the Netherlands are usually best; for trading, the country where your broker\'s server is (often the UK or USA); for backups and storage, Nordic locations such as Finland are the most cost-efficient.'],
            ['q' => 'How fast is an international VPS delivered?', 'a' => 'After payment the server is built automatically and the login details appear in your panel and email — usually within minutes.'],
            ['q' => 'Do I get root access and my choice of OS?', 'a' => 'Yes — full root or Administrator access, with a choice of Linux distributions and Windows. Use must follow ServerNet\'s acceptable use policy.'],
            ['q' => 'Can I change the server\'s country after buying?', 'a' => 'Not in place: create a new server in the target country, move your data and delete the old one. With hourly billing that move is cheap.'],
            ['q' => 'What is the latency to each country?', 'a' => 'It depends on your ISP and the day\'s routing, so there is no fixed number. Measure from your own connection to the target city with a ping tool or mtr before you buy.'],
            ['q' => 'Monthly or hourly billing?', 'a' => 'For an always-on service, monthly is cheaper. For tests, learning or a few hours of work, hourly billing from your wallet costs less.'],
        ],
        'tr' => [
            ['q' => 'Yurt dışı VPS için en iyi ülke hangisi?', 'a' => 'Duruma göre değişir: Orta Doğu ve Avrupa\'ya hizmet veren bir site için genellikle Almanya ve Hollanda en iyisidir; trading için brokerınızın sunucusunun bulunduğu ülke (çoğunlukla İngiltere veya ABD); yedekleme ve depolama için Finlandiya gibi Kuzey Avrupa lokasyonları en ekonomik olanlardır.'],
            ['q' => 'Yurt dışı VPS ne kadar sürede teslim edilir?', 'a' => 'Ödemeden sonra sunucu otomatik olarak oluşturulur ve giriş bilgileri panelinize ve e-postanıza gelir — genellikle birkaç dakika içinde.'],
            ['q' => 'Root erişimim olacak mı, işletim sistemini seçebilir miyim?', 'a' => 'Evet — tam root veya Administrator erişimi ve Linux dağıtımları ile Windows arasından seçim. Kullanım, ServerNet kabul edilebilir kullanım politikasına uygun olmalıdır.'],
            ['q' => 'Satın aldıktan sonra sunucunun ülkesini değiştirebilir miyim?', 'a' => 'Yerinde değiştirilemez: hedef ülkede yeni bir sunucu oluşturup verilerinizi taşır ve eskisini silersiniz. Saatlik ödemeyle bu taşıma düşük maliyetlidir.'],
            ['q' => 'Her ülkeye gecikme ne kadar?', 'a' => 'İnternet sağlayıcınıza ve günün yönlendirmesine bağlıdır, sabit bir rakam yoktur. Satın almadan önce kendi bağlantınızdan hedef şehre ping aracı veya mtr ile ölçün.'],
            ['q' => 'Aylık mı saatlik mi ödeme?', 'a' => 'Sürekli açık bir hizmet için aylık daha ucuzdur. Test, öğrenme veya birkaç saatlik iş için cüzdandan saatlik ödeme daha ekonomiktir.'],
        ],
    ],
];
