version: "3.8"

services:
  web:
    build: .
    container_name: servernet-web-1
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: servernet-db-1
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: SuperStrongPass123
      MYSQL_DATABASE: servernet_db
      MYSQL_USER: serveruser
      MYSQL_PASSWORD: SuperStrongPass456
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: