<?php

/*
|--------------------------------------------------------------------------
| کاتالوگ خدمات ابری — ۱۱ صفحه (fa / en / tr)
|--------------------------------------------------------------------------
*/

$traffic = ['fa' => 'ترافیک نامحدود', 'en' => 'Unlimited traffic', 'tr' => 'Sınırsız trafik'];
$api = ['fa' => 'API و CLI کامل', 'en' => 'Full API & CLI', 'tr' => 'Tam API ve CLI'];

$mk = fn (string $name, int $pid, int $irt, float $eur, array $specs, bool $pop = false) =>
    array_filter(['name' => $name, 'pid' => $pid, 'irt' => $irt, 'eur' => $eur, 'specs' => $specs, 'popular' => $pop]);

return [

    'iaas' => [
        'icon' => 'cloud', 'group' => 'compute',
        'fa' => ['t' => 'زیرساخت ابری (IaaS)', 'tag' => 'پرداخت ساعتی · API کامل',
            'hero_t' => 'زیرساخت ابری،', 'hero_g' => 'در چند ثانیه، با یک API.',
            'hero_d' => 'سرور، شبکه خصوصی، فایروال و استوریج — همه با API و پرداخت ساعتی. زیرساختی که با کد ساخته می‌شود و با رشد شما مقیاس می‌گیرد.'],
        'en' => ['t' => 'Cloud Infrastructure (IaaS)', 'tag' => 'Hourly billing · Full API',
            'hero_t' => 'Cloud infrastructure', 'hero_g' => 'in seconds, via one API.',
            'hero_d' => 'Servers, private networks, firewalls and storage — all API-driven and billed hourly. Infrastructure as code that scales with you.'],
        'tr' => ['t' => 'Bulut Altyapı (IaaS)', 'tag' => 'Saatlik ödeme · Tam API',
            'hero_t' => 'Saniyeler içinde, tek API ile', 'hero_g' => 'bulut altyapısı.',
            'hero_d' => 'Sunucular, özel ağlar, güvenlik duvarları ve depolama — hepsi API ile, saatlik faturalandırma.'],
        'chips' => ['Hourly Billing', 'REST API + CLI', 'Terraform Provider', 'Private Networking', 'NVMe RAID-10'],
        'signature' => ['type' => 'term',
            'fa' => ['t' => 'زیرساخت با یک خط دستور', 'd' => 'CLI سرورنت — سرور بسازید، اسنپ‌شات بگیرید، مقیاس بدهید'],
            'en' => ['t' => 'Infrastructure in one command', 'd' => 'The ServerNet CLI — create servers, snapshot, scale'],
            'tr' => ['t' => 'Tek komutla altyapı', 'd' => 'ServerNet CLI — sunucu oluşturun, snapshot alın, ölçekleyin'],
            'lines' => [
                ['c', '# Create a server with the ServerNet CLI'],
                ['p', '$ snet server create --plan c-2 --image ubuntu-24.04 --region ir-thr'],
                ['ok', '✔ server created in 38s → ip 185.xx.xx.42'],
                ['p', '$ snet snapshot create srv-8f2a --label pre-deploy'],
                ['ok', '✔ snapshot saved (12 GB, incremental)'],
                ['p', '$ snet server resize srv-8f2a --plan c-4'],
                ['ok', '✔ resized live — no reboot required'],
            ]],
        'plans' => [
            $mk('C-1', 170, 590000, 5.90, ['1 vCPU / 2 GB RAM', '25 GB NVMe', ['fa' => '~۸۲۰ تومان/ساعت', 'en' => '~€0.009/hour', 'tr' => '~€0,009/saat'], $traffic, $api]),
            $mk('C-2', 171, 1090000, 10.90, ['2 vCPU / 4 GB RAM', '60 GB NVMe', ['fa' => '~۱,۵۲۰ تومان/ساعت', 'en' => '~€0.016/hour', 'tr' => '~€0,016/saat'], $traffic, $api], true),
            $mk('C-4', 172, 1990000, 19.90, ['4 vCPU / 8 GB RAM', '120 GB NVMe', ['fa' => '~۲,۷۷۰ تومان/ساعت', 'en' => '~€0.028/hour', 'tr' => '~€0,028/saat'], $traffic, $api]),
            $mk('C-8', 173, 3790000, 37.90, ['8 vCPU / 16 GB RAM', '240 GB NVMe', ['fa' => '~۵,۲۷۰ تومان/ساعت', 'en' => '~€0.053/hour', 'tr' => '~€0,053/saat'], $traffic, $api]),
        ],
        'features' => ['hourly', 'scale', 'instant', 'net10', 'backup', 'support'],
        'faqs' => ['activation',
            ['fa' => ['q' => 'Terraform و Ansible پشتیبانی می‌شود؟', 'a' => 'بله — Provider رسمی Terraform و کالکشن Ansible داریم؛ به‌علاوه REST API کامل با مستندات OpenAPI و SDK پایتون/Node.'],
             'en' => ['q' => 'Do you support Terraform and Ansible?', 'a' => 'Yes — we ship an official Terraform provider and Ansible collection, plus a full REST API with OpenAPI docs and Python/Node SDKs.'],
             'tr' => ['q' => 'Terraform ve Ansible destekleniyor mu?', 'a' => 'Evet — resmi Terraform provider ve Ansible koleksiyonumuz var; ayrıca OpenAPI dokümanlı tam REST API.']],
            'os', 'refund',
        ],
    ],

    'gpuaas' => [
        'icon' => 'monitor', 'group' => 'compute',
        'fa' => ['t' => 'زیرساخت گرافیکی (GPUaaS)', 'tag' => 'A100 · H100 · ساعتی',
            'hero_t' => 'GPU ابری،', 'hero_g' => 'فقط وقتی که لازمش دارید.',
            'hero_d' => 'قوی‌ترین GPUهای NVIDIA با پرداخت ساعتی — مدل را آموزش بدهید، سرویس را اجرا کنید، خاموش کنید. بدون سرمایه‌گذاری سنگین سخت‌افزاری.'],
        'en' => ['t' => 'GPU Cloud (GPUaaS)', 'tag' => 'A100 · H100 · Hourly',
            'hero_t' => 'Cloud GPUs,', 'hero_g' => 'only when you need them.',
            'hero_d' => 'NVIDIA\'s strongest GPUs billed hourly — train your model, serve it, shut it down. No heavy hardware investment.'],
        'tr' => ['t' => 'GPU Bulut (GPUaaS)', 'tag' => 'A100 · H100 · Saatlik',
            'hero_t' => 'Bulut GPU\'lar,', 'hero_g' => 'sadece ihtiyaç anında.',
            'hero_d' => 'Saatlik faturalandırılan en güçlü NVIDIA GPU\'lar — eğitin, servis edin, kapatın.'],
        'chips' => ['A100 / H100', 'Hourly Billing', 'CUDA 12', 'NVLink', 'Jupyter Ready'],
        'plans' => [
            $mk('G-RTX', 174, 4900000, 49.00, ['RTX 4000 Ada · 20 GB', '8 vCPU / 32 GB RAM', ['fa' => '~۶,۸۰۰ تومان/ساعت', 'en' => '~€0.068/hour', 'tr' => '~€0,068/saat'], '250 GB NVMe', $api]),
            $mk('G-A100', 175, 14900000, 149.00, ['A100 · 40 GB HBM2e', '16 vCPU / 128 GB RAM', ['fa' => '~۲۰,۷۰۰ تومان/ساعت', 'en' => '~€0.207/hour', 'tr' => '~€0,207/saat'], '1 TB NVMe', $api], true),
            $mk('G-H100', 176, 34900000, 349.00, ['H100 · 80 GB HBM3', '32 vCPU / 256 GB RAM', ['fa' => '~۴۸,۵۰۰ تومان/ساعت', 'en' => '~€0.485/hour', 'tr' => '~€0,485/saat'], '2 TB NVMe', $api]),
        ],
        'features' => ['hourly', 'instant', 'scale', 'support',
            ['icon' => 'bot',
                'fa' => ['t' => 'ایمیج‌های آماده ML', 'd' => 'PyTorch، TensorFlow، JAX و vLLM از پیش نصب — GPU از دقیقه اول مشغول کار واقعی است.'],
                'en' => ['t' => 'Ready ML Images', 'd' => 'PyTorch, TensorFlow, JAX and vLLM pre-installed — your GPU does real work from minute one.'],
                'tr' => ['t' => 'Hazır ML İmajları', 'd' => 'PyTorch, TensorFlow, JAX ve vLLM kurulu — GPU ilk dakikadan gerçek iş yapar.']],
        ],
        'faqs' => ['activation',
            ['fa' => ['q' => 'برای مدل‌های زبانی بزرگ کدام GPU مناسب است؟', 'a' => 'برای inference مدل‌های تا 13B پارامتر A100 40GB کافی است؛ آموزش یا مدل‌های بزرگ‌تر H100 80GB می‌خواهند. تیم ما رایگان به شما در انتخاب و تخمین هزینه کمک می‌کند.'],
             'en' => ['q' => 'Which GPU for large language models?', 'a' => 'For inference up to ~13B parameters, the A100 40GB is enough; training or larger models want the H100 80GB. Our team helps you size and estimate costs for free.'],
             'tr' => ['q' => 'Büyük dil modelleri için hangi GPU?', 'a' => '~13B parametreye kadar inference için A100 40GB yeterli; eğitim veya daha büyük modeller H100 80GB ister.']],
            'refund',
        ],
    ],

    'bmaas' => [
        'icon' => 'server', 'group' => 'compute',
        'fa' => ['t' => 'زیرساخت اختصاصی (BMaaS)', 'tag' => 'Bare-Metal · تحویل ۲ ساعته',
            'hero_t' => 'فلز خالص،', 'hero_g' => 'با تجربه‌ی ابری.',
            'hero_d' => 'سرور فیزیکی کامل بدون لایه مجازی‌سازی — با همان API، پرداخت ساعتی و تحویل سریع ابر. برای دیتابیس‌ها و بارهای کاری حساس به کارایی.'],
        'en' => ['t' => 'Bare-Metal Cloud (BMaaS)', 'tag' => 'Bare-metal · 2-hour delivery',
            'hero_t' => 'Pure metal,', 'hero_g' => 'with a cloud experience.',
            'hero_d' => 'Full physical servers with zero virtualization — same API, hourly billing and fast delivery as cloud. For databases and performance-critical loads.'],
        'tr' => ['t' => 'Bare-Metal Bulut (BMaaS)', 'tag' => 'Bare-metal · 2 saatte teslim',
            'hero_t' => 'Saf metal,', 'hero_g' => 'bulut deneyimiyle.',
            'hero_d' => 'Sanallaştırmasız tam fiziksel sunucular — bulutla aynı API, saatlik ödeme ve hızlı teslim.'],
        'chips' => ['No Hypervisor', 'Hourly Billing', 'API Provisioning', 'NVMe Gen4', '2h Delivery'],
        'plans' => [
            $mk('BM-1', 177, 6900000, 69.00, ['Ryzen 7 7700 · 8c/16t', '64 GB DDR5 ECC', '2 × 512 GB NVMe Gen4', ['fa' => 'پرداخت ساعتی', 'en' => 'Hourly billing', 'tr' => 'Saatlik ödeme'], $api]),
            $mk('BM-2', 178, 9900000, 99.00, ['Ryzen 9 7950X · 16c/32t', '128 GB DDR5 ECC', '2 × 1 TB NVMe Gen4', ['fa' => 'پرداخت ساعتی', 'en' => 'Hourly billing', 'tr' => 'Saatlik ödeme'], $api], true),
            array_merge($mk('BM-XL', 179, 0, 0, ['EPYC · up to 96 cores', 'Up to 1 TB ECC RAM', 'Custom NVMe array', ['fa' => 'پرداخت ساعتی', 'en' => 'Hourly billing', 'tr' => 'Saatlik ödeme'], $api]), ['contact' => true]),
        ],
        'features' => ['hourly', 'root', 'instant', 'net10', 'scale', 'support'],
        'faqs' => ['activation', 'os',
            ['fa' => ['q' => 'فرق BMaaS با سرور اختصاصی معمولی چیست؟', 'a' => 'سخت‌افزار همان است؛ تجربه فرق دارد: تحویل ۲ ساعته به‌جای ۲۴ ساعت، پرداخت ساعتی به‌جای ماهانه و ساخت/حذف با API — انعطاف ابر با قدرت فلز.'],
             'en' => ['q' => 'How is BMaaS different from regular dedicated?', 'a' => 'Same hardware, different experience: 2-hour delivery instead of 24, hourly instead of monthly billing, and API create/destroy — cloud flexibility with metal power.'],
             'tr' => ['q' => 'BMaaS normal dedicated\'dan nasıl farklı?', 'a' => 'Donanım aynı, deneyim farklı: 24 saat yerine 2 saatte teslim, aylık yerine saatlik ödeme ve API ile oluştur/sil.']],
            'refund',
        ],
    ],

    'kubernetes' => [
        'icon' => 'flow', 'group' => 'compute',
        'fa' => ['t' => 'کلاستر کوبرنتیز (KaaS)', 'tag' => 'Managed K8s · کنترل‌پلین رایگان',
            'hero_t' => 'کوبرنتیز مدیریت‌شده،', 'hero_g' => 'بدون دردسر کوبرنتیز.',
            'hero_d' => 'کلاستر آماده با کنترل‌پلین رایگان و HA — آپگرید، پچ و مانیتورینگ با ما؛ شما فقط deploy کنید. سازگار کامل با اکوسیستم CNCF.'],
        'en' => ['t' => 'Kubernetes (KaaS)', 'tag' => 'Managed K8s · Free control plane',
            'hero_t' => 'Managed Kubernetes,', 'hero_g' => 'minus the Kubernetes pain.',
            'hero_d' => 'Ready clusters with a free, HA control plane — we handle upgrades, patches and monitoring; you just deploy. Fully CNCF-conformant.'],
        'tr' => ['t' => 'Kubernetes (KaaS)', 'tag' => 'Yönetilen K8s · Ücretsiz control plane',
            'hero_t' => 'Yönetilen Kubernetes,', 'hero_g' => 'Kubernetes derdi olmadan.',
            'hero_d' => 'Ücretsiz ve HA control plane\'li hazır kümeler — yükseltme ve izleme bizde; siz sadece deploy edin.'],
        'chips' => ['CNCF Conformant', 'Free Control Plane', 'Auto-Scaling', 'LB + Storage CSI', 'kubectl Ready'],
        'signature' => ['type' => 'term',
            'fa' => ['t' => 'کلاستر واقعی، در سه دقیقه', 'd' => 'از ساخت کلاستر تا اولین deploy — بدون نصب حتی یک باینری روی سرور'],
            'en' => ['t' => 'A real cluster in three minutes', 'd' => 'From cluster creation to first deploy — without installing a single binary on a server'],
            'tr' => ['t' => 'Üç dakikada gerçek küme', 'd' => 'Küme oluşturmadan ilk deploy\'a'],
            'lines' => [
                ['p', '$ snet k8s create --name prod --nodes 3 --plan k-4'],
                ['ok', '✔ cluster ready in 2m41s (v1.31, HA control plane)'],
                ['p', '$ snet k8s kubeconfig prod > ~/.kube/config'],
                ['p', '$ kubectl get nodes'],
                ['w', 'prod-node-1   Ready   45s    prod-node-2   Ready   43s'],
                ['p', '$ kubectl apply -f app.yaml'],
                ['ok', '✔ deployment.apps/shop created — LB: 185.xx.xx.10'],
            ]],
        'plans' => [
            $mk('K-DEV', 180, 1990000, 19.90, [['fa' => '۲ نود کارگر ۲v/4G', 'en' => '2 worker nodes 2v/4G', 'tr' => '2 worker düğümü 2v/4G'], ['fa' => 'کنترل‌پلین مشترک رایگان', 'en' => 'Free shared control plane', 'tr' => 'Ücretsiz paylaşımlı control plane'], '80 GB NVMe CSI', ['fa' => 'لودبالانسر ۱ عدد', 'en' => '1 load balancer', 'tr' => '1 yük dengeleyici'], $api]),
            $mk('K-PROD', 181, 5900000, 59.00, [['fa' => '۳ نود کارگر ۴v/8G', 'en' => '3 worker nodes 4v/8G', 'tr' => '3 worker düğümü 4v/8G'], ['fa' => 'کنترل‌پلین HA اختصاصی', 'en' => 'Dedicated HA control plane', 'tr' => 'Özel HA control plane'], '360 GB NVMe CSI', ['fa' => 'اتواسکیل + ۲ لودبالانسر', 'en' => 'Autoscaling + 2 LBs', 'tr' => 'Otomatik ölçek + 2 LB'], $api], true),
            array_merge($mk('K-ENT', 182, 0, 0, [['fa' => 'نودپول سفارشی + GPU', 'en' => 'Custom node pools + GPU', 'tr' => 'Özel node pool + GPU'], ['fa' => 'چند کلاستر + GitOps', 'en' => 'Multi-cluster + GitOps', 'tr' => 'Çoklu küme + GitOps'], ['fa' => 'SLA اختصاصی', 'en' => 'Custom SLA', 'tr' => 'Özel SLA'], ['fa' => 'مهندس پلتفرم اختصاصی', 'en' => 'Dedicated platform engineer', 'tr' => 'Özel platform mühendisi'], $api]), ['contact' => true]),
        ],
        'features' => ['scale', 'uptime', 'backup', 'support', 'net10',
            ['icon' => 'flow',
                'fa' => ['t' => 'آپگرید بدون قطعی', 'd' => 'نسخه‌های جدید کوبرنتیز را ما با استراتژی rolling و بدون حتی یک ثانیه قطعی سرویس اعمال می‌کنیم.'],
                'en' => ['t' => 'Zero-Downtime Upgrades', 'd' => 'We roll out new Kubernetes versions with rolling strategies and zero service interruption.'],
                'tr' => ['t' => 'Kesintisiz Yükseltmeler', 'd' => 'Yeni Kubernetes sürümlerini kesintisiz rolling stratejiyle uygularız.']],
        ],
        'faqs' => ['activation',
            ['fa' => ['q' => 'کنترل‌پلین واقعاً رایگان است؟', 'a' => 'بله — شما فقط هزینه نودهای کارگر، استوریج و لودبالانسر را می‌دهید. کنترل‌پلین (در پلن Prod به‌صورت HA سه‌تایی) کاملاً رایگان است.'],
             'en' => ['q' => 'Is the control plane really free?', 'a' => 'Yes — you only pay for worker nodes, storage and load balancers. The control plane (triple-HA on Prod) is completely free.'],
             'tr' => ['q' => 'Control plane gerçekten ücretsiz mi?', 'a' => 'Evet — yalnızca worker, depolama ve LB için ödersiniz. Control plane tamamen ücretsizdir.']],
            'manage', 'refund',
        ],
    ],

    'cdn' => [
        'icon' => 'globe', 'group' => 'network',
        'fa' => ['t' => 'شبکه توزیع محتوا (CDN)', 'tag' => 'PoPهای ایران + جهان',
            'hero_t' => 'محتوای شما،', 'hero_g' => 'همه‌جا در چند میلی‌ثانیه.',
            'hero_d' => 'CDN با نقاط حضور داخل ایران و شبکه جهانی — کش هوشمند، WAF یکپارچه و SSL رایگان. سایتتان را بدون تغییر کد، چند برابر سریع‌تر کنید.'],
        'en' => ['t' => 'Content Delivery (CDN)', 'tag' => 'Iran + global PoPs',
            'hero_t' => 'Your content,', 'hero_g' => 'everywhere in milliseconds.',
            'hero_d' => 'A CDN with PoPs inside Iran plus a global network — smart caching, integrated WAF and free SSL. Make your site several times faster with zero code changes.'],
        'tr' => ['t' => 'İçerik Dağıtım Ağı (CDN)', 'tag' => 'İran + küresel PoP\'lar',
            'hero_t' => 'İçeriğiniz,', 'hero_g' => 'her yerde milisaniyeler içinde.',
            'hero_d' => 'İran içi PoP\'lar ve küresel ağa sahip CDN — akıllı önbellek, entegre WAF ve ücretsiz SSL.'],
        'chips' => ['Iran PoPs', 'HTTP/3', 'Integrated WAF', 'Free SSL', 'Real-Time Analytics'],
        'signature' => ['type' => 'bars',
            'fa' => ['t' => 'زمان پاسخ اول (TTFB) از تهران', 'd' => 'یک سایت با سرور خارج — قبل و بعد از فعال‌سازی CDN سرورنت'],
            'en' => ['t' => 'TTFB from Tehran', 'd' => 'A site hosted abroad — before and after enabling ServerNet CDN'],
            'tr' => ['t' => 'Tahran\'dan TTFB', 'd' => 'Yurt dışında barındırılan bir site — ServerNet CDN öncesi ve sonrası'],
            'items' => [
                ['fa' => 'با CDN سرورنت (کش تهران)', 'en' => 'With ServerNet CDN (Tehran cache)', 'tr' => 'ServerNet CDN ile', 'val' => '28 ms', 'w' => '100%', 'hl' => true],
                ['fa' => 'بدون CDN — مستقیم از آلمان', 'en' => 'No CDN — direct from Germany', 'tr' => 'CDN\'siz — Almanya\'dan', 'val' => '190 ms', 'w' => '15%'],
                ['fa' => 'بدون CDN — ساعت پیک', 'en' => 'No CDN — peak hours', 'tr' => 'CDN\'siz — yoğun saat', 'val' => '450 ms', 'w' => '6%'],
            ]],
        'plans' => [
            $mk('CDN-START', 183, 290000, 2.90, ['500 GB Traffic / mo', ['fa' => 'PoP تهران + فرانکفورت', 'en' => 'Tehran + Frankfurt PoPs', 'tr' => 'Tahran + Frankfurt PoP'], ['fa' => 'SSL رایگان', 'en' => 'Free SSL', 'tr' => 'Ücretsiz SSL'], ['fa' => 'آمار لحظه‌ای', 'en' => 'Real-time analytics', 'tr' => 'Canlı analitik'], 'HTTP/3 + Brotli']),
            $mk('CDN-BIZ', 184, 990000, 9.90, ['5 TB Traffic / mo', ['fa' => 'همه PoPها + WAF', 'en' => 'All PoPs + WAF', 'tr' => 'Tüm PoP\'lar + WAF'], ['fa' => 'قوانین کش پیشرفته', 'en' => 'Advanced cache rules', 'tr' => 'Gelişmiş önbellek kuralları'], ['fa' => 'Image Optimizer', 'en' => 'Image optimizer', 'tr' => 'Görsel iyileştirici'], 'HTTP/3 + Brotli'], true),
            array_merge($mk('CDN-ENT', 185, 0, 0, [['fa' => 'ترافیک نامحدود سفارشی', 'en' => 'Custom unlimited traffic', 'tr' => 'Özel sınırsız trafik'], ['fa' => 'PoP اختصاصی سازمانی', 'en' => 'Private enterprise PoP', 'tr' => 'Özel kurumsal PoP'], ['fa' => 'SLA اختصاصی', 'en' => 'Custom SLA', 'tr' => 'Özel SLA'], ['fa' => 'مهندس اختصاصی', 'en' => 'Dedicated engineer', 'tr' => 'Özel mühendis']]), ['contact' => true]),
        ],
        'features' => ['ddos', 'ssl', 'uptime', 'support', 'instant',
            ['icon' => 'gauge',
                'fa' => ['t' => 'کش هوشمند داخل ایران', 'd' => 'محتوای استاتیک از نزدیک‌ترین PoP داخلی سرو می‌شود — حتی وقتی سرور اصلی شما خارج از کشور است.'],
                'en' => ['t' => 'Smart In-Country Caching', 'd' => 'Static content is served from the nearest domestic PoP — even when your origin is abroad.'],
                'tr' => ['t' => 'Ülke İçi Akıllı Önbellek', 'd' => 'Statik içerik en yakın yerel PoP\'tan sunulur.']],
        ],
        'faqs' => ['activation',
            ['fa' => ['q' => 'راه‌اندازی CDN چقدر کار می‌برد؟', 'a' => 'فقط تغییر NS یا یک رکورد CNAME — بدون تغییر در کد سایت. برای وردپرس افزونه اتصال یک‌کلیکی هم داریم.'],
             'en' => ['q' => 'How much work is CDN setup?', 'a' => 'Just an NS change or a CNAME record — zero code changes. For WordPress we ship a one-click connector plugin.'],
             'tr' => ['q' => 'CDN kurulumu ne kadar iş?', 'a' => 'Sadece NS değişikliği veya bir CNAME kaydı — kodda sıfır değişiklik.']],
            'upgrade', 'refund',
        ],
    ],

    'ddos-protection' => [
        'icon' => 'shield', 'group' => 'network',
        'fa' => ['t' => 'محافظت از حملات DDoS', 'tag' => 'L3 / L4 / L7 · همیشه فعال',
            'hero_t' => 'حمله می‌آید،', 'hero_g' => 'سایت شما نمی‌افتد.',
            'hero_d' => 'سپر چندلایه در برابر حملات حجمی و اپلیکیشنی — تشخیص خودکار زیر ۳ ثانیه، ظرفیت پالایش چند صد گیگابیتی و گزارش شفاف هر حمله.'],
        'en' => ['t' => 'DDoS Protection', 'tag' => 'L3 / L4 / L7 · Always on',
            'hero_t' => 'Attacks will come —', 'hero_g' => 'your site won\'t go down.',
            'hero_d' => 'Multi-layer defense against volumetric and application attacks — sub-3-second automatic detection, hundreds of Gbit scrubbing capacity, transparent per-attack reports.'],
        'tr' => ['t' => 'DDoS Koruması', 'tag' => 'L3 / L4 / L7 · Daima aktif',
            'hero_t' => 'Saldırılar gelecek —', 'hero_g' => 'siteniz düşmeyecek.',
            'hero_d' => 'Hacimsel ve uygulama saldırılarına karşı çok katmanlı savunma — 3 saniyenin altında otomatik tespit.'],
        'chips' => ['Always-On', '< 3s Detection', 'L7 WAF', 'BGP / GRE', 'Attack Reports'],
        'plans' => [
            $mk('SHIELD-ADV', 187, 990000, 9.90, [['fa' => 'پالایش تا ۱۰۰ گیگابیت', 'en' => 'Up to 100 Gbit scrubbing', 'tr' => '100 Gbit\'e kadar temizleme'], 'L3 / L4 / L7', ['fa' => 'WAF با قوانین سفارشی', 'en' => 'WAF with custom rules', 'tr' => 'Özel kurallı WAF'], ['fa' => 'گزارش هر حمله', 'en' => 'Per-attack reports', 'tr' => 'Saldırı başına rapor'], ['fa' => '۱ دامنه / سرویس', 'en' => '1 domain / service', 'tr' => '1 alan adı / hizmet']]),
            $mk('SHIELD-PRO', 188, 2490000, 24.90, [['fa' => 'پالایش تا ۵۰۰ گیگابیت', 'en' => 'Up to 500 Gbit scrubbing', 'tr' => '500 Gbit\'e kadar temizleme'], 'L3 / L4 / L7 + Bot Management', ['fa' => 'WAF + Rate-Limit پیشرفته', 'en' => 'WAF + advanced rate-limiting', 'tr' => 'WAF + gelişmiş hız sınırı'], ['fa' => 'پشتیبانی حین حمله', 'en' => 'Live under-attack support', 'tr' => 'Saldırı anında canlı destek'], ['fa' => '۵ دامنه / سرویس', 'en' => '5 domains / services', 'tr' => '5 alan adı / hizmet']], true),
            array_merge($mk('SHIELD-ENT', 189, 0, 0, [['fa' => 'ظرفیت پالایش سفارشی', 'en' => 'Custom scrubbing capacity', 'tr' => 'Özel temizleme kapasitesi'], 'BGP / GRE Tunnel', ['fa' => 'SOC اختصاصی ۲۴/۷', 'en' => 'Dedicated 24/7 SOC', 'tr' => 'Özel 7/24 SOC'], ['fa' => 'SLA اختصاصی', 'en' => 'Custom SLA', 'tr' => 'Özel SLA'], ['fa' => 'دامنه نامحدود', 'en' => 'Unlimited domains', 'tr' => 'Sınırsız alan adı']]), ['contact' => true]),
        ],
        'features' => ['ddos', 'uptime', 'support', 'instant',
            ['icon' => 'gauge',
                'fa' => ['t' => 'تشخیص زیر ۳ ثانیه', 'd' => 'الگوریتم‌های ما ترافیک را لحظه‌ای تحلیل می‌کنند و حمله را قبل از رسیدن به سرور شما خنثی می‌کنند.'],
                'en' => ['t' => 'Sub-3-Second Detection', 'd' => 'Our algorithms analyze traffic in real time and neutralize attacks before they reach your server.'],
                'tr' => ['t' => '3 Saniyenin Altında Tespit', 'd' => 'Algoritmalarımız trafiği anlık analiz eder ve saldırıyı sunucunuza ulaşmadan etkisizleştirir.']],
            ['icon' => 'book',
                'fa' => ['t' => 'گزارش شفاف هر حمله', 'd' => 'نوع، حجم، مبدأ و مدت هر حمله را در پنل ببینید — بدانید دقیقاً از چه چیزی محافظت شدید.'],
                'en' => ['t' => 'Transparent Attack Reports', 'd' => 'See the type, volume, origin and duration of every attack in your panel — know exactly what you were protected from.'],
                'tr' => ['t' => 'Şeffaf Saldırı Raporları', 'd' => 'Her saldırının türünü, hacmini ve süresini panelde görün.']],
        ],
        'faqs' => [
            ['fa' => ['q' => 'آیا محافظت پایه رایگان دارید؟', 'a' => 'بله — همه سرویس‌های سرورنت (هاست، VPS، اختصاصی) محافظت L3/L4 پایه را رایگان دارند. این پلن‌ها برای حملات بزرگ‌تر و محافظت لایه ۷ (اپلیکیشن) هستند.'],
             'en' => ['q' => 'Is there free basic protection?', 'a' => 'Yes — every ServerNet service (hosting, VPS, dedicated) includes free basic L3/L4 protection. These plans cover larger attacks and Layer-7 (application) defense.'],
             'tr' => ['q' => 'Ücretsiz temel koruma var mı?', 'a' => 'Evet — tüm ServerNet hizmetleri ücretsiz temel L3/L4 koruması içerir. Bu planlar daha büyük saldırılar ve L7 içindir.']],
            ['fa' => ['q' => 'در حین حمله چه اتفاقی می‌افتد؟', 'a' => 'ترافیک به‌صورت خودکار از مراکز پالایش عبور می‌کند؛ کاربران واقعی هیچ چیزی حس نمی‌کنند. در پلن Pro تیم ما حین حمله به‌صورت زنده همراه شماست.'],
             'en' => ['q' => 'What happens during an attack?', 'a' => 'Traffic is automatically routed through scrubbing centers; real users notice nothing. On Pro, our team is live with you throughout the attack.'],
             'tr' => ['q' => 'Saldırı sırasında ne olur?', 'a' => 'Trafik otomatik olarak temizleme merkezlerinden geçer; gerçek kullanıcılar hiçbir şey fark etmez.']],
            'activation', 'refund',
        ],
    ],

    'block-storage' => [
        'icon' => 'hdd', 'group' => 'storage',
        'fa' => ['t' => 'بلاک‌استوریج', 'tag' => 'NVMe · اتصال آنی',
            'hero_t' => 'دیسک اضافه،', 'hero_g' => 'هر وقت که کم آوردید.',
            'hero_d' => 'والیوم‌های NVMe که در چند ثانیه به هر سرور ابری وصل می‌شوند — بزرگ کنید، اسنپ‌شات بگیرید، جابه‌جا کنید؛ بدون ری‌استارت.'],
        'en' => ['t' => 'Block Storage', 'tag' => 'NVMe · Instant attach',
            'hero_t' => 'Extra disks,', 'hero_g' => 'whenever you run out.',
            'hero_d' => 'NVMe volumes that attach to any cloud server in seconds — grow them, snapshot them, move them; no restarts.'],
        'tr' => ['t' => 'Block Storage', 'tag' => 'NVMe · Anında bağlama',
            'hero_t' => 'Yer bittiğinde', 'hero_g' => 'ekstra diskler.',
            'hero_d' => 'Saniyeler içinde her bulut sunucusuna bağlanan NVMe birimler — büyütün, snapshot alın, taşıyın.'],
        'chips' => ['NVMe-Backed', 'Attach in Seconds', 'Live Resize', 'Snapshots', '3× Replication'],
        'plans' => [
            $mk('VOL-100', 190, 190000, 1.90, ['100 GB NVMe Volume', ['fa' => 'اتصال آنی به هر سرور', 'en' => 'Instant attach to any server', 'tr' => 'Her sunucuya anında bağlama'], ['fa' => 'رشد آنلاین بدون ری‌استارت', 'en' => 'Live resize, no restart', 'tr' => 'Canlı boyutlandırma'], ['fa' => 'اسنپ‌شات دستی و زمان‌بندی', 'en' => 'Manual & scheduled snapshots', 'tr' => 'Manuel ve zamanlanmış snapshot'], ['fa' => 'تکرار ۳ نسخه‌ای', 'en' => '3× replication', 'tr' => '3× çoğaltma']]),
            $mk('VOL-500', 191, 790000, 7.90, ['500 GB NVMe Volume', ['fa' => 'اتصال آنی به هر سرور', 'en' => 'Instant attach to any server', 'tr' => 'Her sunucuya anında bağlama'], ['fa' => 'رشد آنلاین بدون ری‌استارت', 'en' => 'Live resize, no restart', 'tr' => 'Canlı boyutlandırma'], ['fa' => 'اسنپ‌شات دستی و زمان‌بندی', 'en' => 'Manual & scheduled snapshots', 'tr' => 'Manuel ve zamanlanmış snapshot'], ['fa' => 'تکرار ۳ نسخه‌ای', 'en' => '3× replication', 'tr' => '3× çoğaltma']], true),
            $mk('VOL-1T', 192, 1390000, 13.90, ['1 TB NVMe Volume', ['fa' => 'اتصال آنی به هر سرور', 'en' => 'Instant attach to any server', 'tr' => 'Her sunucuya anında bağlama'], ['fa' => 'رشد آنلاین بدون ری‌استارت', 'en' => 'Live resize, no restart', 'tr' => 'Canlı boyutlandırma'], ['fa' => 'اسنپ‌شات دستی و زمان‌بندی', 'en' => 'Manual & scheduled snapshots', 'tr' => 'Manuel ve zamanlanmış snapshot'], ['fa' => 'IOPS تضمینی', 'en' => 'Guaranteed IOPS', 'tr' => 'Garantili IOPS']]),
        ],
        'features' => ['scale', 'instant', 'backup', 'uptime', 'support'],
        'faqs' => ['activation', 'upgrade',
            ['fa' => ['q' => 'اگر سرورم حذف شود دیسک چه می‌شود؟', 'a' => 'والیوم مستقل از سرور است — سرور را حذف کنید، دیسک و داده‌ها می‌مانند و می‌توانید به سرور جدید وصلشان کنید.'],
             'en' => ['q' => 'What happens to the volume if I delete my server?', 'a' => 'Volumes live independently — delete the server and the disk with all data remains, ready to attach to a new server.'],
             'tr' => ['q' => 'Sunucumu silersem birim ne olur?', 'a' => 'Birimler bağımsızdır — sunucuyu silin, disk ve veriler kalır, yeni sunucuya bağlanabilir.']],
            'refund',
        ],
    ],

    'object-storage' => [
        'icon' => 'db', 'group' => 'storage',
        'fa' => ['t' => 'آبجکت‌استوریج', 'tag' => 'S3-Compatible · CDN آماده',
            'hero_t' => 'فضای S3،', 'hero_g' => 'بدون تحریم و بدون مرز.',
            'hero_d' => 'استوریج سازگار با S3 برای فایل، بکاپ و رسانه — با همان SDKها و ابزارهای آمازون کار می‌کند؛ داخل ایران یا اروپا، انتخاب با شماست.'],
        'en' => ['t' => 'Object Storage', 'tag' => 'S3-compatible · CDN-ready',
            'hero_t' => 'S3 storage,', 'hero_g' => 'without borders.',
            'hero_d' => 'S3-compatible storage for files, backups and media — works with every AWS SDK and tool; hosted in Iran or Europe, your choice.'],
        'tr' => ['t' => 'Object Storage', 'tag' => 'S3 uyumlu · CDN hazır',
            'hero_t' => 'Sınırsız', 'hero_g' => 'S3 depolama.',
            'hero_d' => 'Dosya, yedek ve medya için S3 uyumlu depolama — tüm AWS SDK\'larıyla çalışır.'],
        'chips' => ['S3 API', 'Presigned URLs', 'Versioning', 'Lifecycle Rules', 'CDN Integration'],
        'plans' => [
            $mk('OBJ-100', 193, 149000, 1.49, ['100 GB Storage', ['fa' => 'ترافیک خروجی ۲۰۰ گیگ', 'en' => '200 GB egress included', 'tr' => '200 GB çıkış dahil'], 'S3 API + Versioning', ['fa' => 'باکت نامحدود', 'en' => 'Unlimited buckets', 'tr' => 'Sınırsız bucket'], ['fa' => 'ایران یا اروپا', 'en' => 'Iran or Europe', 'tr' => 'İran veya Avrupa']]),
            $mk('OBJ-1T', 194, 990000, 9.90, ['1 TB Storage', ['fa' => 'ترافیک خروجی ۲ ترابایت', 'en' => '2 TB egress included', 'tr' => '2 TB çıkış dahil'], 'S3 API + Lifecycle', ['fa' => 'باکت نامحدود', 'en' => 'Unlimited buckets', 'tr' => 'Sınırsız bucket'], ['fa' => 'اتصال مستقیم CDN', 'en' => 'Direct CDN integration', 'tr' => 'Doğrudan CDN entegrasyonu']], true),
            $mk('OBJ-10T', 195, 8900000, 89.00, ['10 TB Storage', ['fa' => 'ترافیک خروجی ۲۰ ترابایت', 'en' => '20 TB egress included', 'tr' => '20 TB çıkış dahil'], 'S3 API + Replication', ['fa' => 'تکرار بین دو لوکیشن', 'en' => 'Cross-region replication', 'tr' => 'Bölgeler arası çoğaltma'], ['fa' => 'پشتیبانی اولویت‌دار', 'en' => 'Priority support', 'tr' => 'Öncelikli destek']]),
        ],
        'features' => ['scale', 'uptime', 'instant', 'support', 'net10'],
        'faqs' => ['activation',
            ['fa' => ['q' => 'با کدام ابزارها سازگار است؟', 'a' => 'هر ابزاری که S3 بفهمد: AWS CLI و SDKها، rclone، s3cmd، MinIO Client، افزونه‌های بکاپ وردپرس و لاراول Flysystem — فقط endpoint را عوض کنید.'],
             'en' => ['q' => 'Which tools does it work with?', 'a' => 'Anything that speaks S3: AWS CLI and SDKs, rclone, s3cmd, MinIO Client, WordPress backup plugins and Laravel Flysystem — just change the endpoint.'],
             'tr' => ['q' => 'Hangi araçlarla çalışır?', 'a' => 'S3 konuşan her şeyle: AWS CLI ve SDK\'lar, rclone, s3cmd, MinIO Client — sadece endpoint\'i değiştirin.']],
            'upgrade', 'refund',
        ],
    ],

    'gpu-platform' => [
        'icon' => 'sparkles', 'group' => 'ai',
        'fa' => ['t' => 'پلتفرم پردازش گرافیکی', 'tag' => 'Jupyter · Inference · Fine-tune',
            'hero_t' => 'از نوت‌بوک تا پروداکشن،', 'hero_g' => 'روی یک پلتفرم.',
            'hero_d' => 'محیط آماده Jupyter با GPU، اجرای مدل به‌صورت Endpoint و فاین‌تیون با یک کلیک — پلتفرم AI برای تیم‌هایی که نمی‌خواهند درگیر زیرساخت شوند.'],
        'en' => ['t' => 'GPU Platform', 'tag' => 'Jupyter · Inference · Fine-tune',
            'hero_t' => 'From notebook to production,', 'hero_g' => 'on one platform.',
            'hero_d' => 'Ready Jupyter environments with GPUs, model serving as endpoints and one-click fine-tuning — the AI platform for teams that refuse to babysit infrastructure.'],
        'tr' => ['t' => 'GPU Platformu', 'tag' => 'Jupyter · Inference · Fine-tune',
            'hero_t' => 'Notebook\'tan üretime,', 'hero_g' => 'tek platformda.',
            'hero_d' => 'GPU\'lu hazır Jupyter ortamları, endpoint olarak model sunumu ve tek tıkla fine-tuning.'],
        'chips' => ['JupyterLab', 'Model Endpoints', 'Fine-Tuning', 'vLLM / TGI', 'Usage Metering'],
        'plans' => [
            $mk('ML-DEV', 196, 2900000, 29.00, [['fa' => 'Jupyter با GPU اشتراکی', 'en' => 'Jupyter with shared GPU', 'tr' => 'Paylaşımlı GPU\'lu Jupyter'], '50 GB Workspace', ['fa' => '۵۰ ساعت GPU در ماه', 'en' => '50 GPU-hours / mo', 'tr' => 'Ayda 50 GPU saati'], ['fa' => 'دیتاست تا ۱۰۰ گیگ', 'en' => 'Datasets up to 100 GB', 'tr' => '100 GB\'a kadar veri seti'], ['fa' => 'قالب‌های آماده ML', 'en' => 'Ready ML templates', 'tr' => 'Hazır ML şablonları']]),
            $mk('ML-A100', 197, 9900000, 99.00, ['A100 40 GB Dedicated', '200 GB Workspace', ['fa' => 'Endpoint مدل بی‌نهایت', 'en' => 'Unlimited model endpoints', 'tr' => 'Sınırsız model endpoint'], ['fa' => 'فاین‌تیون یک‌کلیکی', 'en' => 'One-click fine-tuning', 'tr' => 'Tek tıkla fine-tuning'], ['fa' => 'مانیتورینگ مصرف', 'en' => 'Usage monitoring', 'tr' => 'Kullanım izleme']], true),
            array_merge($mk('ML-CLUSTER', 198, 0, 0, [['fa' => 'کلاستر چند-GPU (H100)', 'en' => 'Multi-GPU cluster (H100)', 'tr' => 'Çoklu GPU kümesi (H100)'], ['fa' => 'آموزش توزیع‌شده', 'en' => 'Distributed training', 'tr' => 'Dağıtık eğitim'], ['fa' => 'استوریج پرسرعت مشترک', 'en' => 'Shared high-speed storage', 'tr' => 'Paylaşımlı hızlı depolama'], ['fa' => 'مهندس ML اختصاصی', 'en' => 'Dedicated ML engineer', 'tr' => 'Özel ML mühendisi']]), ['contact' => true]),
        ],
        'features' => ['instant', 'scale', 'support', 'uptime',
            ['icon' => 'bot',
                'fa' => ['t' => 'مدل‌های آماده فارسی', 'd' => 'مدل‌های زبانی بهینه‌شده برای فارسی از پیش بارگذاری شده‌اند — چت‌بات و RAG فارسی را همان روز اول بالا بیاورید.'],
                'en' => ['t' => 'Pre-Loaded Persian Models', 'd' => 'Persian-optimized language models come pre-loaded — ship a Persian chatbot or RAG on day one.'],
                'tr' => ['t' => 'Önceden Yüklü Farsça Modeller', 'd' => 'Farsça için optimize dil modelleri hazır yüklü.']],
        ],
        'faqs' => ['activation',
            ['fa' => ['q' => 'داده‌های من برای آموزش استفاده می‌شود؟', 'a' => 'هرگز — دیتاست‌ها و مدل‌های شما کاملاً خصوصی‌اند، رمزنگاری می‌شوند و هیچ استفاده‌ای جز اجرای کارهای خودتان ندارند.'],
             'en' => ['q' => 'Is my data used for training?', 'a' => 'Never — your datasets and models are fully private, encrypted, and used for nothing but your own jobs.'],
             'tr' => ['q' => 'Verilerim eğitim için kullanılıyor mu?', 'a' => 'Asla — veri setleriniz ve modelleriniz tamamen özeldir ve şifrelenir.']],
            'upgrade', 'refund',
        ],
    ],

    'ai-infrastructure' => [
        'icon' => 'bot', 'group' => 'ai',
        'fa' => ['t' => 'زیرساخت هوش مصنوعی', 'tag' => 'Private LLM · سازمانی',
            'hero_t' => 'هوش مصنوعی سازمانی،', 'hero_g' => 'روی زیرساخت خودتان.',
            'hero_d' => 'LLM خصوصی، RAG روی اسناد سازمان و ایجنت‌های سفارشی — داده‌ها هرگز از زیرساخت شما خارج نمی‌شوند. طراحی، پیاده‌سازی و نگهداری با سرورنت.'],
        'en' => ['t' => 'AI Infrastructure', 'tag' => 'Private LLM · Enterprise',
            'hero_t' => 'Enterprise AI,', 'hero_g' => 'on your own infrastructure.',
            'hero_d' => 'Private LLMs, RAG over your documents and custom agents — data never leaves your infrastructure. Designed, built and maintained by ServerNet.'],
        'tr' => ['t' => 'AI Altyapısı', 'tag' => 'Özel LLM · Kurumsal',
            'hero_t' => 'Kurumsal yapay zeka,', 'hero_g' => 'kendi altyapınızda.',
            'hero_d' => 'Özel LLM\'ler, belgeleriniz üzerinde RAG ve özel ajanlar — veriler altyapınızdan asla çıkmaz.'],
        'chips' => ['On-Prem / Private Cloud', 'RAG Pipelines', 'Custom Agents', 'Data Sovereignty', 'SLA-Backed'],
        'plans' => [
            $mk('AI-START', 199, 19900000, 199.00, [['fa' => 'LLM خصوصی تک‌سرور (GPU)', 'en' => 'Single-server private LLM (GPU)', 'tr' => 'Tek sunucu özel LLM (GPU)'], ['fa' => 'RAG تا ۱۰۰ هزار سند', 'en' => 'RAG up to 100k documents', 'tr' => '100 bin belgeye kadar RAG'], ['fa' => 'چت‌بات داخلی سازمان', 'en' => 'Internal company chatbot', 'tr' => 'Kurum içi chatbot'], ['fa' => 'آموزش تیم شما', 'en' => 'Team training included', 'tr' => 'Ekip eğitimi dahil'], ['fa' => 'نگهداری ماهانه', 'en' => 'Monthly maintenance', 'tr' => 'Aylık bakım']]),
            $mk('AI-SCALE', 200, 49900000, 499.00, [['fa' => 'کلاستر GPU با HA', 'en' => 'HA GPU cluster', 'tr' => 'HA GPU kümesi'], ['fa' => 'RAG نامحدود + چند ایجنت', 'en' => 'Unlimited RAG + multiple agents', 'tr' => 'Sınırsız RAG + çoklu ajan'], ['fa' => 'اتصال به ERP و اتوماسیون', 'en' => 'ERP & automation integration', 'tr' => 'ERP ve otomasyon entegrasyonu'], ['fa' => 'داشبورد مدیریتی', 'en' => 'Management dashboard', 'tr' => 'Yönetim panosu'], ['fa' => 'SLA + مهندس اختصاصی', 'en' => 'SLA + dedicated engineer', 'tr' => 'SLA + özel mühendis']], true),
            array_merge($mk('AI-ENT', 201, 0, 0, [['fa' => 'طراحی کاملاً سفارشی', 'en' => 'Fully custom design', 'tr' => 'Tamamen özel tasarım'], ['fa' => 'On-Prem در دیتاسنتر شما', 'en' => 'On-prem in your datacenter', 'tr' => 'Kendi veri merkezinizde'], ['fa' => 'فاین‌تیون مدل اختصاصی', 'en' => 'Custom model fine-tuning', 'tr' => 'Özel model fine-tuning'], ['fa' => 'تیم پروژه اختصاصی', 'en' => 'Dedicated project team', 'tr' => 'Özel proje ekibi']]), ['contact' => true]),
        ],
        'features' => ['support', 'uptime', 'ddos',
            ['icon' => 'lock',
                'fa' => ['t' => 'حاکمیت کامل داده', 'd' => 'مدل و داده روی سرورهای شما (یا ابر خصوصی ما در ایران) اجرا می‌شود — هیچ بایتی به سرویس‌های خارجی نمی‌رود.'],
                'en' => ['t' => 'Full Data Sovereignty', 'd' => 'Models and data run on your servers (or our private cloud in Iran) — not a single byte goes to foreign services.'],
                'tr' => ['t' => 'Tam Veri Egemenliği', 'd' => 'Model ve veri sizin sunucularınızda çalışır — tek bayt bile dış servislere gitmez.']],
            ['icon' => 'flow',
                'fa' => ['t' => 'از BPMN تا ایجنت', 'd' => 'فرایندهای سازمان را تحلیل می‌کنیم و همان‌ها را به ایجنت‌های هوشمند تبدیل می‌کنیم — تجربه ما در ERP و BPMN پشتوانه پروژه شماست.'],
                'en' => ['t' => 'From BPMN to Agents', 'd' => 'We analyze your business processes and turn them into intelligent agents — backed by our ERP and BPMN practice.'],
                'tr' => ['t' => 'BPMN\'den Ajanlara', 'd' => 'İş süreçlerinizi analiz eder ve akıllı ajanlara dönüştürürüz.']],
        ],
        'faqs' => [
            ['fa' => ['q' => 'پروژه از کجا شروع می‌شود؟', 'a' => 'با یک جلسه مشاوره رایگان: نیاز و داده‌های شما را بررسی می‌کنیم، PoC دو هفته‌ای تعریف می‌کنیم و بعد از تایید شما وارد پیاده‌سازی کامل می‌شویم.'],
             'en' => ['q' => 'Where does the project start?', 'a' => 'With a free consultation: we review your needs and data, define a two-week PoC, and move to full implementation after your sign-off.'],
             'tr' => ['q' => 'Proje nereden başlıyor?', 'a' => 'Ücretsiz bir danışmanlıkla: ihtiyaç ve verilerinizi inceler, iki haftalık PoC tanımlar, onayınızla tam uygulamaya geçeriz.']],
            ['fa' => ['q' => 'کدام مدل‌ها را پشتیبانی می‌کنید؟', 'a' => 'مدل‌های متن‌باز (Llama، Qwen، Mistral و مدل‌های فارسی) روی زیرساخت خصوصی؛ در صورت نیاز اتصال امن به APIهای تجاری هم طراحی می‌شود.'],
             'en' => ['q' => 'Which models do you support?', 'a' => 'Open-source models (Llama, Qwen, Mistral and Persian models) on private infrastructure; secure connections to commercial APIs can be designed when needed.'],
             'tr' => ['q' => 'Hangi modelleri destekliyorsunuz?', 'a' => 'Açık kaynak modeller (Llama, Qwen, Mistral) özel altyapıda; gerekirse ticari API\'lere güvenli bağlantı da tasarlanır.']],
            'manage',
        ],
    ],

    'n8n' => [
        'icon' => 'flow', 'group' => 'apps',
        'fa' => ['t' => 'پلتفرم اتوماسیون n8n', 'tag' => 'Managed n8n · آماده در ۶۰ ثانیه',
            'hero_t' => 'اتوماسیون n8n،', 'hero_g' => 'بدون دغدغه سرور.',
            'hero_d' => 'n8n اختصاصی شما با دامنه دلخواه، SSL، بکاپ و آپدیت خودکار — ورک‌فلوهایتان را بسازید؛ نگهداری زیرساخت کار ماست.'],
        'en' => ['t' => 'n8n Automation', 'tag' => 'Managed n8n · Ready in 60s',
            'hero_t' => 'n8n automation,', 'hero_g' => 'minus the server chores.',
            'hero_d' => 'Your dedicated n8n with custom domain, SSL, backups and auto-updates — you build workflows; we keep the infrastructure alive.'],
        'tr' => ['t' => 'n8n Otomasyon', 'tag' => 'Yönetilen n8n · 60 saniyede hazır',
            'hero_t' => 'n8n otomasyonu,', 'hero_g' => 'sunucu derdi olmadan.',
            'hero_d' => 'Özel alan adı, SSL, yedek ve otomatik güncellemeyle size özel n8n — siz iş akışı kurun, altyapı bizde.'],
        'chips' => ['Dedicated Instance', 'Custom Domain + SSL', 'Auto Updates', 'Daily Backups', 'Webhook Ready'],
        'signature' => ['type' => 'term',
            'fa' => ['t' => 'وب‌هوک شما، زنده در ۶۰ ثانیه', 'd' => 'n8n اختصاصی + دامنه شما + SSL — بدون داکر، بدون کانفیگ'],
            'en' => ['t' => 'Your webhook, live in 60 seconds', 'd' => 'Dedicated n8n + your domain + SSL — no Docker, no config'],
            'tr' => ['t' => 'Webhook\'unuz 60 saniyede canlı', 'd' => 'Özel n8n + alan adınız + SSL'],
            'lines' => [
                ['p', '$ snet n8n create --name acme --domain flow.acme.ir'],
                ['ok', '✔ n8n 1.9x deployed → https://flow.acme.ir (SSL active)'],
                ['p', '$ curl -X POST https://flow.acme.ir/webhook/lead \\'],
                ['w', "    -d '{\"name\":\"Sara\",\"phone\":\"0912…\"}'"],
                ['ok', '{"ok":true,"workflow":"lead-capture","executed_in":"312ms"}'],
            ]],
        'plans' => [
            $mk('N8N-START', 202, 490000, 4.90, [['fa' => '۵ هزار اجرا در ماه', 'en' => '5k executions / mo', 'tr' => 'Ayda 5 bin çalıştırma'], '1 vCPU / 2 GB RAM', ['fa' => 'دامنه دلخواه + SSL', 'en' => 'Custom domain + SSL', 'tr' => 'Özel alan adı + SSL'], ['fa' => 'بکاپ روزانه', 'en' => 'Daily backups', 'tr' => 'Günlük yedek'], ['fa' => 'آپدیت خودکار', 'en' => 'Auto updates', 'tr' => 'Otomatik güncelleme']]),
            $mk('N8N-PRO', 203, 990000, 9.90, [['fa' => '۵۰ هزار اجرا در ماه', 'en' => '50k executions / mo', 'tr' => 'Ayda 50 bin çalıştırma'], '2 vCPU / 4 GB RAM', ['fa' => 'دامنه دلخواه + SSL', 'en' => 'Custom domain + SSL', 'tr' => 'Özel alan adı + SSL'], ['fa' => 'بکاپ ۶ ساعته', 'en' => '6-hour backups', 'tr' => '6 saatlik yedek'], ['fa' => 'دسترسی به کیو و ورکر', 'en' => 'Queue mode + worker', 'tr' => 'Kuyruk modu + worker']], true),
            $mk('N8N-BIZ', 204, 1990000, 19.90, [['fa' => 'اجرای نامحدود', 'en' => 'Unlimited executions', 'tr' => 'Sınırsız çalıştırma'], '4 vCPU / 8 GB RAM', ['fa' => 'ورکرهای اختصاصی جدا', 'en' => 'Dedicated separate workers', 'tr' => 'Özel ayrık worker\'lar'], ['fa' => 'SSO و کنترل دسترسی', 'en' => 'SSO & access control', 'tr' => 'SSO ve erişim kontrolü'], ['fa' => 'پشتیبانی ساخت ورک‌فلو', 'en' => 'Workflow-building support', 'tr' => 'İş akışı kurma desteği']]),
        ],
        'features' => ['instant', 'backup', 'ssl', 'uptime', 'support',
            ['icon' => 'bot',
                'fa' => ['t' => 'ورک‌فلوهای آماده فارسی', 'd' => 'قالب‌های آماده برای پیامک ایرانی، درگاه‌های پرداخت، دیجی‌کالا و CRMهای داخلی — از روز اول اتوماسیون واقعی داشته باشید.'],
                'en' => ['t' => 'Ready Local Workflow Templates', 'd' => 'Pre-built templates for local SMS, payment gateways and CRMs — real automation from day one.'],
                'tr' => ['t' => 'Hazır Yerel Şablonlar', 'd' => 'Yerel SMS, ödeme ağ geçitleri ve CRM\'ler için hazır şablonlar.']],
        ],
        'faqs' => ['activation', 'upgrade',
            ['fa' => ['q' => 'از نسخه self-hosted فعلی‌ام منتقل می‌شوید؟', 'a' => 'بله — ورک‌فلوها، کردنشیال‌ها و تاریخچه اجرا را رایگان و بدون قطعی منتقل می‌کنیم؛ فقط دسترسی n8n فعلی را بدهید.'],
             'en' => ['q' => 'Can you migrate my current self-hosted n8n?', 'a' => 'Yes — we migrate workflows, credentials and execution history free of charge with zero downtime; just share access to your current instance.'],
             'tr' => ['q' => 'Mevcut self-hosted n8n\'imi taşır mısınız?', 'a' => 'Evet — iş akışlarını, kimlik bilgilerini ve geçmişi ücretsiz ve kesintisiz taşırız.']],
            'refund',
        ],
    ],
];
