<?php

/*
|--------------------------------------------------------------------------
| کاتالوگ سرور اختصاصی — ۱۴ صفحه (fa / en / tr)
|--------------------------------------------------------------------------
| pid ها placeholder هستند. پلن‌های 'contact' قیمت ندارند و به فروش وصل می‌شوند.
*/

$traffic = ['fa' => 'ترافیک نامحدود', 'en' => 'Unlimited traffic', 'tr' => 'Sınırsız trafik'];
$ipmi = ['fa' => 'کنسول IPMI / KVM', 'en' => 'IPMI / KVM console', 'tr' => 'IPMI / KVM konsolu'];
$setup = ['fa' => 'راه‌اندازی رایگان', 'en' => 'Free setup', 'tr' => 'Ücretsiz kurulum'];

$mk = fn (string $name, int $pid, int $irt, float $eur, array $specs, bool $pop = false) =>
    array_filter(['name' => $name, 'pid' => $pid, 'irt' => $irt, 'eur' => $eur, 'specs' => $specs, 'popular' => $pop]);

$hwFaq = [
    'fa' => ['q' => 'سخت‌افزار دقیقاً اختصاصی خودم است؟', 'a' => 'بله — سرور اختصاصی یعنی کل سخت‌افزار فیزیکی (CPU، رم، دیسک و پورت شبکه) فقط در اختیار شماست؛ هیچ همسایه‌ای وجود ندارد و عملکرد همیشه قابل پیش‌بینی است.'],
    'en' => ['q' => 'Is the hardware truly dedicated to me?', 'a' => 'Yes — dedicated means the entire physical machine (CPU, RAM, disks and network port) is yours alone; no neighbors, always predictable performance.'],
    'tr' => ['q' => 'Donanım gerçekten bana mı özel?', 'a' => 'Evet — dedicated, tüm fiziksel makinenin (CPU, RAM, disk, ağ portu) yalnızca size ait olması demektir; komşu yok, performans daima öngörülebilir.'],
];

$deliveryFaq = [
    'fa' => ['q' => 'تحویل سرور اختصاصی چقدر طول می‌کشد؟', 'a' => 'کانفیگ‌های آماده معمولاً بین ۱ تا ۲۴ ساعت تحویل می‌شوند. کانفیگ‌های سفارشی بسته به قطعات، ۲ تا ۷ روز کاری زمان می‌برند.'],
    'en' => ['q' => 'How long does delivery take?', 'a' => 'Stock configurations are usually delivered within 1–24 hours. Custom builds take 2–7 business days depending on parts.'],
    'tr' => ['q' => 'Teslimat ne kadar sürer?', 'a' => 'Hazır yapılandırmalar genellikle 1–24 saat içinde teslim edilir. Özel yapılandırmalar parçalara bağlı olarak 2–7 iş günü sürer.'],
];

return [

    'iran' => [
        'icon' => 'server', 'group' => 'location',
        'fa' => ['t' => 'سرور اختصاصی ایران', 'tag' => 'دیتاسنتر تهران · Tier III',
            'hero_t' => 'سرور اختصاصی ایران،', 'hero_g' => 'قدرت بدون واسطه.',
            'hero_d' => 'سخت‌افزار کاملاً اختصاصی در دیتاسنتر Tier III تهران — پینگ داخلی ۱ میلی‌ثانیه، ترافیک داخلی نامحدود و دسترسی IPMI برای کنترل کامل.'],
        'en' => ['t' => 'Iran Dedicated', 'tag' => 'Tehran DC · Tier III',
            'hero_t' => 'Iran dedicated servers —', 'hero_g' => 'raw, unshared power.',
            'hero_d' => 'Fully dedicated hardware in a Tier III Tehran datacenter — 1 ms domestic ping, unlimited local traffic and IPMI access for total control.'],
        'tr' => ['t' => 'İran Fiziksel Sunucu', 'tag' => 'Tahran DC · Tier III',
            'hero_t' => 'İran dedicated —', 'hero_g' => 'paylaşımsız saf güç.',
            'hero_d' => 'Tier III Tahran veri merkezinde tamamen özel donanım — 1 ms yerel ping, sınırsız yurt içi trafik ve tam kontrol için IPMI.'],
        'chips' => ['Tehran Tier III', '10 Gbit Port', 'IPMI / KVM', 'RAID Hardware', '24h Delivery'],
        'plans' => [
            $mk('T-1236', 120, 4900000, 49.00, ['Xeon E-2236 · 6c/12t', '32 GB DDR4 ECC', '2 × 480 GB NVMe (RAID-1)', $traffic, $ipmi]),
            $mk('T-2388', 121, 7900000, 79.00, ['Xeon E-2388G · 8c/16t', '64 GB DDR4 ECC', '2 × 960 GB NVMe (RAID-1)', $traffic, $ipmi], true),
            $mk('T-4314', 122, 14900000, 149.00, ['2× Xeon Silver 4314 · 32c/64t', '128 GB DDR4 ECC', '2 × 1.92 TB NVMe (RAID-1)', $traffic, $ipmi]),
        ],
        'features' => ['root', 'net10', 'ddos', 'uptime', 'support',
            ['icon' => 'factory',
                'fa' => ['t' => 'پشتیبانی حضوری دیتاسنتر', 'd' => 'تیم فنی ما در خود دیتاسنتر تهران مستقر است — تعویض قطعه و مداخله دستی در کمترین زمان ممکن.'],
                'en' => ['t' => 'On-Site Datacenter Support', 'd' => 'Our engineers are stationed inside the Tehran datacenter — part swaps and manual intervention in record time.'],
                'tr' => ['t' => 'Yerinde Veri Merkezi Desteği', 'd' => 'Mühendislerimiz Tahran veri merkezinde konuşlu — parça değişimi ve manuel müdahale rekor sürede.']],
        ],
        'faqs' => [$hwFaq, $deliveryFaq, 'manage', 'os'],
    ],

    'germany' => [
        'icon' => 'server', 'group' => 'location',
        'fa' => ['t' => 'سرور اختصاصی آلمان', 'tag' => 'Hetzner · فالکن‌اشتاین',
            'hero_t' => 'سرور اختصاصی آلمان،', 'hero_g' => 'مهندسی آلمانی واقعی.',
            'hero_d' => 'سرورهای نسل جدید Ryzen و Xeon در دیتاسنترهای Hetzner آلمان — بهترین نسبت قدرت به قیمت اروپا با شبکه‌ای که هرگز خاموش نمی‌شود.'],
        'en' => ['t' => 'Germany Dedicated', 'tag' => 'Hetzner · Falkenstein',
            'hero_t' => 'Germany dedicated —', 'hero_g' => 'real German engineering.',
            'hero_d' => 'Latest-gen Ryzen and Xeon servers in Hetzner\'s German datacenters — Europe\'s best power-to-price ratio on a network that never sleeps.'],
        'tr' => ['t' => 'Almanya Fiziksel Sunucu', 'tag' => 'Hetzner · Falkenstein',
            'hero_t' => 'Almanya dedicated —', 'hero_g' => 'gerçek Alman mühendisliği.',
            'hero_d' => 'Hetzner\'in Almanya veri merkezlerinde yeni nesil Ryzen ve Xeon sunucular — Avrupa\'nın en iyi güç/fiyat oranı.'],
        'chips' => ['Hetzner DC', 'Ryzen / Xeon', 'ECC RAM', '1 Gbit Unlimited', 'IPMI'],
        'plans' => [
            $mk('AX-42', 123, 4900000, 49.00, ['Ryzen 7 7700 · 8c/16t', '64 GB DDR5 ECC', '2 × 512 GB NVMe Gen4', $traffic, $ipmi]),
            $mk('AX-52', 124, 6900000, 69.00, ['Ryzen 9 7950X · 16c/32t', '128 GB DDR5 ECC', '2 × 1 TB NVMe Gen4', $traffic, $ipmi], true),
            $mk('AX-102', 125, 8900000, 89.00, ['Ryzen 9 7950X3D · 16c/32t', '128 GB DDR5 ECC', '2 × 1.92 TB NVMe Gen4', $traffic, $ipmi]),
        ],
        'features' => ['root', 'net10', 'ddos', 'uptime', 'instant', 'support'],
        'faqs' => [$hwFaq, $deliveryFaq, 'os', 'manage'],
    ],

    'finland' => [
        'icon' => 'server', 'group' => 'location',
        'fa' => ['t' => 'سرور اختصاصی فنلاند', 'tag' => 'Hetzner · هلسینکی',
            'hero_t' => 'سرور اختصاصی فنلاند،', 'hero_g' => 'خنک، سبز، اقتصادی.',
            'hero_d' => 'همان سخت‌افزار آلمان در دیتاسنتر هلسینکی با خنک‌سازی طبیعی — چند درصد ارزان‌تر، به همان اندازه قدرتمند.'],
        'en' => ['t' => 'Finland Dedicated', 'tag' => 'Hetzner · Helsinki',
            'hero_t' => 'Finland dedicated —', 'hero_g' => 'cool, green, economical.',
            'hero_d' => 'The same hardware as Germany in Helsinki\'s naturally-cooled datacenter — a few percent cheaper, every bit as powerful.'],
        'tr' => ['t' => 'Finlandiya Fiziksel Sunucu', 'tag' => 'Hetzner · Helsinki',
            'hero_t' => 'Finlandiya dedicated —', 'hero_g' => 'serin, yeşil, ekonomik.',
            'hero_d' => 'Almanya ile aynı donanım, Helsinki\'nin doğal soğutmalı veri merkezinde — birkaç puan daha ucuz, aynı güçte.'],
        'chips' => ['Helsinki DC', 'Green Energy', 'Ryzen / Xeon', 'ECC RAM', 'IPMI'],
        'plans' => [
            $mk('FI-42', 126, 4500000, 45.00, ['Ryzen 7 7700 · 8c/16t', '64 GB DDR5 ECC', '2 × 512 GB NVMe Gen4', $traffic, $ipmi]),
            $mk('FI-52', 127, 6400000, 64.00, ['Ryzen 9 7950X · 16c/32t', '128 GB DDR5 ECC', '2 × 1 TB NVMe Gen4', $traffic, $ipmi], true),
            $mk('FI-102', 128, 8300000, 83.00, ['Ryzen 9 7950X3D · 16c/32t', '128 GB DDR5 ECC', '2 × 1.92 TB NVMe Gen4', $traffic, $ipmi]),
        ],
        'features' => ['root', 'net10', 'ddos', 'uptime', 'instant', 'support'],
        'faqs' => [$hwFaq, $deliveryFaq, 'os', 'manage'],
    ],

    'france' => [
        'icon' => 'server', 'group' => 'location',
        'fa' => ['t' => 'سرور اختصاصی فرانسه', 'tag' => 'OVH · گراولین',
            'hero_t' => 'سرور اختصاصی فرانسه،', 'hero_g' => 'با سپر ضد DDoS.',
            'hero_d' => 'سرورهای OVH با محافظت DDoS نامحدود پیش‌فرض — انتخاب اول پروژه‌هایی که هدف حمله‌اند: گیم‌سرور، صرافی و سرویس‌های عمومی.'],
        'en' => ['t' => 'France Dedicated', 'tag' => 'OVH · Gravelines',
            'hero_t' => 'France dedicated —', 'hero_g' => 'with a DDoS shield.',
            'hero_d' => 'OVH servers with unlimited default DDoS protection — first choice for attack-prone projects: game servers, exchanges, public services.'],
        'tr' => ['t' => 'Fransa Fiziksel Sunucu', 'tag' => 'OVH · Gravelines',
            'hero_t' => 'Fransa dedicated —', 'hero_g' => 'DDoS kalkanıyla.',
            'hero_d' => 'Sınırsız varsayılan DDoS korumalı OVH sunucuları — saldırıya açık projelerin ilk tercihi.'],
        'chips' => ['OVH DC', 'Unlimited Anti-DDoS', 'vRack Private Net', 'ECC RAM', 'IPMI'],
        'plans' => [
            $mk('RISE-1', 129, 4400000, 44.00, ['Xeon-E 2386G · 6c/12t', '32 GB DDR4 ECC', '2 × 512 GB NVMe', $traffic, $ipmi]),
            $mk('ADV-1', 130, 6900000, 69.00, ['Ryzen 9 5900X · 12c/24t', '64 GB DDR4 ECC', '2 × 960 GB NVMe', $traffic, $ipmi], true),
            $mk('SCALE-1', 131, 11900000, 119.00, ['EPYC 7313 · 16c/32t', '128 GB DDR4 ECC', '2 × 1.92 TB NVMe', $traffic, $ipmi]),
        ],
        'features' => ['root', 'ddos', 'net10', 'uptime', 'support', 'instant'],
        'faqs' => [$hwFaq, $deliveryFaq, 'os', 'manage'],
    ],

    'canada' => [
        'icon' => 'server', 'group' => 'location',
        'fa' => ['t' => 'سرور اختصاصی کانادا', 'tag' => 'OVH · بوهارنوآ',
            'hero_t' => 'سرور اختصاصی کانادا،', 'hero_g' => 'پل آمریکای شمالی.',
            'hero_d' => 'دیتاسنتر بوهارنوآ مونترال — پوشش هم‌زمان آمریکا و اروپا با قوانین حریم خصوصی کانادا و برق ارزان آبی-برقی.'],
        'en' => ['t' => 'Canada Dedicated', 'tag' => 'OVH · Beauharnois',
            'hero_t' => 'Canada dedicated —', 'hero_g' => 'the North American bridge.',
            'hero_d' => 'Montreal\'s Beauharnois datacenter — cover the US and Europe at once, with Canadian privacy law and cheap hydro power.'],
        'tr' => ['t' => 'Kanada Fiziksel Sunucu', 'tag' => 'OVH · Beauharnois',
            'hero_t' => 'Kanada dedicated —', 'hero_g' => 'Kuzey Amerika köprüsü.',
            'hero_d' => 'Montreal Beauharnois veri merkezi — ABD ve Avrupa\'yı aynı anda kapsayın.'],
        'chips' => ['OVH BHS', 'Unlimited Anti-DDoS', 'US + EU Coverage', 'ECC RAM', 'IPMI'],
        'plans' => [
            $mk('CA-RISE', 132, 4600000, 46.00, ['Xeon-E 2386G · 6c/12t', '32 GB DDR4 ECC', '2 × 512 GB NVMe', $traffic, $ipmi]),
            $mk('CA-ADV', 133, 7200000, 72.00, ['Ryzen 9 5900X · 12c/24t', '64 GB DDR4 ECC', '2 × 960 GB NVMe', $traffic, $ipmi], true),
            $mk('CA-SCALE', 134, 12500000, 125.00, ['EPYC 7313 · 16c/32t', '128 GB DDR4 ECC', '2 × 1.92 TB NVMe', $traffic, $ipmi]),
        ],
        'features' => ['root', 'ddos', 'net10', 'uptime', 'support', 'instant'],
        'faqs' => [$hwFaq, $deliveryFaq, 'os', 'manage'],
    ],

    'usa' => [
        'icon' => 'server', 'group' => 'location',
        'fa' => ['t' => 'سرور اختصاصی آمریکا', 'tag' => 'نیویورک · لس‌آنجلس',
            'hero_t' => 'سرور اختصاصی آمریکا،', 'hero_g' => 'در مرکز بازار جهانی.',
            'hero_d' => 'حضور فیزیکی در بزرگ‌ترین بازار اینترنت دنیا — IPهای تمیز آمریکایی، پهنای باند عظیم و اتصال مستقیم به تمام CDNهای بزرگ.'],
        'en' => ['t' => 'USA Dedicated', 'tag' => 'New York · Los Angeles',
            'hero_t' => 'USA dedicated —', 'hero_g' => 'at the center of the market.',
            'hero_d' => 'A physical presence in the world\'s biggest internet market — clean US IPs, massive bandwidth, direct peering with every major CDN.'],
        'tr' => ['t' => 'ABD Fiziksel Sunucu', 'tag' => 'New York · Los Angeles',
            'hero_t' => 'ABD dedicated —', 'hero_g' => 'pazarın merkezinde.',
            'hero_d' => 'Dünyanın en büyük internet pazarında fiziksel varlık — temiz ABD IP\'leri, dev bant genişliği.'],
        'chips' => ['NY + LA', 'Clean US IPs', '10 Gbit Port', 'ECC RAM', 'IPMI'],
        'plans' => [
            $mk('US-E', 135, 5400000, 54.00, ['Xeon E-2388G · 8c/16t', '64 GB DDR4 ECC', '2 × 960 GB NVMe', $traffic, $ipmi]),
            $mk('US-R', 136, 7900000, 79.00, ['Ryzen 9 7950X · 16c/32t', '128 GB DDR5 ECC', '2 × 1 TB NVMe Gen4', $traffic, $ipmi], true),
            $mk('US-EPYC', 137, 12900000, 129.00, ['EPYC 7443P · 24c/48t', '128 GB DDR4 ECC', '2 × 1.92 TB NVMe', $traffic, $ipmi]),
        ],
        'features' => ['root', 'net10', 'ddos', 'uptime', 'support', 'instant'],
        'faqs' => [$hwFaq, $deliveryFaq, 'os', 'manage'],
    ],

    'iran-infrastructure' => [
        'icon' => 'factory', 'group' => 'dc',
        'fa' => ['t' => 'زیرساخت ایران', 'tag' => 'کولوکیشن · رک اختصاصی',
            'hero_t' => 'سخت‌افزار شما،', 'hero_g' => 'خانه‌ای در کلاس جهانی.',
            'hero_d' => 'کولوکیشن در دیتاسنتر Tier III تهران — برق دوگانه، خنک‌سازی افزونه، اینترنت چنداپراتوره و دست‌های فنی ما در کنار سرورهای شما، ۲۴ ساعته.'],
        'en' => ['t' => 'Iran Infrastructure', 'tag' => 'Colocation · Private racks',
            'hero_t' => 'Your hardware,', 'hero_g' => 'a world-class home.',
            'hero_d' => 'Colocation in a Tier III Tehran datacenter — redundant power and cooling, multi-carrier connectivity and our hands next to your servers, 24/7.'],
        'tr' => ['t' => 'İran Altyapısı', 'tag' => 'Colocation · Özel kabinler',
            'hero_t' => 'Donanımınıza', 'hero_g' => 'dünya standartlarında bir ev.',
            'hero_d' => 'Tier III Tahran veri merkezinde colocation — yedekli güç ve soğutma, çok operatörlü bağlantı, 7/24 yerinde teknik el.'],
        'chips' => ['Tier III', 'N+1 Power & Cooling', 'Multi-Carrier', 'Remote Hands 24/7', 'CCTV + Biometric'],
        'plans' => [
            $mk('COLO-1U', 138, 2900000, 29.00, ['1U Rack Space', ['fa' => 'برق ۱۵۰ وات + پورت ۱ گیگ', 'en' => '150 W power + 1 Gbit port', 'tr' => '150 W güç + 1 Gbit port'], ['fa' => 'IP اختصاصی /30', 'en' => 'Dedicated /30 IP', 'tr' => 'Özel /30 IP'], ['fa' => 'دسترسی حضوری هماهنگ', 'en' => 'Scheduled physical access', 'tr' => 'Planlı fiziksel erişim'], $setup]),
            $mk('COLO-4U', 139, 8900000, 89.00, ['4U Rack Space', ['fa' => 'برق ۶۰۰ وات + پورت ۱۰ گیگ', 'en' => '600 W power + 10 Gbit port', 'tr' => '600 W güç + 10 Gbit port'], ['fa' => 'IP اختصاصی /29', 'en' => 'Dedicated /29 IP', 'tr' => 'Özel /29 IP'], ['fa' => 'Remote Hands رایگان', 'en' => 'Free remote hands', 'tr' => 'Ücretsiz remote hands'], $setup], true),
            array_merge($mk('RACK-42U', 140, 0, 0, ['42U Private Rack', ['fa' => 'برق و خنک‌سازی اختصاصی', 'en' => 'Dedicated power & cooling', 'tr' => 'Özel güç ve soğutma'], ['fa' => 'رنج IP اختصاصی', 'en' => 'Dedicated IP range', 'tr' => 'Özel IP aralığı'], ['fa' => 'قفل و دسترسی بیومتریک', 'en' => 'Biometric locked cage', 'tr' => 'Biyometrik kilitli kabin'], $setup]), ['contact' => true]),
        ],
        'features' => ['uptime', 'net10', 'support',
            ['icon' => 'shield',
                'fa' => ['t' => 'امنیت فیزیکی چندلایه', 'd' => 'دوربین مداربسته، دسترسی بیومتریک و ثبت کامل ورود و خروج — سخت‌افزار شما زیر نظارت دائم است.'],
                'en' => ['t' => 'Multi-Layer Physical Security', 'd' => 'CCTV, biometric access and full entry logging — your hardware is under constant watch.'],
                'tr' => ['t' => 'Çok Katmanlı Fiziksel Güvenlik', 'd' => 'CCTV, biyometrik erişim ve tam giriş kaydı.']],
            ['icon' => 'wrench',
                'fa' => ['t' => 'Remote Hands ۲۴/۷', 'd' => 'ری‌استارت، تعویض کابل یا دیسک — تیم مستقر ما به‌جای شما انجام می‌دهد، در هر ساعت شبانه‌روز.'],
                'en' => ['t' => '24/7 Remote Hands', 'd' => 'Reboots, cable or disk swaps — our on-site team does it for you, any hour of the day.'],
                'tr' => ['t' => '7/24 Remote Hands', 'd' => 'Yeniden başlatma, kablo veya disk değişimi — yerinde ekibimiz sizin yerinize yapar.']],
        ],
        'faqs' => [
            ['fa' => ['q' => 'چه تجهیزاتی می‌توانم بیاورم؟', 'a' => 'هر سرور استاندارد رک‌مونت (۱U تا ۴۲U کامل)، فایروال، سوییچ و استوریج. تیم ما در نصب و کابل‌کشی اولیه رایگان کمک می‌کند.'],
             'en' => ['q' => 'What equipment can I bring?', 'a' => 'Any standard rackmount gear (1U up to a full 42U), firewalls, switches and storage. Our team helps with initial racking and cabling for free.'],
             'tr' => ['q' => 'Hangi ekipmanı getirebilirim?', 'a' => 'Her standart rack donanımı (1U\'dan tam 42U\'ya), güvenlik duvarı, switch ve depolama. İlk kurulumda ücretsiz yardım ederiz.']],
            ['fa' => ['q' => 'اگر سرورم مشکل سخت‌افزاری پیدا کند؟', 'a' => 'با سرویس Remote Hands تیم مستقر ما طبق دستور شما قطعه را تعویض یا سیستم را عیب‌یابی می‌کند — بدون نیاز به حضور شما.'],
             'en' => ['q' => 'What if my server has a hardware failure?', 'a' => 'With Remote Hands, our on-site team swaps parts or troubleshoots per your instructions — no site visit needed.'],
             'tr' => ['q' => 'Sunucumda donanım arızası olursa?', 'a' => 'Remote Hands ile yerinde ekibimiz talimatınıza göre parça değiştirir veya sorun giderir — gelmenize gerek yok.']],
            'manage',
        ],
    ],

    'ovh' => [
        'icon' => 'server', 'group' => 'dc',
        'fa' => ['t' => 'سرورهای OVH', 'tag' => 'فرانسه · کانادا · نماینده رسمی',
            'hero_t' => 'قدرت OVH،', 'hero_g' => 'با پشتیبانی فارسی.',
            'hero_d' => 'بزرگ‌ترین ارائه‌دهنده اروپا با محافظت DDoS افسانه‌ای — سفارش، پرداخت ریالی و پشتیبانی فارسی از ما، زیرساخت از OVH.'],
        'en' => ['t' => 'OVH Servers', 'tag' => 'France · Canada · Official partner',
            'hero_t' => 'OVH power,', 'hero_g' => 'with local support.',
            'hero_d' => 'Europe\'s largest provider with legendary DDoS protection — ordering, local payment and support from us, infrastructure from OVH.'],
        'tr' => ['t' => 'OVH Sunucuları', 'tag' => 'Fransa · Kanada · Resmi iş ortağı',
            'hero_t' => 'OVH gücü,', 'hero_g' => 'yerel destekle.',
            'hero_d' => 'Efsanevi DDoS korumasıyla Avrupa\'nın en büyük sağlayıcısı — sipariş, yerel ödeme ve destek bizden, altyapı OVH\'den.'],
        'chips' => ['Official Partner', 'Unlimited Anti-DDoS', 'vRack', 'FR + CA', 'Local Billing'],
        'plans' => [
            $mk('OVH-RISE', 141, 4400000, 44.00, ['Xeon-E 2386G · 6c/12t', '32 GB DDR4 ECC', '2 × 512 GB NVMe', ['fa' => 'فرانسه یا کانادا', 'en' => 'France or Canada', 'tr' => 'Fransa veya Kanada'], $traffic]),
            $mk('OVH-ADV', 142, 6900000, 69.00, ['Ryzen 9 5900X · 12c/24t', '64 GB DDR4 ECC', '2 × 960 GB NVMe', ['fa' => 'فرانسه یا کانادا', 'en' => 'France or Canada', 'tr' => 'Fransa veya Kanada'], $traffic], true),
            $mk('OVH-SCALE', 143, 11900000, 119.00, ['EPYC 7313 · 16c/32t', '128 GB DDR4 ECC', '2 × 1.92 TB NVMe', ['fa' => 'فرانسه یا کانادا', 'en' => 'France or Canada', 'tr' => 'Fransa veya Kanada'], $traffic]),
        ],
        'features' => ['ddos', 'root', 'net10', 'uptime', 'support', 'instant'],
        'faqs' => [
            ['fa' => ['q' => 'چرا از شما بخرم و مستقیم از OVH نخرم؟', 'a' => 'پرداخت ریالی بدون نیاز به کارت بین‌المللی، پشتیبانی فارسی ۲۴ ساعته، مدیریت تحریم‌ها و تجربه ما در کانفیگ بهینه — با همان قیمت و اغلب تحویل سریع‌تر.'],
             'en' => ['q' => 'Why buy through you instead of OVH directly?', 'a' => 'Local payment without international cards, 24/7 support in your language, sanctions handling and our configuration expertise — at the same price, often with faster delivery.'],
             'tr' => ['q' => 'Neden doğrudan OVH yerine sizden alayım?', 'a' => 'Yerel ödeme, kendi dilinizde 7/24 destek ve yapılandırma uzmanlığımız — aynı fiyata, çoğu zaman daha hızlı teslimatla.']],
            $hwFaq, $deliveryFaq, 'manage',
        ],
    ],

    'hetzner' => [
        'icon' => 'server', 'group' => 'dc',
        'fa' => ['t' => 'سرورهای Hetzner', 'tag' => 'آلمان · فنلاند · نماینده رسمی',
            'hero_t' => 'Hetzner واقعی،', 'hero_g' => 'با پرداخت ریالی.',
            'hero_d' => 'محبوب‌ترین دیتاسنتر اروپا میان توسعه‌دهنده‌ها — سرورهای AX و EX با پرداخت ریالی، فعال‌سازی سریع و پشتیبانی فارسی سرورنت.'],
        'en' => ['t' => 'Hetzner Servers', 'tag' => 'Germany · Finland · Official partner',
            'hero_t' => 'Real Hetzner,', 'hero_g' => 'with local billing.',
            'hero_d' => 'Europe\'s favorite datacenter among developers — AX and EX servers with local payment, fast activation and ServerNet support.'],
        'tr' => ['t' => 'Hetzner Sunucuları', 'tag' => 'Almanya · Finlandiya · Resmi iş ortağı',
            'hero_t' => 'Gerçek Hetzner,', 'hero_g' => 'yerel faturalandırmayla.',
            'hero_d' => 'Geliştiricilerin en sevdiği Avrupa veri merkezi — yerel ödeme ve ServerNet desteğiyle AX ve EX sunucular.'],
        'chips' => ['Official Partner', 'AX / EX Series', 'DDR5 ECC', 'DE + FI', 'Local Billing'],
        'plans' => [
            $mk('HZ-AX42', 144, 4900000, 49.00, ['Ryzen 7 7700 · 8c/16t', '64 GB DDR5 ECC', '2 × 512 GB NVMe Gen4', ['fa' => 'آلمان یا فنلاند', 'en' => 'Germany or Finland', 'tr' => 'Almanya veya Finlandiya'], $traffic]),
            $mk('HZ-AX52', 145, 6900000, 69.00, ['Ryzen 9 7950X · 16c/32t', '128 GB DDR5 ECC', '2 × 1 TB NVMe Gen4', ['fa' => 'آلمان یا فنلاند', 'en' => 'Germany or Finland', 'tr' => 'Almanya veya Finlandiya'], $traffic], true),
            $mk('HZ-EX130', 146, 12900000, 129.00, ['Xeon Gold 5412U · 24c/48t', '256 GB DDR5 ECC', '2 × 1.92 TB NVMe', ['fa' => 'آلمان یا فنلاند', 'en' => 'Germany or Finland', 'tr' => 'Almanya veya Finlandiya'], $traffic]),
        ],
        'features' => ['root', 'net10', 'uptime', 'instant', 'support', 'ddos'],
        'faqs' => [
            ['fa' => ['q' => 'سرور واقعاً در Hetzner است؟', 'a' => 'بله — سرور فیزیکی در دیتاسنتر رسمی Hetzner (فالکن‌اشتاین یا هلسینکی) تحویل می‌شود و پنل Robot/Cloud خود Hetzner را هم در اختیار دارید.'],
             'en' => ['q' => 'Is the server really at Hetzner?', 'a' => 'Yes — a physical server in an official Hetzner datacenter (Falkenstein or Helsinki), and you get access to Hetzner\'s own Robot/Cloud panel too.'],
             'tr' => ['q' => 'Sunucu gerçekten Hetzner\'de mi?', 'a' => 'Evet — resmi Hetzner veri merkezinde fiziksel sunucu, ayrıca Hetzner\'in kendi Robot/Cloud paneline de erişirsiniz.']],
            $hwFaq, $deliveryFaq, 'manage',
        ],
    ],

    'cloud' => [
        'icon' => 'cloud', 'group' => 'more',
        'fa' => ['t' => 'سرور اختصاصی ابری', 'tag' => 'Bare-Metal Cloud · تحویل ۲ ساعته',
            'hero_t' => 'سخت‌افزار اختصاصی،', 'hero_g' => 'با چابکی ابر.',
            'hero_d' => 'سرور فیزیکی کامل که مثل سرور ابری در چند دقیقه آماده و ساعتی پرداخت می‌شود — قدرت Bare-Metal بدون قرارداد بلندمدت.'],
        'en' => ['t' => 'Cloud Dedicated', 'tag' => 'Bare-Metal Cloud · 2-hour delivery',
            'hero_t' => 'Dedicated hardware,', 'hero_g' => 'with cloud agility.',
            'hero_d' => 'A full physical server provisioned in minutes and billed hourly like cloud — bare-metal power without a long-term contract.'],
        'tr' => ['t' => 'Bulut Dedicated', 'tag' => 'Bare-Metal Cloud · 2 saatte teslim',
            'hero_t' => 'Özel donanım,', 'hero_g' => 'bulut çevikliğiyle.',
            'hero_d' => 'Dakikalar içinde hazırlanan ve bulut gibi saatlik faturalanan tam fiziksel sunucu.'],
        'chips' => ['Hourly Billing', 'API Provisioning', '2h Delivery', 'NVMe Gen4', 'No Contract'],
        'plans' => [
            $mk('BM-S', 147, 6900000, 69.00, ['Ryzen 7 7700 · 8c/16t', '64 GB DDR5 ECC', '2 × 512 GB NVMe Gen4', ['fa' => 'پرداخت ساعتی', 'en' => 'Hourly billing', 'tr' => 'Saatlik ödeme'], $traffic]),
            $mk('BM-M', 148, 9900000, 99.00, ['Ryzen 9 7950X · 16c/32t', '128 GB DDR5 ECC', '2 × 1 TB NVMe Gen4', ['fa' => 'پرداخت ساعتی', 'en' => 'Hourly billing', 'tr' => 'Saatlik ödeme'], $traffic], true),
            array_merge($mk('BM-XL', 149, 0, 0, ['EPYC · up to 96 cores', 'up to 1 TB ECC RAM', 'Custom NVMe array', ['fa' => 'پرداخت ساعتی', 'en' => 'Hourly billing', 'tr' => 'Saatlik ödeme'], $traffic]), ['contact' => true]),
        ],
        'features' => ['hourly', 'instant', 'root', 'scale', 'net10', 'support'],
        'faqs' => ['activation', $hwFaq, 'os', 'refund'],
    ],

    'custom' => [
        'icon' => 'wrench', 'group' => 'more',
        'fa' => ['t' => 'سرور اختصاصی سفارشی', 'tag' => 'Custom Build · مشاوره رایگان',
            'hero_t' => 'دقیقاً همان سروری', 'hero_g' => 'که در ذهن دارید.',
            'hero_d' => 'CPU، رم، آرایه دیسک، GPU و کارت شبکه را شما انتخاب می‌کنید؛ ما می‌سازیم، تست می‌کنیم و در دیتاسنتر دلخواهتان تحویل می‌دهیم.'],
        'en' => ['t' => 'Custom Dedicated', 'tag' => 'Custom build · Free consultation',
            'hero_t' => 'Exactly the server', 'hero_g' => 'you have in mind.',
            'hero_d' => 'You pick the CPU, RAM, disk array, GPU and NICs; we build, burn-test and deliver it in the datacenter of your choice.'],
        'tr' => ['t' => 'Özel Yapılandırma', 'tag' => 'Custom build · Ücretsiz danışmanlık',
            'hero_t' => 'Aklınızdaki sunucunun', 'hero_g' => 'tam kendisi.',
            'hero_d' => 'CPU, RAM, disk dizisi, GPU ve ağ kartlarını siz seçin; biz kurup test edelim ve istediğiniz veri merkezinde teslim edelim.'],
        'chips' => ['Any CPU / GPU', 'Custom RAID', 'Burn-In Tested', 'IR / EU / US', 'Free Consultation'],
        'plans' => [
            $mk('CUS-BASE', 150, 6900000, 69.00, [['fa' => 'پایه: CPU 8 هسته', 'en' => 'Base: 8-core CPU', 'tr' => 'Temel: 8 çekirdek CPU'], ['fa' => 'تا ۱۲۸ گیگ رم ECC', 'en' => 'Up to 128 GB ECC', 'tr' => '128 GB ECC\'ye kadar'], ['fa' => 'آرایه NVMe دلخواه', 'en' => 'Custom NVMe array', 'tr' => 'Özel NVMe dizisi'], $traffic, $setup]),
            $mk('CUS-PRO', 151, 12900000, 129.00, [['fa' => 'حرفه‌ای: CPU 16-32 هسته', 'en' => 'Pro: 16–32-core CPU', 'tr' => 'Pro: 16–32 çekirdek'], ['fa' => 'تا ۵۱۲ گیگ رم ECC', 'en' => 'Up to 512 GB ECC', 'tr' => '512 GB ECC\'ye kadar'], ['fa' => 'RAID سخت‌افزاری + GPU', 'en' => 'Hardware RAID + GPU option', 'tr' => 'Donanım RAID + GPU seçeneği'], $traffic, $setup], true),
            array_merge($mk('CUS-ENT', 152, 0, 0, [['fa' => 'Enterprise: چند نود کلاستر', 'en' => 'Enterprise: multi-node cluster', 'tr' => 'Enterprise: çok düğümlü küme'], ['fa' => 'طراحی HA و شبکه اختصاصی', 'en' => 'HA design + private fabric', 'tr' => 'HA tasarım + özel ağ'], ['fa' => 'SLA اختصاصی', 'en' => 'Custom SLA', 'tr' => 'Özel SLA'], $traffic, $setup]), ['contact' => true]),
        ],
        'features' => ['support', 'uptime', 'root', 'net10',
            ['icon' => 'wrench',
                'fa' => ['t' => 'مهندسی مشترک با تیم شما', 'd' => 'قبل از خرید، مهندسان ما نیاز شما را تحلیل و کانفیگ بهینه را با قیمت شفاف پیشنهاد می‌دهند — رایگان.'],
                'en' => ['t' => 'Co-Engineering With Your Team', 'd' => 'Before you buy, our engineers analyze your workload and propose the optimal build with transparent pricing — free.'],
                'tr' => ['t' => 'Ekibinizle Ortak Mühendislik', 'd' => 'Satın almadan önce mühendislerimiz iş yükünüzü analiz eder ve şeffaf fiyatla en uygun yapıyı önerir — ücretsiz.']],
        ],
        'faqs' => [$deliveryFaq, $hwFaq, 'manage',
            ['fa' => ['q' => 'حداقل مدت قرارداد چقدر است؟', 'a' => 'کانفیگ‌های سفارشی با تعهد ۳ ماهه ارائه می‌شوند (به‌دلیل تهیه قطعات اختصاصی)؛ بعد از آن ماه‌به‌ماه تمدید می‌کنید.'],
             'en' => ['q' => 'What\'s the minimum term?', 'a' => 'Custom builds come with a 3-month commitment (due to dedicated part sourcing); after that you renew month-to-month.'],
             'tr' => ['q' => 'Minimum süre nedir?', 'a' => 'Özel yapılandırmalar 3 aylık taahhütle sunulur; sonrasında aydan aya yenilersiniz.']],
        ],
    ],

    'ecommerce' => [
        'icon' => 'coins', 'group' => 'more',
        'fa' => ['t' => 'سرور اختصاصی فروشگاهی', 'tag' => 'بهینه برای فروشگاه‌های بزرگ',
            'hero_t' => 'سرور فروشگاهی،', 'hero_g' => 'آماده روز حراج.',
            'hero_d' => 'برای فروشگاه‌هایی که از هاست بزرگ‌تر شده‌اند — دیتابیس تیون‌شده، Redis اختصاصی، لود بالانس آماده و تیمی که شب حراج بیدار می‌ماند.'],
        'en' => ['t' => 'E-commerce Dedicated', 'tag' => 'Optimized for large stores',
            'hero_t' => 'Store servers,', 'hero_g' => 'ready for sale day.',
            'hero_d' => 'For stores that outgrew hosting — tuned databases, dedicated Redis, load-balancer ready, and a team that stays awake on campaign night.'],
        'tr' => ['t' => 'E-ticaret Sunucuları', 'tag' => 'Büyük mağazalar için optimize',
            'hero_t' => 'Mağaza sunucuları,', 'hero_g' => 'indirim gününe hazır.',
            'hero_d' => 'Hostingden büyüyen mağazalar için — ayarlı veritabanı, özel Redis ve kampanya gecesi uyanık kalan ekip.'],
        'chips' => ['DB Tuned', 'Redis Included', 'LB-Ready', 'NVMe Gen4', 'Campaign Support'],
        'plans' => [
            $mk('SHOP-S', 153, 7900000, 79.00, ['Ryzen 9 7950X · 16c/32t', '128 GB DDR5 ECC', '2 × 1 TB NVMe Gen4', ['fa' => 'MySQL/MariaDB تیون‌شده', 'en' => 'Tuned MySQL/MariaDB', 'tr' => 'Ayarlı MySQL/MariaDB'], ['fa' => 'Redis اختصاصی', 'en' => 'Dedicated Redis', 'tr' => 'Özel Redis']]),
            $mk('SHOP-M', 154, 12900000, 129.00, ['EPYC 7443P · 24c/48t', '256 GB DDR4 ECC', '2 × 1.92 TB NVMe', ['fa' => 'DB جدا + کش جدا (۲ سرور)', 'en' => 'Split DB + cache (2 servers)', 'tr' => 'Ayrık DB + önbellek (2 sunucu)'], ['fa' => 'مانیتورینگ کمپین', 'en' => 'Campaign monitoring', 'tr' => 'Kampanya izleme']], true),
            $mk('SHOP-L', 155, 19900000, 199.00, [['fa' => 'کلاستر ۳ نود + لودبالانسر', 'en' => '3-node cluster + LB', 'tr' => '3 düğümlü küme + LB'], '384 GB ECC RAM total', 'NVMe Gen4 everywhere', ['fa' => 'معماری HA بدون قطعی', 'en' => 'Zero-downtime HA design', 'tr' => 'Kesintisiz HA tasarımı'], ['fa' => 'مهندس اختصاصی', 'en' => 'Dedicated engineer', 'tr' => 'Özel mühendis']]),
        ],
        'features' => ['redis', 'ddos', 'uptime', 'support', 'backup',
            ['icon' => 'trend',
                'fa' => ['t' => 'تیم آماده‌باش کمپین', 'd' => 'قبل از جشنواره به ما خبر دهید — ظرفیت را از قبل رزرو و در طول کمپین لحظه‌ای مانیتور می‌کنیم.'],
                'en' => ['t' => 'Campaign Standby Team', 'd' => 'Tell us before your big sale — we pre-reserve capacity and monitor live throughout the campaign.'],
                'tr' => ['t' => 'Kampanya Nöbet Ekibi', 'd' => 'Büyük indirimden önce haber verin — kapasiteyi önceden ayırır, kampanya boyunca canlı izleriz.']],
        ],
        'faqs' => [$hwFaq, 'manage', 'migration', $deliveryFaq],
    ],

    'budget' => [
        'icon' => 'coins', 'group' => 'more',
        'fa' => ['t' => 'سرور اختصاصی اقتصادی', 'tag' => 'شروع دنیای Dedicated',
            'hero_t' => 'اولین سرور اختصاصی،', 'hero_g' => 'با قیمت سرور مجازی.',
            'hero_d' => 'سخت‌افزار نسل قبل ولی کاملاً اختصاصی — برای پروژه‌هایی که به منابع تضمین‌شده نیاز دارند اما بودجه سرور روز را ندارند.'],
        'en' => ['t' => 'Budget Dedicated', 'tag' => 'Your entry into dedicated',
            'hero_t' => 'Your first dedicated server,', 'hero_g' => 'at a VPS price.',
            'hero_d' => 'Previous-gen but fully dedicated hardware — for projects that need guaranteed resources without a flagship budget.'],
        'tr' => ['t' => 'Ekonomik Fiziksel Sunucu', 'tag' => 'Dedicated dünyasına giriş',
            'hero_t' => 'İlk dedicated sunucunuz,', 'hero_g' => 'VPS fiyatına.',
            'hero_d' => 'Önceki nesil ama tamamen özel donanım — garanti kaynak isteyen bütçeli projeler için.'],
        'chips' => ['Fully Dedicated', 'Best Price', 'SSD / NVMe', 'IPMI', 'EU Locations'],
        'plans' => [
            $mk('ECO-1', 156, 2900000, 29.00, ['Xeon E3-1245 v6 · 4c/8t', '32 GB DDR4', '2 × 480 GB SSD', $traffic, $ipmi]),
            $mk('ECO-2', 157, 3900000, 39.00, ['Xeon E5-1650 v4 · 6c/12t', '64 GB DDR4 ECC', '2 × 512 GB NVMe', $traffic, $ipmi], true),
            $mk('ECO-3', 158, 4900000, 49.00, ['Ryzen 5 5600 · 6c/12t', '64 GB DDR4', '2 × 1 TB NVMe', $traffic, $ipmi]),
        ],
        'features' => ['root', 'uptime', 'instant', 'support', 'net10'],
        'faqs' => [$hwFaq,
            ['fa' => ['q' => 'سخت‌افزار قدیمی مشکلی ایجاد نمی‌کند؟', 'a' => 'خیر — همه سرورها قبل از تحویل Burn-Test کامل می‌شوند و گارانتی تعویض قطعه در کمتر از ۴ ساعت دارند. برای وب‌سرور، بکاپ و سرویس‌های داخلی عملکردی عالی دارند.'],
             'en' => ['q' => 'Is older hardware a problem?', 'a' => 'No — every server is fully burn-tested before delivery, with sub-4-hour part replacement guarantees. Excellent for web serving, backups and internal services.'],
             'tr' => ['q' => 'Eski donanım sorun yaratır mı?', 'a' => 'Hayır — tüm sunucular teslimden önce tam test edilir, 4 saatin altında parça değişim garantisi vardır.']],
            $deliveryFaq, 'manage',
        ],
    ],

    'managed' => [
        'icon' => 'lifebuoy', 'group' => 'more',
        'fa' => ['t' => 'سرور اختصاصی مدیریت‌شده', 'tag' => 'Fully Managed · تیم شما، تیم ما',
            'hero_t' => 'شما کسب‌وکار را بچرخانید،', 'hero_g' => 'سرور با ما.',
            'hero_d' => 'نصب، امن‌سازی، مانیتورینگ ۲۴/۷، بکاپ، آپدیت و رفع مشکل — سرور اختصاصی با تیم فنی کامل، بدون استخدام حتی یک نفر.'],
        'en' => ['t' => 'Managed Dedicated', 'tag' => 'Fully managed · Our team, your team',
            'hero_t' => 'You run the business,', 'hero_g' => 'we run the server.',
            'hero_d' => 'Setup, hardening, 24/7 monitoring, backups, updates and incident response — a dedicated server with a full ops team, without hiring one.'],
        'tr' => ['t' => 'Yönetilen Fiziksel Sunucu', 'tag' => 'Tam yönetilen',
            'hero_t' => 'Siz işi yönetin,', 'hero_g' => 'sunucu bizde.',
            'hero_d' => 'Kurulum, sıkılaştırma, 7/24 izleme, yedekleme ve müdahale — tam ekipli dedicated sunucu, kimseyi işe almadan.'],
        'chips' => ['24/7 Monitoring', 'Security Hardening', 'Managed Backups', 'Incident Response', 'Monthly Reports'],
        'plans' => [
            $mk('MGD-S', 159, 9900000, 99.00, ['Ryzen 7 7700 · 64 GB ECC', '2 × 512 GB NVMe Gen4', ['fa' => 'مانیتورینگ + آپدیت ماهانه', 'en' => 'Monitoring + monthly patching', 'tr' => 'İzleme + aylık yama'], ['fa' => 'بکاپ روزانه مدیریت‌شده', 'en' => 'Managed daily backups', 'tr' => 'Yönetilen günlük yedek'], ['fa' => 'پاسخ حادثه < ۳۰ دقیقه', 'en' => 'Incident response < 30 min', 'tr' => 'Olay müdahalesi < 30 dk']]),
            $mk('MGD-M', 160, 16900000, 169.00, ['Ryzen 9 7950X · 128 GB ECC', '2 × 1 TB NVMe Gen4', ['fa' => 'مانیتورینگ + آپدیت هفتگی', 'en' => 'Monitoring + weekly patching', 'tr' => 'İzleme + haftalık yama'], ['fa' => 'بکاپ ۶ ساعته + DR', 'en' => '6-hour backups + DR plan', 'tr' => '6 saatlik yedek + DR'], ['fa' => 'پاسخ حادثه < ۱۵ دقیقه', 'en' => 'Incident response < 15 min', 'tr' => 'Olay müdahalesi < 15 dk']], true),
            $mk('MGD-L', 161, 29900000, 299.00, [['fa' => 'کلاستر HA چندسروره', 'en' => 'Multi-server HA cluster', 'tr' => 'Çok sunuculu HA küme'], ['fa' => 'مهندس اختصاصی نام‌دار', 'en' => 'Named dedicated engineer', 'tr' => 'İsimli özel mühendis'], ['fa' => 'مانیتورینگ سفارشی + گزارش', 'en' => 'Custom monitoring + reports', 'tr' => 'Özel izleme + raporlar'], ['fa' => 'SLA پاسخ ۵ دقیقه', 'en' => '5-minute response SLA', 'tr' => '5 dakikalık yanıt SLA'], ['fa' => 'DR کامل بین دو دیتاسنتر', 'en' => 'Full cross-DC disaster recovery', 'tr' => 'İki DC arası tam DR']]),
        ],
        'features' => ['support', 'uptime', 'backup', 'ddos',
            ['icon' => 'gauge',
                'fa' => ['t' => 'مانیتورینگ فعال، نه منفعل', 'd' => 'مشکل را قبل از اینکه شما بفهمید پیدا و رفع می‌کنیم — با هشدار خودکار و مداخله انسانی واقعی.'],
                'en' => ['t' => 'Proactive, Not Reactive Monitoring', 'd' => 'We find and fix issues before you notice — automated alerting backed by real human intervention.'],
                'tr' => ['t' => 'Reaktif Değil Proaktif İzleme', 'd' => 'Sorunları siz fark etmeden bulur ve çözeriz.']],
            ['icon' => 'book',
                'fa' => ['t' => 'گزارش ماهانه شفاف', 'd' => 'هر ماه گزارش کامل آپتایم، مصرف منابع، آپدیت‌ها و رخدادها را دریافت می‌کنید — بدانید پولتان کجا کار می‌کند.'],
                'en' => ['t' => 'Transparent Monthly Reports', 'd' => 'Every month: full uptime, resource usage, patching and incident report — know what your money does.'],
                'tr' => ['t' => 'Şeffaf Aylık Raporlar', 'd' => 'Her ay: tam çalışma süresi, kaynak kullanımı ve olay raporu.']],
        ],
        'faqs' => ['manage',
            ['fa' => ['q' => 'دقیقاً چه چیزهایی را مدیریت می‌کنید؟', 'a' => 'همه‌چیز به‌جز کد اپلیکیشن شما: سیستم‌عامل، وب‌سرور، دیتابیس، امنیت، فایروال، بکاپ، مانیتورینگ و رفع حادثه. تغییرات با تیکت درخواست می‌شود و طبق SLA انجام می‌شود.'],
             'en' => ['q' => 'What exactly do you manage?', 'a' => 'Everything except your application code: OS, web server, database, security, firewall, backups, monitoring and incident response. Changes are requested by ticket and delivered per SLA.'],
             'tr' => ['q' => 'Tam olarak neleri yönetiyorsunuz?', 'a' => 'Uygulama kodunuz hariç her şeyi: OS, web sunucusu, veritabanı, güvenlik, yedekler, izleme ve olay müdahalesi.']],
            $hwFaq, 'migration',
        ],
    ],
];
