<?php

/*
|--------------------------------------------------------------------------
| کاتالوگ سرور مجازی — ۱۱ صفحه (fa / en / tr)
|--------------------------------------------------------------------------
| pid ها placeholder هستند و باید با محصولات واقعی WHMCS جایگزین شوند.
*/

$traffic = ['fa' => 'ترافیک نامحدود', 'en' => 'Unlimited traffic', 'tr' => 'Sınırsız trafik'];
$root = ['fa' => 'دسترسی کامل روت', 'en' => 'Full root access', 'tr' => 'Tam root erişimi'];
$snap = ['fa' => 'بکاپ + اسنپ‌شات', 'en' => 'Backups + snapshots', 'tr' => 'Yedek + anlık görüntü'];

$mk = fn (string $name, int $pid, int $irt, float $eur, array $specs, bool $pop = false) =>
    array_filter(['name' => $name, 'pid' => $pid, 'irt' => $irt, 'eur' => $eur, 'specs' => $specs, 'popular' => $pop]);

return [

    'iran' => [
        'icon' => 'cpu', 'group' => 'location',
        'fa' => ['t' => 'سرور مجازی ایران',
            'seo_t' => 'خرید سرور مجازی ایران | NVMe، پینگ ۱ms، تحویل آنی',
            'seo_d' => 'خرید سرور مجازی ایران با دیسک NVMe، دیتاسنتر تهران و پینگ ۱ میلی‌ثانیه؛ ترافیک داخلی نیم‌بها، IP اختصاصی، پرداخت ریالی و تحویل خودکار در چند دقیقه. پرداخت ماهانه یا ساعتی.',
            'tag' => 'دیتاسنتر تهران · ترافیک داخلی نیم‌بها',
            'hero_t' => 'سرور مجازی ایران،', 'hero_g' => 'با پینگ ۱ میلی‌ثانیه.',
            'hero_d' => 'NVMe در قلب تهران — برای سایت‌ها و اپلیکیشن‌هایی که کاربر ایرانی دارند: سریع‌ترین پینگ، ترافیک داخلی نیم‌بها و تحویل آنی.'],
        'en' => ['t' => 'Iran VPS',
            'seo_t' => 'Buy Iran VPS | NVMe, 1 ms latency, instant delivery',
            'seo_d' => 'Buy an Iran VPS with NVMe storage in a Tehran data centre: 1 ms local latency, discounted domestic traffic, dedicated IP and automatic delivery in minutes. Monthly or hourly billing.',
            'tag' => 'Tehran datacenter · Local traffic',
            'hero_t' => 'Iran VPS with', 'hero_g' => '1 ms local latency.',
            'hero_d' => 'NVMe in the heart of Tehran — for sites and apps serving Iranian users: the fastest local ping, discounted domestic traffic and instant delivery.'],
        'tr' => ['t' => 'İran VPS', 'tag' => 'Tahran veri merkezi',
            'hero_t' => '1 ms yerel gecikmeyle', 'hero_g' => 'İran VPS.',
            'hero_d' => 'Tahran\'ın kalbinde NVMe — İranlı kullanıcılara hizmet veren siteler için: en hızlı yerel ping, indirimli yurt içi trafik ve anında teslim.'],
        'chips' => ['NVMe RAID-10', 'Tehran DC', '1 Gbit Port', 'IPv4 + IPv6', 'Anti-DDoS'],
        'signature' => ['type' => 'pings',
            'fa' => ['t' => 'پینگ از شهرهای ایران', 'd' => 'میانگین تاخیر شبکه از ISPهای اصلی کشور تا سرور مجازی ایران سرورنت'],
            'en' => ['t' => 'Ping from Iranian cities', 'd' => 'Average network latency from major national ISPs to ServerNet Iran VPS'],
            'tr' => ['t' => 'İran şehirlerinden ping', 'd' => 'Büyük ulusal ISS\'lerden ServerNet İran VPS\'e ortalama ağ gecikmesi'],
            'items' => [
                ['fa' => 'تهران', 'en' => 'Tehran', 'tr' => 'Tahran', 'ms' => '1 ms'],
                ['fa' => 'اصفهان', 'en' => 'Isfahan', 'tr' => 'İsfahan', 'ms' => '8 ms'],
                ['fa' => 'مشهد', 'en' => 'Mashhad', 'tr' => 'Meşhed', 'ms' => '14 ms'],
                ['fa' => 'تبریز', 'en' => 'Tabriz', 'tr' => 'Tebriz', 'ms' => '12 ms'],
                ['fa' => 'شیراز', 'en' => 'Shiraz', 'tr' => 'Şiraz', 'ms' => '10 ms'],
            ]],
        'plans' => [
            $mk('IR-1', 70, 490000, 4.90, ['1 vCPU / 2 GB RAM', '25 GB NVMe', $traffic, $root, $snap]),
            $mk('IR-2', 71, 990000, 9.90, ['2 vCPU / 4 GB RAM', '60 GB NVMe', $traffic, $root, $snap], true),
            $mk('IR-3', 72, 1890000, 18.90, ['4 vCPU / 8 GB RAM', '120 GB NVMe', $traffic, $root, $snap]),
            $mk('IR-4', 73, 3490000, 34.90, ['8 vCPU / 16 GB RAM', '240 GB NVMe', $traffic, $root, $snap]),
        ],
        'features' => ['instant', 'root', 'scale', 'ddos', 'uptime', 'support'],
        'faqs' => ['activation', 'os', 'manage', 'refund'],
    ],

    'international' => [
        'icon' => 'globe', 'group' => 'location',
        'fa' => ['t' => 'سرور مجازی خارج',
            'seo_t' => 'خرید سرور مجازی خارج | آلمان، فنلاند، فرانسه، آمریکا',
            'seo_d' => 'خرید سرور مجازی خارج از ایران در آلمان، فنلاند، فرانسه و آمریکا با NVMe، پورت ۱۰ گیگ و ۲۰ ترابایت ترافیک؛ پرداخت ریالی، تحویل زیر ۶۰ ثانیه و پشتیبانی فارسی ۲۴/۷.',
            'tag' => 'آلمان · فنلاند · فرانسه · آمریکا',
            'hero_t' => 'سرور مجازی خارج،', 'hero_g' => 'به انتخاب شما.',
            'hero_d' => 'چهار لوکیشن بین‌المللی روی سخت‌افزار نسل جدید — لوکیشن را هنگام سفارش انتخاب کنید؛ بقیه‌اش با ما. تحویل زیر ۶۰ ثانیه.'],
        'en' => ['t' => 'International VPS',
            'seo_t' => 'Buy International VPS | Germany, Finland, France, USA',
            'seo_d' => 'Buy an international VPS in Germany, Finland, France or the USA with NVMe, 10 Gbit ports and 20 TB traffic; delivered in under 60 seconds with 24/7 support.',
            'tag' => 'Germany · Finland · France · USA',
            'hero_t' => 'International VPS,', 'hero_g' => 'your location, your call.',
            'hero_d' => 'Four international locations on latest-gen hardware — pick your location at checkout, we handle the rest. Delivered in under 60 seconds.'],
        'tr' => ['t' => 'Yurt Dışı VPS', 'tag' => 'Almanya · Finlandiya · Fransa · ABD',
            'hero_t' => 'Yurt dışı VPS,', 'hero_g' => 'lokasyon sizin seçiminiz.',
            'hero_d' => 'Son nesil donanımda dört uluslararası lokasyon — ödeme sırasında seçin, gerisi bizde. 60 saniyenin altında teslim.'],
        'chips' => ['NVMe RAID-10', '10 Gbit Network', '4 Locations', 'IPv4 + IPv6', 'Hourly Snapshots'],
        'signature' => ['type' => 'pings',
            'fa' => ['t' => 'پینگ از تهران به لوکیشن‌ها', 'd' => 'میانگین تاخیر شبکه از ایران — برای انتخاب بهترین لوکیشن کاربرانتان'],
            'en' => ['t' => 'Latency from Tehran', 'd' => 'Average network latency from Iran — pick the best location for your users'],
            'tr' => ['t' => 'Tahran\'dan gecikme', 'd' => 'İran\'dan ortalama ağ gecikmesi — kullanıcılarınız için en iyi lokasyonu seçin'],
            'items' => [
                ['fa' => 'فرانکفورت', 'en' => 'Frankfurt', 'tr' => 'Frankfurt', 'ms' => '45 ms'],
                ['fa' => 'هلسینکی', 'en' => 'Helsinki', 'tr' => 'Helsinki', 'ms' => '62 ms'],
                ['fa' => 'پاریس', 'en' => 'Paris', 'tr' => 'Paris', 'ms' => '55 ms'],
                ['fa' => 'نیویورک', 'en' => 'New York', 'tr' => 'New York', 'ms' => '115 ms'],
            ]],
        'plans' => [
            $mk('EU-1', 74, 590000, 5.90, ['1 vCPU / 2 GB RAM', '25 GB NVMe', '20 TB Traffic', $root, $snap]),
            $mk('EU-2', 75, 1190000, 11.90, ['2 vCPU / 4 GB RAM', '60 GB NVMe', '20 TB Traffic', $root, $snap], true),
            $mk('EU-3', 76, 2190000, 21.90, ['4 vCPU / 8 GB RAM', '120 GB NVMe', '20 TB Traffic', $root, $snap]),
            $mk('EU-4', 77, 3990000, 39.90, ['8 vCPU / 16 GB RAM', '240 GB NVMe', '20 TB Traffic', $root, $snap]),
        ],
        'features' => ['instant', 'root', 'scale', 'net10', 'ddos', 'support'],
        'faqs' => ['activation', 'os', 'manage', 'refund'],
    ],

    'germany' => [
        'icon' => 'cpu', 'group' => 'location',
        'fa' => ['t' => 'سرور مجازی آلمان',
            'seo_t' => 'خرید سرور مجازی آلمان | فرانکفورت، NVMe، پورت ۱۰ گیگ',
            'seo_d' => 'خرید سرور مجازی آلمان در دیتاسنتر فرانکفورت (DE-CIX) با NVMe و پورت ۱۰ گیگابیت؛ پینگ حدود ۴۵ms از تهران، پرداخت ریالی، تحویل آنی و پشتیبانی فارسی.',
            'tag' => 'فرانکفورت · Tier III+',
            'hero_t' => 'سرور مجازی آلمان،', 'hero_g' => 'قلب اینترنت اروپا.',
            'hero_d' => 'فرانکفورت — بزرگ‌ترین نقطه تبادل ترافیک جهان (DE-CIX). بهترین انتخاب برای پوشش هم‌زمان کاربران ایران و اروپا.'],
        'en' => ['t' => 'Germany VPS',
            'seo_t' => 'Buy Germany VPS | Frankfurt, NVMe, 10 Gbit',
            'seo_d' => 'Buy a Germany VPS in Frankfurt (DE-CIX) with NVMe storage and a 10 Gbit port; instant delivery, dedicated IP and 24/7 support.',
            'tag' => 'Frankfurt · Tier III+',
            'hero_t' => 'Germany VPS,', 'hero_g' => 'the heart of European internet.',
            'hero_d' => 'Frankfurt — home of DE-CIX, the world\'s largest internet exchange. The best choice to serve Iranian and European users at once.'],
        'tr' => ['t' => 'Almanya VPS', 'tag' => 'Frankfurt · Tier III+',
            'hero_t' => 'Almanya VPS,', 'hero_g' => 'Avrupa internetinin kalbi.',
            'hero_d' => 'Frankfurt — dünyanın en büyük internet değişim noktası DE-CIX\'in evi. İran ve Avrupa kullanıcılarına aynı anda hizmet için en iyi seçim.'],
        'chips' => ['Frankfurt DC', 'DE-CIX', 'NVMe RAID-10', '10 Gbit', 'GDPR-Ready'],
        'signature' => ['type' => 'pings',
            'fa' => ['t' => 'فرانکفورت از نگاه شبکه', 'd' => 'میانگین تاخیر تا مقاصد کلیدی — چرا آلمان محبوب‌ترین لوکیشن کاربران ایرانی است'],
            'en' => ['t' => 'Frankfurt, network-wise', 'd' => 'Average latency to key destinations — why Germany is the most popular location'],
            'tr' => ['t' => 'Ağ açısından Frankfurt', 'd' => 'Önemli noktalara ortalama gecikme'],
            'items' => [
                ['fa' => 'تهران', 'en' => 'Tehran', 'tr' => 'Tahran', 'ms' => '45 ms'],
                ['fa' => 'استانبول', 'en' => 'Istanbul', 'tr' => 'İstanbul', 'ms' => '28 ms'],
                ['fa' => 'لندن', 'en' => 'London', 'tr' => 'Londra', 'ms' => '11 ms'],
                ['fa' => 'دبی', 'en' => 'Dubai', 'tr' => 'Dubai', 'ms' => '88 ms'],
            ]],
        'plans' => [
            $mk('DE-1', 81, 590000, 5.90, ['1 vCPU / 2 GB RAM', '25 GB NVMe', '20 TB Traffic', $root, $snap]),
            $mk('DE-2', 82, 1190000, 11.90, ['2 vCPU / 4 GB RAM', '60 GB NVMe', '20 TB Traffic', $root, $snap], true),
            $mk('DE-3', 83, 2190000, 21.90, ['4 vCPU / 8 GB RAM', '120 GB NVMe', '20 TB Traffic', $root, $snap]),
        ],
        'features' => ['instant', 'root', 'net10', 'ddos', 'uptime', 'support'],
        'faqs' => ['activation', 'os', 'manage', 'refund'],
    ],

    'finland' => [
        'icon' => 'cpu', 'group' => 'location',
        'fa' => ['t' => 'سرور مجازی فنلاند',
            'seo_t' => 'خرید سرور مجازی فنلاند | هلسینکی، اقتصادی و پرسرعت',
            'seo_d' => 'خرید سرور مجازی فنلاند در دیتاسنتر هلسینکی — همان سخت‌افزار آلمان با قیمت اقتصادی‌تر؛ NVMe، پورت ۱۰ گیگ، پرداخت ریالی و تحویل خودکار.',
            'tag' => 'هلسینکی · انرژی سبز',
            'hero_t' => 'سرور مجازی فنلاند،', 'hero_g' => 'قدرت با قیمت به‌صرفه.',
            'hero_d' => 'دیتاسنتر هلسینکی با خنک‌سازی طبیعی و انرژی سبز — همان سخت‌افزار آلمان با قیمتی اقتصادی‌تر. مناسب پروژه‌هایی که حساسیت پینگ کمتری دارند.'],
        'en' => ['t' => 'Finland VPS',
            'seo_t' => 'Buy Finland VPS | Helsinki, best value, NVMe',
            'seo_d' => 'Buy a Finland VPS in Helsinki — the same hardware as Germany at a friendlier price; NVMe, 10 Gbit port, instant automatic delivery.',
            'tag' => 'Helsinki · Green energy',
            'hero_t' => 'Finland VPS,', 'hero_g' => 'power at a smarter price.',
            'hero_d' => 'Helsinki datacenter with natural cooling and green energy — the same hardware as Germany at a friendlier price. Great for less latency-critical workloads.'],
        'tr' => ['t' => 'Finlandiya VPS', 'tag' => 'Helsinki · Yeşil enerji',
            'hero_t' => 'Finlandiya VPS,', 'hero_g' => 'akıllı fiyata güç.',
            'hero_d' => 'Doğal soğutma ve yeşil enerjiyle Helsinki veri merkezi — Almanya ile aynı donanım, daha uygun fiyat.'],
        'chips' => ['Helsinki DC', 'Green Energy', 'NVMe RAID-10', '10 Gbit', 'Best Value'],
        'signature' => ['type' => 'pings',
            'fa' => ['t' => 'پینگ از مقاصد کلیدی', 'd' => 'هلسینکی — تعادل عالی بین هزینه و کیفیت شبکه'],
            'en' => ['t' => 'Latency from key locations', 'd' => 'Helsinki — a great balance of cost and network quality'],
            'tr' => ['t' => 'Önemli noktalardan gecikme', 'd' => 'Helsinki — maliyet ve ağ kalitesi dengesi'],
            'items' => [
                ['fa' => 'تهران', 'en' => 'Tehran', 'tr' => 'Tahran', 'ms' => '62 ms'],
                ['fa' => 'مسکو', 'en' => 'Moscow', 'tr' => 'Moskova', 'ms' => '18 ms'],
                ['fa' => 'فرانکفورت', 'en' => 'Frankfurt', 'tr' => 'Frankfurt', 'ms' => '22 ms'],
                ['fa' => 'استکهلم', 'en' => 'Stockholm', 'tr' => 'Stokholm', 'ms' => '8 ms'],
            ]],
        'plans' => [
            $mk('FI-1', 84, 550000, 5.50, ['1 vCPU / 2 GB RAM', '25 GB NVMe', '20 TB Traffic', $root, $snap]),
            $mk('FI-2', 85, 1090000, 10.90, ['2 vCPU / 4 GB RAM', '60 GB NVMe', '20 TB Traffic', $root, $snap], true),
            $mk('FI-3', 86, 1990000, 19.90, ['4 vCPU / 8 GB RAM', '120 GB NVMe', '20 TB Traffic', $root, $snap]),
        ],
        'features' => ['instant', 'root', 'net10', 'scale', 'uptime', 'support'],
        'faqs' => ['activation', 'os', 'manage', 'refund'],
    ],

    'france' => [
        'icon' => 'cpu', 'group' => 'location',
        'fa' => ['t' => 'سرور مجازی فرانسه',
            'seo_t' => 'خرید سرور مجازی فرانسه | پاریس، Anti-DDoS پیش‌فرض',
            'seo_d' => 'خرید سرور مجازی فرانسه در دیتاسنترهای پاریس و گراولین با محافظت Anti-DDoS پیش‌فرض؛ NVMe، IP اختصاصی، پرداخت ریالی و تحویل آنی.',
            'tag' => 'پاریس · گراولین',
            'hero_t' => 'سرور مجازی فرانسه،', 'hero_g' => 'روی زیرساخت OVH.',
            'hero_d' => 'دیتاسنترهای پاریس و گراولین با محافظت Anti-DDoS پیش‌فرض OVH — انتخابی مطمئن برای وب‌سایت‌های اروپایی و پروژه‌های پرترافیک.'],
        'en' => ['t' => 'France VPS',
            'seo_t' => 'Buy France VPS | Paris, built-in Anti-DDoS',
            'seo_d' => 'Buy a France VPS in Paris and Gravelines with built-in Anti-DDoS protection; NVMe storage, dedicated IP and instant delivery.',
            'tag' => 'Paris · Gravelines',
            'hero_t' => 'France VPS', 'hero_g' => 'on OVH infrastructure.',
            'hero_d' => 'Paris and Gravelines datacenters with OVH\'s default Anti-DDoS — a reliable pick for European websites and high-traffic projects.'],
        'tr' => ['t' => 'Fransa VPS', 'tag' => 'Paris · Gravelines',
            'hero_t' => 'OVH altyapısında', 'hero_g' => 'Fransa VPS.',
            'hero_d' => 'OVH\'nin varsayılan Anti-DDoS korumasıyla Paris ve Gravelines veri merkezleri — Avrupa siteleri için güvenilir seçim.'],
        'chips' => ['OVH Infra', 'Anti-DDoS Included', 'NVMe', '1 → 10 Gbit', 'IPv4 + IPv6'],
        'signature' => ['type' => 'pings',
            'fa' => ['t' => 'پینگ از مقاصد کلیدی', 'd' => 'پاریس — دروازه اروپای غربی'],
            'en' => ['t' => 'Latency from key locations', 'd' => 'Paris — the gateway to Western Europe'],
            'tr' => ['t' => 'Önemli noktalardan gecikme', 'd' => 'Paris — Batı Avrupa\'nın kapısı'],
            'items' => [
                ['fa' => 'تهران', 'en' => 'Tehran', 'tr' => 'Tahran', 'ms' => '55 ms'],
                ['fa' => 'لندن', 'en' => 'London', 'tr' => 'Londra', 'ms' => '8 ms'],
                ['fa' => 'مادرید', 'en' => 'Madrid', 'tr' => 'Madrid', 'ms' => '17 ms'],
                ['fa' => 'فرانکفورت', 'en' => 'Frankfurt', 'tr' => 'Frankfurt', 'ms' => '10 ms'],
            ]],
        'plans' => [
            $mk('FR-1', 78, 590000, 5.90, ['1 vCPU / 2 GB RAM', '25 GB NVMe', '20 TB Traffic', $root, $snap]),
            $mk('FR-2', 79, 1190000, 11.90, ['2 vCPU / 4 GB RAM', '60 GB NVMe', '20 TB Traffic', $root, $snap], true),
            $mk('FR-3', 80, 2190000, 21.90, ['4 vCPU / 8 GB RAM', '120 GB NVMe', '20 TB Traffic', $root, $snap]),
        ],
        'features' => ['instant', 'root', 'ddos', 'scale', 'uptime', 'support'],
        'faqs' => ['activation', 'os', 'manage', 'refund'],
    ],

    'usa' => [
        'icon' => 'cpu', 'group' => 'location',
        'fa' => ['t' => 'سرور مجازی آمریکا',
            'seo_t' => 'خرید سرور مجازی آمریکا | نیویورک و لس‌آنجلس',
            'seo_d' => 'خرید سرور مجازی آمریکا در نیویورک و لس‌آنجلس با NVMe و IP اختصاصی؛ مناسب کاربران آمریکای شمالی، پرداخت ریالی و تحویل خودکار در چند دقیقه.',
            'tag' => 'نیویورک · لس‌آنجلس',
            'hero_t' => 'سرور مجازی آمریکا،', 'hero_g' => 'دو ساحل، یک کلیک.',
            'hero_d' => 'نیویورک برای پوشش اروپا و شرق آمریکا، لس‌آنجلس برای آسیا و غرب — با شبکه پرظرفیت و IPهای تمیز آمریکایی.'],
        'en' => ['t' => 'USA VPS',
            'seo_t' => 'Buy USA VPS | New York and Los Angeles',
            'seo_d' => 'Buy a USA VPS in New York or Los Angeles with NVMe storage and a dedicated IP; ideal for North American audiences, delivered automatically in minutes.',
            'tag' => 'New York · Los Angeles',
            'hero_t' => 'USA VPS,', 'hero_g' => 'both coasts, one click.',
            'hero_d' => 'New York to cover Europe and the US East, Los Angeles for Asia and the West — high-capacity network and clean US IPs.'],
        'tr' => ['t' => 'ABD VPS', 'tag' => 'New York · Los Angeles',
            'hero_t' => 'ABD VPS,', 'hero_g' => 'iki kıyı, tek tık.',
            'hero_d' => 'Avrupa ve ABD doğusu için New York, Asya ve batı için Los Angeles — yüksek kapasiteli ağ ve temiz ABD IP\'leri.'],
        'chips' => ['NY + LA', 'Clean US IPs', 'NVMe RAID-10', '10 Gbit', 'IPv4 + IPv6'],
        'signature' => ['type' => 'pings',
            'fa' => ['t' => 'پینگ از مقاصد کلیدی', 'd' => 'دو لوکیشن برای پوشش کامل قاره آمریکا'],
            'en' => ['t' => 'Latency from key locations', 'd' => 'Two locations for full continental coverage'],
            'tr' => ['t' => 'Önemli noktalardan gecikme', 'd' => 'Tam kıta kapsaması için iki lokasyon'],
            'items' => [
                ['fa' => 'تهران → نیویورک', 'en' => 'Tehran → NY', 'tr' => 'Tahran → NY', 'ms' => '115 ms'],
                ['fa' => 'لندن → نیویورک', 'en' => 'London → NY', 'tr' => 'Londra → NY', 'ms' => '70 ms'],
                ['fa' => 'توکیو → لس‌آنجلس', 'en' => 'Tokyo → LA', 'tr' => 'Tokyo → LA', 'ms' => '98 ms'],
                ['fa' => 'تورنتو → نیویورک', 'en' => 'Toronto → NY', 'tr' => 'Toronto → NY', 'ms' => '12 ms'],
            ]],
        'plans' => [
            $mk('US-1', 87, 650000, 6.50, ['1 vCPU / 2 GB RAM', '25 GB NVMe', '20 TB Traffic', $root, $snap]),
            $mk('US-2', 88, 1290000, 12.90, ['2 vCPU / 4 GB RAM', '60 GB NVMe', '20 TB Traffic', $root, $snap], true),
            $mk('US-3', 89, 2390000, 23.90, ['4 vCPU / 8 GB RAM', '120 GB NVMe', '20 TB Traffic', $root, $snap]),
        ],
        'features' => ['instant', 'root', 'net10', 'scale', 'uptime', 'support'],
        'faqs' => ['activation', 'os', 'manage', 'refund'],
    ],

    // ─────────────────────────────────────────────────────────────────────
    // کشورهایی که پلنِ زنده داریم ولی تا امروز صفحهٔ بازاریابی نداشتند.
    // بی‌این صفحات، جستجوی «سرور مجازی روسیه/سنگاپور/…» در گوگل ما را پیدا
    // نمی‌کرد — درآمدِ ازدست‌رفته. اسلاگ‌ها در CloudCountry::MARKETING_SLUG نگاشته
    // شده‌اند تا منو و صفحهٔ کشور به همین‌جا لینک دهند (نه ۴۰۴). pidها placeholder.
    // ─────────────────────────────────────────────────────────────────────

    'russia' => [
        'icon' => 'cpu', 'group' => 'location',
        'fa' => ['t' => 'سرور مجازی روسیه', 'tag' => 'مسکو · مسیر کوتاه تا ایران',
            'hero_t' => 'سرور مجازی روسیه،', 'hero_g' => 'نزدیک، سریع، پایدار.',
            'hero_d' => 'دیتاسنتر مسکو با یکی از کوتاه‌ترین مسیرهای شبکه تا ایران — انتخابی عالی برای کاربرانی که پینگ پایین می‌خواهند بی‌آنکه هزینهٔ لوکیشن‌های دورتر را بپردازند.'],
        'en' => ['t' => 'Russia VPS', 'tag' => 'Moscow · Short path to Iran',
            'hero_t' => 'Russia VPS,', 'hero_g' => 'close, fast, steady.',
            'hero_d' => 'A Moscow datacenter with one of the shortest network paths to Iran — great for users who want low latency without paying for far-away locations.'],
        'tr' => ['t' => 'Rusya VPS', 'tag' => 'Moskova · İran\'a kısa yol',
            'hero_t' => 'Rusya VPS,', 'hero_g' => 'yakın, hızlı, istikrarlı.',
            'hero_d' => 'İran\'a en kısa ağ yollarından birine sahip Moskova veri merkezi — uzak lokasyonların bedelini ödemeden düşük gecikme isteyenler için ideal.'],
        'chips' => ['Moscow DC', 'NVMe RAID-10', '1 Gbit Port', 'IPv4 + IPv6', 'Anti-DDoS'],
        'signature' => ['type' => 'pings',
            'fa' => ['t' => 'پینگ از مقاصد کلیدی', 'd' => 'مسکو — مسیر کوتاه به ایران و اروپای شرقی'],
            'en' => ['t' => 'Latency from key locations', 'd' => 'Moscow — a short path to Iran and Eastern Europe'],
            'tr' => ['t' => 'Önemli noktalardan gecikme', 'd' => 'Moskova — İran ve Doğu Avrupa\'ya kısa yol'],
            'items' => [
                ['fa' => 'تهران', 'en' => 'Tehran', 'tr' => 'Tahran', 'ms' => '55 ms'],
                ['fa' => 'استانبول', 'en' => 'Istanbul', 'tr' => 'İstanbul', 'ms' => '40 ms'],
                ['fa' => 'هلسینکی', 'en' => 'Helsinki', 'tr' => 'Helsinki', 'ms' => '18 ms'],
                ['fa' => 'فرانکفورت', 'en' => 'Frankfurt', 'tr' => 'Frankfurt', 'ms' => '35 ms'],
            ]],
        'plans' => [
            $mk('RU-1', 130, 520000, 5.20, ['1 vCPU / 2 GB RAM', '25 GB NVMe', $traffic, $root, $snap]),
            $mk('RU-2', 131, 990000, 9.90, ['2 vCPU / 4 GB RAM', '60 GB NVMe', $traffic, $root, $snap], true),
            $mk('RU-3', 132, 1890000, 18.90, ['4 vCPU / 8 GB RAM', '120 GB NVMe', $traffic, $root, $snap]),
        ],
        'features' => ['instant', 'root', 'scale', 'ddos', 'uptime', 'support'],
        'faqs' => ['activation', 'os', 'manage', 'refund'],
    ],

    'singapore' => [
        'icon' => 'cpu', 'group' => 'location',
        'fa' => ['t' => 'سرور مجازی سنگاپور', 'tag' => 'سنگاپور · دروازهٔ آسیا',
            'hero_t' => 'سرور مجازی سنگاپور،', 'hero_g' => 'دروازهٔ شرق دور.',
            'hero_d' => 'مرکز اتصال آسیای جنوب‌شرقی با کمترین تاخیر تا چین، هند و اقیانوسیه — انتخاب درست برای بازارها و کاربران آسیایی شما.'],
        'en' => ['t' => 'Singapore VPS', 'tag' => 'Singapore · Gateway to Asia',
            'hero_t' => 'Singapore VPS,', 'hero_g' => 'your gateway to the Far East.',
            'hero_d' => 'The connectivity hub of Southeast Asia with the lowest latency to China, India and Oceania — the right pick for your Asian markets and users.'],
        'tr' => ['t' => 'Singapur VPS', 'tag' => 'Singapur · Asya\'nın kapısı',
            'hero_t' => 'Singapur VPS,', 'hero_g' => 'Uzak Doğu\'ya açılan kapı.',
            'hero_d' => 'Çin, Hindistan ve Okyanusya\'ya en düşük gecikmeli Güneydoğu Asya bağlantı merkezi — Asya pazarlarınız için doğru seçim.'],
        'chips' => ['Singapore DC', 'Asia Hub', 'NVMe RAID-10', '10 Gbit', 'IPv4 + IPv6'],
        'signature' => ['type' => 'pings',
            'fa' => ['t' => 'پینگ از مقاصد کلیدی', 'd' => 'سنگاپور — نزدیک‌ترین قلب شبکه به آسیای شرقی'],
            'en' => ['t' => 'Latency from key locations', 'd' => 'Singapore — the closest network hub to East Asia'],
            'tr' => ['t' => 'Önemli noktalardan gecikme', 'd' => 'Singapur — Doğu Asya\'ya en yakın ağ merkezi'],
            'items' => [
                ['fa' => 'تهران', 'en' => 'Tehran', 'tr' => 'Tahran', 'ms' => '140 ms'],
                ['fa' => 'توکیو', 'en' => 'Tokyo', 'tr' => 'Tokyo', 'ms' => '68 ms'],
                ['fa' => 'دبی', 'en' => 'Dubai', 'tr' => 'Dubai', 'ms' => '95 ms'],
                ['fa' => 'هنگ‌کنگ', 'en' => 'Hong Kong', 'tr' => 'Hong Kong', 'ms' => '38 ms'],
            ]],
        'plans' => [
            $mk('SG-1', 133, 690000, 6.90, ['1 vCPU / 2 GB RAM', '25 GB NVMe', '20 TB Traffic', $root, $snap]),
            $mk('SG-2', 134, 1390000, 13.90, ['2 vCPU / 4 GB RAM', '60 GB NVMe', '20 TB Traffic', $root, $snap], true),
            $mk('SG-3', 135, 2590000, 25.90, ['4 vCPU / 8 GB RAM', '120 GB NVMe', '20 TB Traffic', $root, $snap]),
        ],
        'features' => ['instant', 'root', 'net10', 'scale', 'uptime', 'support'],
        'faqs' => ['activation', 'os', 'manage', 'refund'],
    ],

    'sweden' => [
        'icon' => 'cpu', 'group' => 'location',
        'fa' => ['t' => 'سرور مجازی سوئد', 'tag' => 'استکهلم · انرژی سبز',
            'hero_t' => 'سرور مجازی سوئد،', 'hero_g' => 'شمال اروپا، پایدار و سبز.',
            'hero_d' => 'دیتاسنتر استکهلم با انرژی تجدیدپذیر و شبکهٔ باکیفیت اسکاندیناوی — گزینه‌ای پایدار برای پروژه‌های اروپایی با تعهد به محیط‌زیست.'],
        'en' => ['t' => 'Sweden VPS', 'tag' => 'Stockholm · Green energy',
            'hero_t' => 'Sweden VPS,', 'hero_g' => 'Northern Europe, steady and green.',
            'hero_d' => 'A Stockholm datacenter on renewable energy with high-quality Scandinavian networking — a stable choice for European projects that care about sustainability.'],
        'tr' => ['t' => 'İsveç VPS', 'tag' => 'Stockholm · Yeşil enerji',
            'hero_t' => 'İsveç VPS,', 'hero_g' => 'Kuzey Avrupa, istikrarlı ve yeşil.',
            'hero_d' => 'Yenilenebilir enerjiyle çalışan Stockholm veri merkezi ve yüksek kaliteli İskandinav ağı — sürdürülebilirliğe önem veren Avrupa projeleri için istikrarlı seçim.'],
        'chips' => ['Stockholm DC', 'Green Energy', 'NVMe RAID-10', '10 Gbit', 'IPv4 + IPv6'],
        'signature' => ['type' => 'pings',
            'fa' => ['t' => 'پینگ از مقاصد کلیدی', 'd' => 'استکهلم — قلب شبکهٔ اسکاندیناوی'],
            'en' => ['t' => 'Latency from key locations', 'd' => 'Stockholm — the Scandinavian network hub'],
            'tr' => ['t' => 'Önemli noktalardan gecikme', 'd' => 'Stockholm — İskandinav ağ merkezi'],
            'items' => [
                ['fa' => 'هلسینکی', 'en' => 'Helsinki', 'tr' => 'Helsinki', 'ms' => '8 ms'],
                ['fa' => 'فرانکفورت', 'en' => 'Frankfurt', 'tr' => 'Frankfurt', 'ms' => '24 ms'],
                ['fa' => 'لندن', 'en' => 'London', 'tr' => 'Londra', 'ms' => '30 ms'],
                ['fa' => 'تهران', 'en' => 'Tehran', 'tr' => 'Tahran', 'ms' => '75 ms'],
            ]],
        'plans' => [
            $mk('SE-1', 136, 560000, 5.60, ['1 vCPU / 2 GB RAM', '25 GB NVMe', '20 TB Traffic', $root, $snap]),
            $mk('SE-2', 137, 1090000, 10.90, ['2 vCPU / 4 GB RAM', '60 GB NVMe', '20 TB Traffic', $root, $snap], true),
            $mk('SE-3', 138, 1990000, 19.90, ['4 vCPU / 8 GB RAM', '120 GB NVMe', '20 TB Traffic', $root, $snap]),
        ],
        'features' => ['instant', 'root', 'net10', 'scale', 'uptime', 'support'],
        'faqs' => ['activation', 'os', 'manage', 'refund'],
    ],

    'netherlands' => [
        'icon' => 'cpu', 'group' => 'location',
        'fa' => ['t' => 'سرور مجازی هلند', 'tag' => 'آمستردام · AMS-IX',
            'hero_t' => 'سرور مجازی هلند،', 'hero_g' => 'روی AMS-IX.',
            'hero_d' => 'آمستردام — یکی از بزرگ‌ترین نقاط تبادل ترافیک جهان (AMS-IX). پینگ عالی به سراسر اروپا و پهنای‌باند فراوان برای پروژه‌های پرمصرف.'],
        'en' => ['t' => 'Netherlands VPS', 'tag' => 'Amsterdam · AMS-IX',
            'hero_t' => 'Netherlands VPS,', 'hero_g' => 'right on AMS-IX.',
            'hero_d' => 'Amsterdam — home of AMS-IX, one of the world\'s largest internet exchanges. Excellent latency across Europe and plenty of bandwidth for heavy workloads.'],
        'tr' => ['t' => 'Hollanda VPS', 'tag' => 'Amsterdam · AMS-IX',
            'hero_t' => 'Hollanda VPS,', 'hero_g' => 'tam AMS-IX üzerinde.',
            'hero_d' => 'Amsterdam — dünyanın en büyük internet değişim noktalarından AMS-IX\'in evi. Avrupa geneline mükemmel gecikme ve yoğun işler için bol bant genişliği.'],
        'chips' => ['Amsterdam DC', 'AMS-IX', 'NVMe RAID-10', '10 Gbit', 'IPv4 + IPv6'],
        'signature' => ['type' => 'pings',
            'fa' => ['t' => 'پینگ از مقاصد کلیدی', 'd' => 'آمستردام — تقاطع شبکهٔ اروپا'],
            'en' => ['t' => 'Latency from key locations', 'd' => 'Amsterdam — Europe\'s network crossroads'],
            'tr' => ['t' => 'Önemli noktalardan gecikme', 'd' => 'Amsterdam — Avrupa\'nın ağ kavşağı'],
            'items' => [
                ['fa' => 'فرانکفورت', 'en' => 'Frankfurt', 'tr' => 'Frankfurt', 'ms' => '7 ms'],
                ['fa' => 'لندن', 'en' => 'London', 'tr' => 'Londra', 'ms' => '9 ms'],
                ['fa' => 'پاریس', 'en' => 'Paris', 'tr' => 'Paris', 'ms' => '11 ms'],
                ['fa' => 'تهران', 'en' => 'Tehran', 'tr' => 'Tahran', 'ms' => '85 ms'],
            ]],
        'plans' => [
            $mk('NL-1', 139, 590000, 5.90, ['1 vCPU / 2 GB RAM', '25 GB NVMe', '20 TB Traffic', $root, $snap]),
            $mk('NL-2', 140, 1190000, 11.90, ['2 vCPU / 4 GB RAM', '60 GB NVMe', '20 TB Traffic', $root, $snap], true),
            $mk('NL-3', 141, 2190000, 21.90, ['4 vCPU / 8 GB RAM', '120 GB NVMe', '20 TB Traffic', $root, $snap]),
        ],
        'features' => ['instant', 'root', 'net10', 'ddos', 'uptime', 'support'],
        'faqs' => ['activation', 'os', 'manage', 'refund'],
    ],

    'austria' => [
        'icon' => 'cpu', 'group' => 'location',
        'fa' => ['t' => 'سرور مجازی اتریش', 'tag' => 'وین · مرکز اروپا',
            'hero_t' => 'سرور مجازی اتریش،', 'hero_g' => 'قلب جغرافیایی اروپا.',
            'hero_d' => 'دیتاسنتر وین در مرکز اروپا با قوانین سختگیرانهٔ حریم خصوصی — پینگ متعادل به شرق و غرب قاره و بستری مطمئن برای دادهٔ حساس.'],
        'en' => ['t' => 'Austria VPS', 'tag' => 'Vienna · Central Europe',
            'hero_t' => 'Austria VPS,', 'hero_g' => 'the geographic heart of Europe.',
            'hero_d' => 'A Vienna datacenter at the center of Europe with strict privacy laws — balanced latency to both East and West, and a solid home for sensitive data.'],
        'tr' => ['t' => 'Avusturya VPS', 'tag' => 'Viyana · Orta Avrupa',
            'hero_t' => 'Avusturya VPS,', 'hero_g' => 'Avrupa\'nın coğrafi kalbi.',
            'hero_d' => 'Avrupa\'nın merkezinde, katı gizlilik yasalarına sahip Viyana veri merkezi — doğuya ve batıya dengeli gecikme, hassas veriler için sağlam bir yuva.'],
        'chips' => ['Vienna DC', 'Central EU', 'NVMe RAID-10', '10 Gbit', 'IPv4 + IPv6'],
        'signature' => ['type' => 'pings',
            'fa' => ['t' => 'پینگ از مقاصد کلیدی', 'd' => 'وین — تعادل بین شرق و غرب اروپا'],
            'en' => ['t' => 'Latency from key locations', 'd' => 'Vienna — balanced between East and West Europe'],
            'tr' => ['t' => 'Önemli noktalardan gecikme', 'd' => 'Viyana — Doğu ve Batı Avrupa arasında denge'],
            'items' => [
                ['fa' => 'فرانکفورت', 'en' => 'Frankfurt', 'tr' => 'Frankfurt', 'ms' => '12 ms'],
                ['fa' => 'استانبول', 'en' => 'Istanbul', 'tr' => 'İstanbul', 'ms' => '30 ms'],
                ['fa' => 'وارشو', 'en' => 'Warsaw', 'tr' => 'Varşova', 'ms' => '15 ms'],
                ['fa' => 'تهران', 'en' => 'Tehran', 'tr' => 'Tahran', 'ms' => '68 ms'],
            ]],
        'plans' => [
            $mk('AT-1', 142, 590000, 5.90, ['1 vCPU / 2 GB RAM', '25 GB NVMe', '20 TB Traffic', $root, $snap]),
            $mk('AT-2', 143, 1190000, 11.90, ['2 vCPU / 4 GB RAM', '60 GB NVMe', '20 TB Traffic', $root, $snap], true),
            $mk('AT-3', 144, 2190000, 21.90, ['4 vCPU / 8 GB RAM', '120 GB NVMe', '20 TB Traffic', $root, $snap]),
        ],
        'features' => ['instant', 'root', 'net10', 'scale', 'uptime', 'support'],
        'faqs' => ['activation', 'os', 'manage', 'refund'],
    ],

    'england' => [
        'icon' => 'cpu', 'group' => 'location',
        'fa' => ['t' => 'سرور مجازی انگلیس',
            'seo_t' => 'خرید سرور مجازی انگلیس | لندن، روی LINX',
            'seo_d' => 'خرید سرور مجازی انگلیس در دیتاسنتر لندن متصل به LINX؛ NVMe، IP اختصاصی، پرداخت ریالی، تحویل آنی و پشتیبانی فارسی ۲۴/۷.',
            'tag' => 'لندن · LINX',
            'hero_t' => 'سرور مجازی انگلیس،', 'hero_g' => 'لندن، روی LINX.',
            'hero_d' => 'دیتاسنتر لندن روی LINX — قطب مالی و اینترنتی بریتانیا. کمترین تاخیر به بازار انگلستان و اروپای غربی، مناسب فین‌تک و کسب‌وکارهای آنلاین.'],
        'en' => ['t' => 'UK VPS',
            'seo_t' => 'Buy UK VPS | London, on LINX',
            'seo_d' => 'Buy a UK VPS in a London data centre connected to LINX; NVMe storage, dedicated IP, instant delivery and 24/7 support.',
            'tag' => 'London · LINX',
            'hero_t' => 'UK VPS,', 'hero_g' => 'London, on LINX.',
            'hero_d' => 'A London datacenter on LINX — Britain\'s financial and internet hub. The lowest latency to the UK market and Western Europe, ideal for fintech and online business.'],
        'tr' => ['t' => 'İngiltere VPS', 'tag' => 'Londra · LINX',
            'hero_t' => 'İngiltere VPS,', 'hero_g' => 'Londra, LINX üzerinde.',
            'hero_d' => 'LINX üzerinde bir Londra veri merkezi — Britanya\'nın finans ve internet merkezi. Birleşik Krallık pazarına ve Batı Avrupa\'ya en düşük gecikme, fintech ve online iş için ideal.'],
        'chips' => ['London DC', 'LINX', 'NVMe RAID-10', '10 Gbit', 'IPv4 + IPv6'],
        'signature' => ['type' => 'pings',
            'fa' => ['t' => 'پینگ از مقاصد کلیدی', 'd' => 'لندن — دروازهٔ بازار بریتانیا'],
            'en' => ['t' => 'Latency from key locations', 'd' => 'London — gateway to the UK market'],
            'tr' => ['t' => 'Önemli noktalardan gecikme', 'd' => 'Londra — Birleşik Krallık pazarının kapısı'],
            'items' => [
                ['fa' => 'آمستردام', 'en' => 'Amsterdam', 'tr' => 'Amsterdam', 'ms' => '9 ms'],
                ['fa' => 'فرانکفورت', 'en' => 'Frankfurt', 'tr' => 'Frankfurt', 'ms' => '15 ms'],
                ['fa' => 'پاریس', 'en' => 'Paris', 'tr' => 'Paris', 'ms' => '8 ms'],
                ['fa' => 'تهران', 'en' => 'Tehran', 'tr' => 'Tahran', 'ms' => '90 ms'],
            ]],
        'plans' => [
            $mk('GB-1', 145, 650000, 6.50, ['1 vCPU / 2 GB RAM', '25 GB NVMe', '20 TB Traffic', $root, $snap]),
            $mk('GB-2', 146, 1290000, 12.90, ['2 vCPU / 4 GB RAM', '60 GB NVMe', '20 TB Traffic', $root, $snap], true),
            $mk('GB-3', 147, 2390000, 23.90, ['4 vCPU / 8 GB RAM', '120 GB NVMe', '20 TB Traffic', $root, $snap]),
        ],
        'features' => ['instant', 'root', 'net10', 'scale', 'uptime', 'support'],
        'faqs' => ['activation', 'os', 'manage', 'refund'],
    ],

    'trading' => [
        'icon' => 'trend', 'group' => 'use',
        'fa' => ['t' => 'سرور مجازی ترید',
            'seo_t' => 'سرور مجازی ترید | لندن LD4 و نیویورک NY4، تأخیر پایین',
            'seo_d' => 'خرید سرور مجازی ترید در ساختمان‌های LD4 لندن و NY4 نیویورک، همان‌جایی که سرورهای بروکرهاست؛ متاتریدر آماده، ویندوز سرور، آپتایم ۹۹.۹۹٪ و پرداخت ریالی.',
            'tag' => 'لندن LD4 · نیویورک NY4',
            'hero_t' => 'سرور ترید،', 'hero_g' => 'هر میلی‌ثانیه یعنی پول.',
            'hero_d' => 'میزبانی در ساختمان‌های LD4 لندن و NY4 نیویورک — همان‌جایی که سرورهای بروکرهاست. متاتریدر آماده، آپتایم ۹۹.۹۹٪ و اجرای سفارش بدون لغزش.'],
        'en' => ['t' => 'Trading VPS',
            'seo_t' => 'Trading VPS | London LD4 and New York NY4, low latency',
            'seo_d' => 'Buy a trading VPS hosted inside London LD4 and New York NY4 next to broker servers; MetaTrader ready, Windows Server, 99.99% uptime.',
            'tag' => 'London LD4 · New York NY4',
            'hero_t' => 'Trading VPS —', 'hero_g' => 'every millisecond is money.',
            'hero_d' => 'Hosted inside London LD4 and New York NY4 — the same buildings as broker servers. MetaTrader pre-installed, 99.99% uptime, slippage-free execution.'],
        'tr' => ['t' => 'Trade VPS', 'tag' => 'Londra LD4 · New York NY4',
            'hero_t' => 'Trade VPS —', 'hero_g' => 'her milisaniye paradır.',
            'hero_d' => 'Londra LD4 ve New York NY4 içinde barındırma — broker sunucularıyla aynı binalar. MetaTrader kurulu, %99,99 çalışma süresi.'],
        'chips' => ['LD4 / NY4', 'MT4 / MT5 Ready', 'Windows Server', '99.99% SLA', 'Low-Latency Network'],
        'signature' => ['type' => 'bars',
            'fa' => ['t' => 'تاخیر تا سرور بروکر', 'd' => 'میانگین Round-Trip تا سرورهای اصلی بروکرها — دلیل اینکه تریدرهای حرفه‌ای VPS ترید می‌گیرند'],
            'en' => ['t' => 'Latency to broker servers', 'd' => 'Average round-trip to major broker servers — why serious traders use a trading VPS'],
            'tr' => ['t' => 'Broker sunucularına gecikme', 'd' => 'Büyük broker sunucularına ortalama gidiş-dönüş süresi'],
            'items' => [
                ['fa' => 'سرورنت — داخل LD4', 'en' => 'ServerNet — inside LD4', 'tr' => 'ServerNet — LD4 içinde', 'val' => '0.9 ms', 'w' => '100%', 'hl' => true],
                ['fa' => 'VPS معمولی اروپا', 'en' => 'Typical EU VPS', 'tr' => 'Tipik AB VPS', 'val' => '25 ms', 'w' => '12%'],
                ['fa' => 'اینترنت خانگی ایران', 'en' => 'Home internet (Iran)', 'tr' => 'Ev interneti', 'val' => '180 ms', 'w' => '3%'],
            ]],
        'plans' => [
            $mk('TR-1', 90, 890000, 8.90, ['2 vCPU / 4 GB RAM', '60 GB NVMe', 'Windows Server 2022', ['fa' => 'متاتریدر نصب‌شده', 'en' => 'MetaTrader pre-installed', 'tr' => 'MetaTrader kurulu'], ['fa' => 'تا ۲ ترمینال هم‌زمان', 'en' => 'Up to 2 terminals', 'tr' => '2 terminale kadar']]),
            $mk('TR-2', 91, 1490000, 14.90, ['4 vCPU / 8 GB RAM', '100 GB NVMe', 'Windows Server 2022', ['fa' => 'متاتریدر نصب‌شده', 'en' => 'MetaTrader pre-installed', 'tr' => 'MetaTrader kurulu'], ['fa' => 'تا ۵ ترمینال هم‌زمان', 'en' => 'Up to 5 terminals', 'tr' => '5 terminale kadar']], true),
            $mk('TR-3', 92, 2690000, 26.90, ['8 vCPU / 16 GB RAM', '200 GB NVMe', 'Windows Server 2022', ['fa' => 'متاتریدر نصب‌شده', 'en' => 'MetaTrader pre-installed', 'tr' => 'MetaTrader kurulu'], ['fa' => 'ترمینال نامحدود + IP اختصاصی', 'en' => 'Unlimited terminals + dedicated IP', 'tr' => 'Sınırsız terminal + özel IP']]),
        ],
        'features' => ['uptime', 'instant', 'support', 'backup',
            ['icon' => 'clock',
                'fa' => ['t' => 'همیشه روشن، حتی وقت خواب', 'd' => 'اکسپرت‌ها و ربات‌های شما ۲۴/۵ بدون قطعی برق و اینترنت خانگی معامله می‌کنند.'],
                'en' => ['t' => 'Always on, even while you sleep', 'd' => 'Your EAs and bots trade 24/5 without home power or internet interruptions.'],
                'tr' => ['t' => 'Siz uyurken bile açık', 'd' => 'EA\'larınız ve botlarınız ev elektriği/interneti kesintisi olmadan 7/24 işlem yapar.']],
            ['icon' => 'gauge',
                'fa' => ['t' => 'شبکه Low-Latency اختصاصی', 'd' => 'مسیر مستقیم فیبر بین LD4 و NY4 و بروکرهای اصلی — بدون هاپ اضافه.'],
                'en' => ['t' => 'Dedicated low-latency network', 'd' => 'Direct fiber routes between LD4, NY4 and major brokers — zero extra hops.'],
                'tr' => ['t' => 'Özel düşük gecikmeli ağ', 'd' => 'LD4, NY4 ve büyük broker\'lar arasında doğrudan fiber — ek hop yok.']],
        ],
        'faqs' => ['activation',
            ['fa' => ['q' => 'کدام بروکرها نزدیک سرور شما هستند؟', 'a' => 'اکثر بروکرهای بزرگ (IC Markets، Pepperstone، Exness، آلپاری و…) سرورهای اجرا در LD4 لندن یا NY4 نیویورک دارند — دقیقاً همان‌جایی که VPS ترید سرورنت میزبانی می‌شود. پینگ زیر ۱ میلی‌ثانیه.'],
             'en' => ['q' => 'Which brokers are close to your servers?', 'a' => 'Most major brokers (IC Markets, Pepperstone, Exness, Alpari…) run execution servers in London LD4 or New York NY4 — exactly where ServerNet trading VPS lives. Sub-1 ms ping.'],
             'tr' => ['q' => 'Hangi broker\'lar sunucularınıza yakın?', 'a' => 'Büyük broker\'ların çoğu (IC Markets, Pepperstone, Exness, Alpari…) LD4 veya NY4\'te sunucu çalıştırır — ServerNet trade VPS tam orada. 1 ms altı ping.']],
            ['fa' => ['q' => 'آیا متاتریدر از قبل نصب است؟', 'a' => 'بله — MT4 و MT5 نصب و بهینه شده‌اند. فقط لاگین بروکرتان را وارد کنید و اکسپرت‌ها را فعال کنید.'],
             'en' => ['q' => 'Is MetaTrader pre-installed?', 'a' => 'Yes — MT4 and MT5 come installed and optimized. Just enter your broker login and enable your EAs.'],
             'tr' => ['q' => 'MetaTrader önceden kurulu mu?', 'a' => 'Evet — MT4 ve MT5 kurulu ve optimize. Broker girişinizi yapıp EA\'larınızı etkinleştirmeniz yeter.']],
            'upgrade', 'refund',
        ],
    ],

    'gpu' => [
        'icon' => 'monitor', 'group' => 'use',
        'fa' => ['t' => 'سرور مجازی گرافیکی',
            'seo_t' => 'اجاره سرور مجازی گرافیکی (GPU) | NVIDIA، CUDA 12',
            'seo_d' => 'اجاره سرور مجازی گرافیکی با کارت NVIDIA و درایور آمادهٔ CUDA 12 برای رندر، آموزش مدل و پردازش سنگین؛ ایمیج‌های آمادهٔ PyTorch و TensorFlow و پشتیبانی فارسی.',
            'tag' => 'NVIDIA · CUDA 12',
            'hero_t' => 'قدرت گرافیکی NVIDIA،', 'hero_g' => 'بدون خرید سخت‌افزار.',
            'hero_d' => 'GPUهای حرفه‌ای برای رندر، هوش مصنوعی و پردازش سنگین — با درایورهای آماده CUDA و ایمیج‌های از پیش پیکربندی‌شده PyTorch و TensorFlow.'],
        'en' => ['t' => 'GPU VPS',
            'seo_t' => 'Rent a GPU VPS | NVIDIA, CUDA 12',
            'seo_d' => 'Rent a GPU VPS with NVIDIA cards and ready CUDA 12 drivers for rendering, model training and heavy compute; pre-built PyTorch and TensorFlow images.',
            'tag' => 'NVIDIA · CUDA 12',
            'hero_t' => 'NVIDIA GPU power,', 'hero_g' => 'without buying hardware.',
            'hero_d' => 'Professional GPUs for rendering, AI and heavy compute — with ready CUDA drivers and pre-configured PyTorch and TensorFlow images.'],
        'tr' => ['t' => 'GPU VPS', 'tag' => 'NVIDIA · CUDA 12',
            'hero_t' => 'Donanım almadan', 'hero_g' => 'NVIDIA GPU gücü.',
            'hero_d' => 'Render, yapay zeka ve ağır işlem için profesyonel GPU\'lar — hazır CUDA sürücüleri ve önceden yapılandırılmış PyTorch/TensorFlow imajları.'],
        'chips' => ['CUDA 12', 'PyTorch / TensorFlow', 'NVMe RAID-10', 'Dedicated vGPU', 'Jupyter Ready'],
        'plans' => [
            $mk('G-4000', 93, 4900000, 49.00, ['RTX 4000 Ada · 20 GB', '8 vCPU / 32 GB RAM', '250 GB NVMe', ['fa' => 'درایور و CUDA آماده', 'en' => 'Drivers & CUDA ready', 'tr' => 'Sürücüler ve CUDA hazır'], $traffic]),
            $mk('G-A5000', 94, 7900000, 79.00, ['RTX A5000 · 24 GB', '12 vCPU / 64 GB RAM', '500 GB NVMe', ['fa' => 'درایور و CUDA آماده', 'en' => 'Drivers & CUDA ready', 'tr' => 'Sürücüler ve CUDA hazır'], $traffic], true),
            $mk('G-A100', 95, 14900000, 149.00, ['A100 · 40 GB HBM2e', '16 vCPU / 128 GB RAM', '1 TB NVMe', ['fa' => 'درایور و CUDA آماده', 'en' => 'Drivers & CUDA ready', 'tr' => 'Sürücüler ve CUDA hazır'], $traffic]),
        ],
        'features' => ['instant', 'root', 'scale', 'support', 'uptime',
            ['icon' => 'bot',
                'fa' => ['t' => 'ایمیج‌های آماده AI', 'd' => 'PyTorch، TensorFlow، ComfyUI و Jupyter از پیش نصب — از دقیقه اول آموزش مدل را شروع کنید.'],
                'en' => ['t' => 'Ready AI Images', 'd' => 'PyTorch, TensorFlow, ComfyUI and Jupyter pre-installed — start training from minute one.'],
                'tr' => ['t' => 'Hazır AI İmajları', 'd' => 'PyTorch, TensorFlow, ComfyUI ve Jupyter kurulu — ilk dakikadan eğitime başlayın.']],
        ],
        'faqs' => ['activation', 'os',
            ['fa' => ['q' => 'برای رندر مناسب است یا فقط AI؟', 'a' => 'هر دو — RTX 4000/A5000 برای رندر Blender و 3ds Max و DaVinci عالی‌اند؛ A100 برای آموزش و اجرای مدل‌های بزرگ زبان و تصویری طراحی شده.'],
             'en' => ['q' => 'Is it good for rendering or only AI?', 'a' => 'Both — RTX 4000/A5000 excel at Blender, 3ds Max and DaVinci rendering; the A100 is built for training and serving large language/vision models.'],
             'tr' => ['q' => 'Render için mi uygun, sadece AI mı?', 'a' => 'İkisi de — RTX 4000/A5000 Blender ve DaVinci render\'da mükemmel; A100 büyük modellerin eğitimi için tasarlandı.']],
            'refund',
        ],
    ],

    'cloud' => [
        'icon' => 'cloud', 'group' => 'use',
        'fa' => ['t' => 'سرور مجازی ابری',
            'seo_t' => 'خرید سرور مجازی ابری | اسنپ‌شات، مقیاس آنی، پرداخت ساعتی',
            'seo_d' => 'خرید سرور مجازی ابری با اسنپ‌شات لحظه‌ای، ارتقای بدون ری‌استارت و امکان پرداخت ساعتی یا ماهانه؛ NVMe، IP اختصاصی، پرداخت ریالی و تحویل خودکار.',
            'tag' => 'پرداخت ساعتی · مقیاس آنی',
            'hero_t' => 'سرور ابری،', 'hero_g' => 'به اندازه مصرف بپردازید.',
            'hero_d' => 'سرور مجازی نسل ابری با پرداخت ساعتی، اسنپ‌شات لحظه‌ای و ارتقای بدون ری‌استارت — بسازید، تست کنید، حذف کنید؛ فقط همان ساعت‌ها را می‌پردازید.'],
        'en' => ['t' => 'Cloud VPS',
            'seo_t' => 'Buy Cloud VPS | snapshots, instant scale, hourly billing',
            'seo_d' => 'Buy a cloud VPS with instant snapshots, no-restart scaling and hourly or monthly billing; NVMe storage, dedicated IP and automatic delivery.',
            'tag' => 'Hourly billing · Instant scale',
            'hero_t' => 'Cloud VPS —', 'hero_g' => 'pay for what you use.',
            'hero_d' => 'Cloud-generation VPS with hourly billing, instant snapshots and no-restart scaling — create, test, destroy; pay only for the hours used.'],
        'tr' => ['t' => 'Bulut VPS', 'tag' => 'Saatlik ödeme · Anında ölçek',
            'hero_t' => 'Bulut VPS —', 'hero_g' => 'kullandığın kadar öde.',
            'hero_d' => 'Saatlik faturalandırma, anlık snapshot ve yeniden başlatmasız ölçeklendirme — oluştur, test et, sil; sadece kullanılan saatleri öde.'],
        'chips' => ['Hourly Billing', 'API + CLI', 'Instant Snapshots', 'NVMe RAID-10', 'Private Network'],
        'plans' => [
            $mk('CV-1', 96, 590000, 5.90, ['1 vCPU / 2 GB RAM', '25 GB NVMe', ['fa' => 'یا ~۸۲۰ تومان/ساعت', 'en' => 'or ~€0.009/hour', 'tr' => 'veya ~€0,009/saat'], $traffic, $root]),
            $mk('CV-2', 97, 1090000, 10.90, ['2 vCPU / 4 GB RAM', '60 GB NVMe', ['fa' => 'یا ~۱,۵۲۰ تومان/ساعت', 'en' => 'or ~€0.016/hour', 'tr' => 'veya ~€0,016/saat'], $traffic, $root], true),
            $mk('CV-4', 98, 1990000, 19.90, ['4 vCPU / 8 GB RAM', '120 GB NVMe', ['fa' => 'یا ~۲,۷۷۰ تومان/ساعت', 'en' => 'or ~€0.028/hour', 'tr' => 'veya ~€0,028/saat'], $traffic, $root]),
        ],
        'features' => ['hourly', 'scale', 'instant', 'net10', 'backup', 'support'],
        'faqs' => ['activation', 'os',
            ['fa' => ['q' => 'پرداخت ساعتی دقیقاً چطور کار می‌کند؟', 'a' => 'کیف پول خود را شارژ می‌کنید و به ازای هر ساعتی که سرور وجود دارد، هزینه کسر می‌شود. سرور را حذف کنید، کسر هزینه همان لحظه متوقف می‌شود. سقف هزینه ماهانه همان قیمت پلن است.'],
             'en' => ['q' => 'How exactly does hourly billing work?', 'a' => 'Top up your wallet and pay per hour while the server exists. Delete the server and charges stop instantly. Monthly cost is capped at the plan price.'],
             'tr' => ['q' => 'Saatlik ödeme tam olarak nasıl çalışır?', 'a' => 'Cüzdanınızı doldurun, sunucu var olduğu her saat için ödeyin. Sunucuyu silin, ücretlendirme anında durur. Aylık maliyet plan fiyatıyla sınırlıdır.']],
            'manage', 'refund',
        ],
    ],

    'linux' => [
        'icon' => 'code', 'group' => 'os',
        'fa' => ['t' => 'سرور مجازی لینوکس',
            'seo_t' => 'خرید سرور مجازی لینوکس | Ubuntu، Debian، Alma، Rocky',
            'seo_d' => 'خرید سرور مجازی لینوکس با دسترسی کامل root، دیسک NVMe و نصب خودکار Ubuntu، Debian، AlmaLinux و Rocky؛ ایران و خارج، پرداخت ریالی و تحویل آنی.',
            'tag' => 'Ubuntu · Debian · Alma · Rocky',
            'hero_t' => 'سرور مجازی لینوکس،', 'hero_g' => 'انتخاب توسعه‌دهنده‌ها.',
            'hero_d' => 'همه توزیع‌های محبوب با نصب یک‌کلیکی، دسترسی کامل روت و کنسول تحت وب — در ایران و اروپا، آماده در کمتر از ۶۰ ثانیه.'],
        'en' => ['t' => 'Linux VPS',
            'seo_t' => 'Buy Linux VPS | Ubuntu, Debian, Alma, Rocky',
            'seo_d' => 'Buy a Linux VPS with full root access, NVMe storage and automatic installation of Ubuntu, Debian, AlmaLinux or Rocky; Iran and abroad, instant delivery.',
            'tag' => 'Ubuntu · Debian · Alma · Rocky',
            'hero_t' => 'Linux VPS,', 'hero_g' => 'the developer\'s choice.',
            'hero_d' => 'Every major distro with one-click install, full root access and a web console — in Iran and Europe, ready in under 60 seconds.'],
        'tr' => ['t' => 'Linux VPS', 'tag' => 'Ubuntu · Debian · Alma · Rocky',
            'hero_t' => 'Linux VPS,', 'hero_g' => 'geliştiricinin seçimi.',
            'hero_d' => 'Tek tıkla kurulan tüm popüler dağıtımlar, tam root erişimi ve web konsolu — İran ve Avrupa\'da, 60 saniyede hazır.'],
        'chips' => ['Ubuntu 24.04', 'Debian 12', 'AlmaLinux 9', 'Docker Ready', 'Web Console'],
        'plans' => [
            $mk('LNX-1', 99, 490000, 4.90, ['1 vCPU / 2 GB RAM', '25 GB NVMe', ['fa' => 'ایران یا اروپا', 'en' => 'Iran or Europe', 'tr' => 'İran veya Avrupa'], $traffic, $root]),
            $mk('LNX-2', 100, 990000, 9.90, ['2 vCPU / 4 GB RAM', '60 GB NVMe', ['fa' => 'ایران یا اروپا', 'en' => 'Iran or Europe', 'tr' => 'İran veya Avrupa'], $traffic, $root], true),
            $mk('LNX-4', 101, 1890000, 18.90, ['4 vCPU / 8 GB RAM', '120 GB NVMe', ['fa' => 'ایران یا اروپا', 'en' => 'Iran or Europe', 'tr' => 'İran veya Avrupa'], $traffic, $root]),
        ],
        'features' => ['instant', 'root', 'scale', 'net10', 'backup', 'support'],
        'faqs' => ['activation', 'os', 'manage', 'refund'],
    ],

    'windows' => [
        'icon' => 'monitor', 'group' => 'os',
        'fa' => ['t' => 'سرور مجازی ویندوز',
            'seo_t' => 'خرید سرور مجازی ویندوز | لایسنس رایگان، دسترسی RDP',
            'seo_d' => 'خرید سرور مجازی ویندوز سرور ۲۰۱۹/۲۰۲۲ با لایسنس رایگان و دسترسی RDP؛ NVMe، IP اختصاصی، ایران و خارج، پرداخت ریالی و تحویل خودکار.',
            'tag' => 'Windows Server 2019 / 2022',
            'hero_t' => 'سرور مجازی ویندوز،', 'hero_g' => 'با لایسنس رایگان.',
            'hero_d' => 'ویندوز سرور اورجینال با لایسنس رایگان روی NVMe — ریموت دسکتاپ آنی برای نرم‌افزارهای ویندوزی، حسابداری و اتوماسیون سازمانی.'],
        'en' => ['t' => 'Windows VPS',
            'seo_t' => 'Buy Windows VPS | free licence, RDP access',
            'seo_d' => 'Buy a Windows Server 2019/2022 VPS with a free licence and RDP access; NVMe storage, dedicated IP, Iran and abroad, automatic delivery.',
            'tag' => 'Windows Server 2019 / 2022',
            'hero_t' => 'Windows VPS', 'hero_g' => 'with a free license.',
            'hero_d' => 'Genuine Windows Server with free licensing on NVMe — instant RDP for Windows software, accounting suites and business automation.'],
        'tr' => ['t' => 'Windows VPS', 'tag' => 'Windows Server 2019 / 2022',
            'hero_t' => 'Ücretsiz lisanslı', 'hero_g' => 'Windows VPS.',
            'hero_d' => 'NVMe üzerinde ücretsiz lisanslı orijinal Windows Server — Windows yazılımları için anında RDP.'],
        'chips' => ['License Included', 'RDP Instant', 'NVMe RAID-10', 'Iran & Europe', 'MSSQL Ready'],
        'plans' => [
            $mk('WVP-1', 102, 890000, 8.90, ['2 vCPU / 4 GB RAM', '60 GB NVMe', ['fa' => 'لایسنس ویندوز رایگان', 'en' => 'Free Windows license', 'tr' => 'Ücretsiz Windows lisansı'], $traffic, ['fa' => 'ریموت دسکتاپ آنی', 'en' => 'Instant RDP', 'tr' => 'Anında RDP']]),
            $mk('WVP-2', 103, 1490000, 14.90, ['4 vCPU / 8 GB RAM', '120 GB NVMe', ['fa' => 'لایسنس ویندوز رایگان', 'en' => 'Free Windows license', 'tr' => 'Ücretsiz Windows lisansı'], $traffic, ['fa' => 'ریموت دسکتاپ آنی', 'en' => 'Instant RDP', 'tr' => 'Anında RDP']], true),
            $mk('WVP-3', 104, 2690000, 26.90, ['8 vCPU / 16 GB RAM', '240 GB NVMe', ['fa' => 'لایسنس ویندوز رایگان', 'en' => 'Free Windows license', 'tr' => 'Ücretsiz Windows lisansı'], $traffic, ['fa' => 'IP اختصاصی', 'en' => 'Dedicated IP', 'tr' => 'Özel IP']]),
        ],
        'features' => ['instant', 'scale', 'backup', 'ddos', 'uptime', 'support'],
        'faqs' => ['activation',
            ['fa' => ['q' => 'هزینه لایسنس ویندوز جداست؟', 'a' => 'خیر — لایسنس ویندوز سرور در قیمت پلن لحاظ شده و هیچ هزینه پنهانی ندارد.'],
             'en' => ['q' => 'Is the Windows license charged separately?', 'a' => 'No — the Windows Server license is included in the plan price with no hidden fees.'],
             'tr' => ['q' => 'Windows lisansı ayrı mı ücretlendiriliyor?', 'a' => 'Hayır — Windows Server lisansı plan fiyatına dahildir, gizli ücret yoktur.']],
            'manage', 'refund',
        ],
    ],
];
