<?php

/*
|--------------------------------------------------------------------------
| کاتالوگ سرور مجازی — ۱۱ صفحه (fa / en / tr)
|--------------------------------------------------------------------------
| pid ها placeholder هستند و باید با محصولات واقعی WHMCS جایگزین شوند.
*/

$traffic = ['fa' => 'ترافیک نامحدود', 'en' => 'Unlimited traffic', 'tr' => 'Sınırsız trafik'];
$root = ['fa' => 'دسترسی کامل روت', 'en' => 'Full root access', 'tr' => 'Tam root erişimi'];
$snap = ['fa' => 'بکاپ + اسنپ‌شات', 'en' => 'Backups + snapshots', 'tr' => 'Yedek + anlık görüntü'];

$mk = fn (string $name, int $pid, int $irt, float $eur, array $specs, bool $pop = false) =>
    array_filter(['name' => $name, 'pid' => $pid, 'irt' => $irt, 'eur' => $eur, 'specs' => $specs, 'popular' => $pop]);

return [

    'iran' => [
        'icon' => 'cpu', 'group' => 'location',
        'fa' => ['t' => 'سرور مجازی ایران', 'tag' => 'دیتاسنتر تهران · ترافیک داخلی نیم‌بها',
            'hero_t' => 'سرور مجازی ایران،', 'hero_g' => 'با پینگ ۱ میلی‌ثانیه.',
            'hero_d' => 'NVMe در قلب تهران — برای سایت‌ها و اپلیکیشن‌هایی که کاربر ایرانی دارند: سریع‌ترین پینگ، ترافیک داخلی نیم‌بها و تحویل آنی.'],
        'en' => ['t' => 'Iran VPS', 'tag' => 'Tehran datacenter · Local traffic',
            'hero_t' => 'Iran VPS with', 'hero_g' => '1 ms local latency.',
            'hero_d' => 'NVMe in the heart of Tehran — for sites and apps serving Iranian users: the fastest local ping, discounted domestic traffic and instant delivery.'],
        'tr' => ['t' => 'İran VPS', 'tag' => 'Tahran veri merkezi',
            'hero_t' => '1 ms yerel gecikmeyle', 'hero_g' => 'İran VPS.',
            'hero_d' => 'Tahran\'ın kalbinde NVMe — İranlı kullanıcılara hizmet veren siteler için: en hızlı yerel ping, indirimli yurt içi trafik ve anında teslim.'],
        'chips' => ['NVMe RAID-10', 'Tehran DC', '1 Gbit Port', 'IPv4 + IPv6', 'Anti-DDoS'],
        'signature' => ['type' => 'pings',
            'fa' => ['t' => 'پینگ از شهرهای ایران', 'd' => 'میانگین تاخیر شبکه از ISPهای اصلی کشور تا سرور مجازی ایران سرورنت'],
            'en' => ['t' => 'Ping from Iranian cities', 'd' => 'Average network latency from major national ISPs to ServerNet Iran VPS'],
            'tr' => ['t' => 'İran şehirlerinden ping', 'd' => 'Büyük ulusal ISS\'lerden ServerNet İran VPS\'e ortalama ağ gecikmesi'],
            'items' => [
                ['fa' => 'تهران', 'en' => 'Tehran', 'tr' => 'Tahran', 'ms' => '1 ms'],
                ['fa' => 'اصفهان', 'en' => 'Isfahan', 'tr' => 'İsfahan', 'ms' => '8 ms'],
                ['fa' => 'مشهد', 'en' => 'Mashhad', 'tr' => 'Meşhed', 'ms' => '14 ms'],
                ['fa' => 'تبریز', 'en' => 'Tabriz', 'tr' => 'Tebriz', 'ms' => '12 ms'],
                ['fa' => 'شیراز', 'en' => 'Shiraz', 'tr' => 'Şiraz', 'ms' => '10 ms'],
            ]],
        'plans' => [
            $mk('IR-1', 70, 490000, 4.90, ['1 vCPU / 2 GB RAM', '25 GB NVMe', $traffic, $root, $snap]),
            $mk('IR-2', 71, 990000, 9.90, ['2 vCPU / 4 GB RAM', '60 GB NVMe', $traffic, $root, $snap], true),
            $mk('IR-3', 72, 1890000, 18.90, ['4 vCPU / 8 GB RAM', '120 GB NVMe', $traffic, $root, $snap]),
            $mk('IR-4', 73, 3490000, 34.90, ['8 vCPU / 16 GB RAM', '240 GB NVMe', $traffic, $root, $snap]),
        ],
        'features' => ['instant', 'root', 'scale', 'ddos', 'uptime', 'support'],
        'faqs' => ['activation', 'os', 'manage', 'refund'],
    ],

    'international' => [
        'icon' => 'globe', 'group' => 'location',
        'fa' => ['t' => 'سرور مجازی خارج', 'tag' => 'آلمان · فنلاند · فرانسه · آمریکا',
            'hero_t' => 'سرور مجازی خارج،', 'hero_g' => 'به انتخاب شما.',
            'hero_d' => 'چهار لوکیشن بین‌المللی روی سخت‌افزار نسل جدید — لوکیشن را هنگام سفارش انتخاب کنید؛ بقیه‌اش با ما. تحویل زیر ۶۰ ثانیه.'],
        'en' => ['t' => 'International VPS', 'tag' => 'Germany · Finland · France · USA',
            'hero_t' => 'International VPS,', 'hero_g' => 'your location, your call.',
            'hero_d' => 'Four international locations on latest-gen hardware — pick your location at checkout, we handle the rest. Delivered in under 60 seconds.'],
        'tr' => ['t' => 'Yurt Dışı VPS', 'tag' => 'Almanya · Finlandiya · Fransa · ABD',
            'hero_t' => 'Yurt dışı VPS,', 'hero_g' => 'lokasyon sizin seçiminiz.',
            'hero_d' => 'Son nesil donanımda dört uluslararası lokasyon — ödeme sırasında seçin, gerisi bizde. 60 saniyenin altında teslim.'],
        'chips' => ['NVMe RAID-10', '10 Gbit Network', '4 Locations', 'IPv4 + IPv6', 'Hourly Snapshots'],
        'signature' => ['type' => 'pings',
            'fa' => ['t' => 'پینگ از تهران به لوکیشن‌ها', 'd' => 'میانگین تاخیر شبکه از ایران — برای انتخاب بهترین لوکیشن کاربرانتان'],
            'en' => ['t' => 'Latency from Tehran', 'd' => 'Average network latency from Iran — pick the best location for your users'],
            'tr' => ['t' => 'Tahran\'dan gecikme', 'd' => 'İran\'dan ortalama ağ gecikmesi — kullanıcılarınız için en iyi lokasyonu seçin'],
            'items' => [
                ['fa' => 'فرانکفورت', 'en' => 'Frankfurt', 'tr' => 'Frankfurt', 'ms' => '45 ms'],
                ['fa' => 'هلسینکی', 'en' => 'Helsinki', 'tr' => 'Helsinki', 'ms' => '62 ms'],
                ['fa' => 'پاریس', 'en' => 'Paris', 'tr' => 'Paris', 'ms' => '55 ms'],
                ['fa' => 'نیویورک', 'en' => 'New York', 'tr' => 'New York', 'ms' => '115 ms'],
            ]],
        'plans' => [
            $mk('EU-1', 74, 590000, 5.90, ['1 vCPU / 2 GB RAM', '25 GB NVMe', '20 TB Traffic', $root, $snap]),
            $mk('EU-2', 75, 1190000, 11.90, ['2 vCPU / 4 GB RAM', '60 GB NVMe', '20 TB Traffic', $root, $snap], true),
            $mk('EU-3', 76, 2190000, 21.90, ['4 vCPU / 8 GB RAM', '120 GB NVMe', '20 TB Traffic', $root, $snap]),
            $mk('EU-4', 77, 3990000, 39.90, ['8 vCPU / 16 GB RAM', '240 GB NVMe', '20 TB Traffic', $root, $snap]),
        ],
        'features' => ['instant', 'root', 'scale', 'net10', 'ddos', 'support'],
        'faqs' => ['activation', 'os', 'manage', 'refund'],
    ],

    'germany' => [
        'icon' => 'cpu', 'group' => 'location',
        'fa' => ['t' => 'سرور مجازی آلمان', 'tag' => 'فرانکفورت · Tier III+',
            'hero_t' => 'سرور مجازی آلمان،', 'hero_g' => 'قلب اینترنت اروپا.',
            'hero_d' => 'فرانکفورت — بزرگ‌ترین نقطه تبادل ترافیک جهان (DE-CIX). بهترین انتخاب برای پوشش هم‌زمان کاربران ایران و اروپا.'],
        'en' => ['t' => 'Germany VPS', 'tag' => 'Frankfurt · Tier III+',
            'hero_t' => 'Germany VPS,', 'hero_g' => 'the heart of European internet.',
            'hero_d' => 'Frankfurt — home of DE-CIX, the world\'s largest internet exchange. The best choice to serve Iranian and European users at once.'],
        'tr' => ['t' => 'Almanya VPS', 'tag' => 'Frankfurt · Tier III+',
            'hero_t' => 'Almanya VPS,', 'hero_g' => 'Avrupa internetinin kalbi.',
            'hero_d' => 'Frankfurt — dünyanın en büyük internet değişim noktası DE-CIX\'in evi. İran ve Avrupa kullanıcılarına aynı anda hizmet için en iyi seçim.'],
        'chips' => ['Frankfurt DC', 'DE-CIX', 'NVMe RAID-10', '10 Gbit', 'GDPR-Ready'],
        'signature' => ['type' => 'pings',
            'fa' => ['t' => 'فرانکفورت از نگاه شبکه', 'd' => 'میانگین تاخیر تا مقاصد کلیدی — چرا آلمان محبوب‌ترین لوکیشن کاربران ایرانی است'],
            'en' => ['t' => 'Frankfurt, network-wise', 'd' => 'Average latency to key destinations — why Germany is the most popular location'],
            'tr' => ['t' => 'Ağ açısından Frankfurt', 'd' => 'Önemli noktalara ortalama gecikme'],
            'items' => [
                ['fa' => 'تهران', 'en' => 'Tehran', 'tr' => 'Tahran', 'ms' => '45 ms'],
                ['fa' => 'استانبول', 'en' => 'Istanbul', 'tr' => 'İstanbul', 'ms' => '28 ms'],
                ['fa' => 'لندن', 'en' => 'London', 'tr' => 'Londra', 'ms' => '11 ms'],
                ['fa' => 'دبی', 'en' => 'Dubai', 'tr' => 'Dubai', 'ms' => '88 ms'],
            ]],
        'plans' => [
            $mk('DE-1', 81, 590000, 5.90, ['1 vCPU / 2 GB RAM', '25 GB NVMe', '20 TB Traffic', $root, $snap]),
            $mk('DE-2', 82, 1190000, 11.90, ['2 vCPU / 4 GB RAM', '60 GB NVMe', '20 TB Traffic', $root, $snap], true),
            $mk('DE-3', 83, 2190000, 21.90, ['4 vCPU / 8 GB RAM', '120 GB NVMe', '20 TB Traffic', $root, $snap]),
        ],
        'features' => ['instant', 'root', 'net10', 'ddos', 'uptime', 'support'],
        'faqs' => ['activation', 'os', 'manage', 'refund'],
    ],

    'finland' => [
        'icon' => 'cpu', 'group' => 'location',
        'fa' => ['t' => 'سرور مجازی فنلاند', 'tag' => 'هلسینکی · انرژی سبز',
            'hero_t' => 'سرور مجازی فنلاند،', 'hero_g' => 'قدرت با قیمت به‌صرفه.',
            'hero_d' => 'دیتاسنتر هلسینکی با خنک‌سازی طبیعی و انرژی سبز — همان سخت‌افزار آلمان با قیمتی اقتصادی‌تر. مناسب پروژه‌هایی که حساسیت پینگ کمتری دارند.'],
        'en' => ['t' => 'Finland VPS', 'tag' => 'Helsinki · Green energy',
            'hero_t' => 'Finland VPS,', 'hero_g' => 'power at a smarter price.',
            'hero_d' => 'Helsinki datacenter with natural cooling and green energy — the same hardware as Germany at a friendlier price. Great for less latency-critical workloads.'],
        'tr' => ['t' => 'Finlandiya VPS', 'tag' => 'Helsinki · Yeşil enerji',
            'hero_t' => 'Finlandiya VPS,', 'hero_g' => 'akıllı fiyata güç.',
            'hero_d' => 'Doğal soğutma ve yeşil enerjiyle Helsinki veri merkezi — Almanya ile aynı donanım, daha uygun fiyat.'],
        'chips' => ['Helsinki DC', 'Green Energy', 'NVMe RAID-10', '10 Gbit', 'Best Value'],
        'signature' => ['type' => 'pings',
            'fa' => ['t' => 'پینگ از مقاصد کلیدی', 'd' => 'هلسینکی — تعادل عالی بین هزینه و کیفیت شبکه'],
            'en' => ['t' => 'Latency from key locations', 'd' => 'Helsinki — a great balance of cost and network quality'],
            'tr' => ['t' => 'Önemli noktalardan gecikme', 'd' => 'Helsinki — maliyet ve ağ kalitesi dengesi'],
            'items' => [
                ['fa' => 'تهران', 'en' => 'Tehran', 'tr' => 'Tahran', 'ms' => '62 ms'],
                ['fa' => 'مسکو', 'en' => 'Moscow', 'tr' => 'Moskova', 'ms' => '18 ms'],
                ['fa' => 'فرانکفورت', 'en' => 'Frankfurt', 'tr' => 'Frankfurt', 'ms' => '22 ms'],
                ['fa' => 'استکهلم', 'en' => 'Stockholm', 'tr' => 'Stokholm', 'ms' => '8 ms'],
            ]],
        'plans' => [
            $mk('FI-1', 84, 550000, 5.50, ['1 vCPU / 2 GB RAM', '25 GB NVMe', '20 TB Traffic', $root, $snap]),
            $mk('FI-2', 85, 1090000, 10.90, ['2 vCPU / 4 GB RAM', '60 GB NVMe', '20 TB Traffic', $root, $snap], true),
            $mk('FI-3', 86, 1990000, 19.90, ['4 vCPU / 8 GB RAM', '120 GB NVMe', '20 TB Traffic', $root, $snap]),
        ],
        'features' => ['instant', 'root', 'net10', 'scale', 'uptime', 'support'],
        'faqs' => ['activation', 'os', 'manage', 'refund'],
    ],

    'france' => [
        'icon' => 'cpu', 'group' => 'location',
        'fa' => ['t' => 'سرور مجازی فرانسه', 'tag' => 'پاریس · گراولین',
            'hero_t' => 'سرور مجازی فرانسه،', 'hero_g' => 'روی زیرساخت OVH.',
            'hero_d' => 'دیتاسنترهای پاریس و گراولین با محافظت Anti-DDoS پیش‌فرض OVH — انتخابی مطمئن برای وب‌سایت‌های اروپایی و پروژه‌های پرترافیک.'],
        'en' => ['t' => 'France VPS', 'tag' => 'Paris · Gravelines',
            'hero_t' => 'France VPS', 'hero_g' => 'on OVH infrastructure.',
            'hero_d' => 'Paris and Gravelines datacenters with OVH\'s default Anti-DDoS — a reliable pick for European websites and high-traffic projects.'],
        'tr' => ['t' => 'Fransa VPS', 'tag' => 'Paris · Gravelines',
            'hero_t' => 'OVH altyapısında', 'hero_g' => 'Fransa VPS.',
            'hero_d' => 'OVH\'nin varsayılan Anti-DDoS korumasıyla Paris ve Gravelines veri merkezleri — Avrupa siteleri için güvenilir seçim.'],
        'chips' => ['OVH Infra', 'Anti-DDoS Included', 'NVMe', '1 → 10 Gbit', 'IPv4 + IPv6'],
        'signature' => ['type' => 'pings',
            'fa' => ['t' => 'پینگ از مقاصد کلیدی', 'd' => 'پاریس — دروازه اروپای غربی'],
            'en' => ['t' => 'Latency from key locations', 'd' => 'Paris — the gateway to Western Europe'],
            'tr' => ['t' => 'Önemli noktalardan gecikme', 'd' => 'Paris — Batı Avrupa\'nın kapısı'],
            'items' => [
                ['fa' => 'تهران', 'en' => 'Tehran', 'tr' => 'Tahran', 'ms' => '55 ms'],
                ['fa' => 'لندن', 'en' => 'London', 'tr' => 'Londra', 'ms' => '8 ms'],
                ['fa' => 'مادرید', 'en' => 'Madrid', 'tr' => 'Madrid', 'ms' => '17 ms'],
                ['fa' => 'فرانکفورت', 'en' => 'Frankfurt', 'tr' => 'Frankfurt', 'ms' => '10 ms'],
            ]],
        'plans' => [
            $mk('FR-1', 78, 590000, 5.90, ['1 vCPU / 2 GB RAM', '25 GB NVMe', '20 TB Traffic', $root, $snap]),
            $mk('FR-2', 79, 1190000, 11.90, ['2 vCPU / 4 GB RAM', '60 GB NVMe', '20 TB Traffic', $root, $snap], true),
            $mk('FR-3', 80, 2190000, 21.90, ['4 vCPU / 8 GB RAM', '120 GB NVMe', '20 TB Traffic', $root, $snap]),
        ],
        'features' => ['instant', 'root', 'ddos', 'scale', 'uptime', 'support'],
        'faqs' => ['activation', 'os', 'manage', 'refund'],
    ],

    'usa' => [
        'icon' => 'cpu', 'group' => 'location',
        'fa' => ['t' => 'سرور مجازی آمریکا', 'tag' => 'نیویورک · لس‌آنجلس',
            'hero_t' => 'سرور مجازی آمریکا،', 'hero_g' => 'دو ساحل، یک کلیک.',
            'hero_d' => 'نیویورک برای پوشش اروپا و شرق آمریکا، لس‌آنجلس برای آسیا و غرب — با شبکه پرظرفیت و IPهای تمیز آمریکایی.'],
        'en' => ['t' => 'USA VPS', 'tag' => 'New York · Los Angeles',
            'hero_t' => 'USA VPS,', 'hero_g' => 'both coasts, one click.',
            'hero_d' => 'New York to cover Europe and the US East, Los Angeles for Asia and the West — high-capacity network and clean US IPs.'],
        'tr' => ['t' => 'ABD VPS', 'tag' => 'New York · Los Angeles',
            'hero_t' => 'ABD VPS,', 'hero_g' => 'iki kıyı, tek tık.',
            'hero_d' => 'Avrupa ve ABD doğusu için New York, Asya ve batı için Los Angeles — yüksek kapasiteli ağ ve temiz ABD IP\'leri.'],
        'chips' => ['NY + LA', 'Clean US IPs', 'NVMe RAID-10', '10 Gbit', 'IPv4 + IPv6'],
        'signature' => ['type' => 'pings',
            'fa' => ['t' => 'پینگ از مقاصد کلیدی', 'd' => 'دو لوکیشن برای پوشش کامل قاره آمریکا'],
            'en' => ['t' => 'Latency from key locations', 'd' => 'Two locations for full continental coverage'],
            'tr' => ['t' => 'Önemli noktalardan gecikme', 'd' => 'Tam kıta kapsaması için iki lokasyon'],
            'items' => [
                ['fa' => 'تهران → نیویورک', 'en' => 'Tehran → NY', 'tr' => 'Tahran → NY', 'ms' => '115 ms'],
                ['fa' => 'لندن → نیویورک', 'en' => 'London → NY', 'tr' => 'Londra → NY', 'ms' => '70 ms'],
                ['fa' => 'توکیو → لس‌آنجلس', 'en' => 'Tokyo → LA', 'tr' => 'Tokyo → LA', 'ms' => '98 ms'],
                ['fa' => 'تورنتو → نیویورک', 'en' => 'Toronto → NY', 'tr' => 'Toronto → NY', 'ms' => '12 ms'],
            ]],
        'plans' => [
            $mk('US-1', 87, 650000, 6.50, ['1 vCPU / 2 GB RAM', '25 GB NVMe', '20 TB Traffic', $root, $snap]),
            $mk('US-2', 88, 1290000, 12.90, ['2 vCPU / 4 GB RAM', '60 GB NVMe', '20 TB Traffic', $root, $snap], true),
            $mk('US-3', 89, 2390000, 23.90, ['4 vCPU / 8 GB RAM', '120 GB NVMe', '20 TB Traffic', $root, $snap]),
        ],
        'features' => ['instant', 'root', 'net10', 'scale', 'uptime', 'support'],
        'faqs' => ['activation', 'os', 'manage', 'refund'],
    ],

    'trading' => [
        'icon' => 'trend', 'group' => 'use',
        'fa' => ['t' => 'سرور مجازی ترید', 'tag' => 'لندن LD4 · نیویورک NY4',
            'hero_t' => 'سرور ترید،', 'hero_g' => 'هر میلی‌ثانیه یعنی پول.',
            'hero_d' => 'میزبانی در ساختمان‌های LD4 لندن و NY4 نیویورک — همان‌جایی که سرورهای بروکرهاست. متاتریدر آماده، آپتایم ۹۹.۹۹٪ و اجرای سفارش بدون لغزش.'],
        'en' => ['t' => 'Trading VPS', 'tag' => 'London LD4 · New York NY4',
            'hero_t' => 'Trading VPS —', 'hero_g' => 'every millisecond is money.',
            'hero_d' => 'Hosted inside London LD4 and New York NY4 — the same buildings as broker servers. MetaTrader pre-installed, 99.99% uptime, slippage-free execution.'],
        'tr' => ['t' => 'Trade VPS', 'tag' => 'Londra LD4 · New York NY4',
            'hero_t' => 'Trade VPS —', 'hero_g' => 'her milisaniye paradır.',
            'hero_d' => 'Londra LD4 ve New York NY4 içinde barındırma — broker sunucularıyla aynı binalar. MetaTrader kurulu, %99,99 çalışma süresi.'],
        'chips' => ['LD4 / NY4', 'MT4 / MT5 Ready', 'Windows Server', '99.99% SLA', 'Low-Latency Network'],
        'signature' => ['type' => 'bars',
            'fa' => ['t' => 'تاخیر تا سرور بروکر', 'd' => 'میانگین Round-Trip تا سرورهای اصلی بروکرها — دلیل اینکه تریدرهای حرفه‌ای VPS ترید می‌گیرند'],
            'en' => ['t' => 'Latency to broker servers', 'd' => 'Average round-trip to major broker servers — why serious traders use a trading VPS'],
            'tr' => ['t' => 'Broker sunucularına gecikme', 'd' => 'Büyük broker sunucularına ortalama gidiş-dönüş süresi'],
            'items' => [
                ['fa' => 'سرورنت — داخل LD4', 'en' => 'ServerNet — inside LD4', 'tr' => 'ServerNet — LD4 içinde', 'val' => '0.9 ms', 'w' => '100%', 'hl' => true],
                ['fa' => 'VPS معمولی اروپا', 'en' => 'Typical EU VPS', 'tr' => 'Tipik AB VPS', 'val' => '25 ms', 'w' => '12%'],
                ['fa' => 'اینترنت خانگی ایران', 'en' => 'Home internet (Iran)', 'tr' => 'Ev interneti', 'val' => '180 ms', 'w' => '3%'],
            ]],
        'plans' => [
            $mk('TR-1', 90, 890000, 8.90, ['2 vCPU / 4 GB RAM', '60 GB NVMe', 'Windows Server 2022', ['fa' => 'متاتریدر نصب‌شده', 'en' => 'MetaTrader pre-installed', 'tr' => 'MetaTrader kurulu'], ['fa' => 'تا ۲ ترمینال هم‌زمان', 'en' => 'Up to 2 terminals', 'tr' => '2 terminale kadar']]),
            $mk('TR-2', 91, 1490000, 14.90, ['4 vCPU / 8 GB RAM', '100 GB NVMe', 'Windows Server 2022', ['fa' => 'متاتریدر نصب‌شده', 'en' => 'MetaTrader pre-installed', 'tr' => 'MetaTrader kurulu'], ['fa' => 'تا ۵ ترمینال هم‌زمان', 'en' => 'Up to 5 terminals', 'tr' => '5 terminale kadar']], true),
            $mk('TR-3', 92, 2690000, 26.90, ['8 vCPU / 16 GB RAM', '200 GB NVMe', 'Windows Server 2022', ['fa' => 'متاتریدر نصب‌شده', 'en' => 'MetaTrader pre-installed', 'tr' => 'MetaTrader kurulu'], ['fa' => 'ترمینال نامحدود + IP اختصاصی', 'en' => 'Unlimited terminals + dedicated IP', 'tr' => 'Sınırsız terminal + özel IP']]),
        ],
        'features' => ['uptime', 'instant', 'support', 'backup',
            ['icon' => 'clock',
                'fa' => ['t' => 'همیشه روشن، حتی وقت خواب', 'd' => 'اکسپرت‌ها و ربات‌های شما ۲۴/۵ بدون قطعی برق و اینترنت خانگی معامله می‌کنند.'],
                'en' => ['t' => 'Always on, even while you sleep', 'd' => 'Your EAs and bots trade 24/5 without home power or internet interruptions.'],
                'tr' => ['t' => 'Siz uyurken bile açık', 'd' => 'EA\'larınız ve botlarınız ev elektriği/interneti kesintisi olmadan 7/24 işlem yapar.']],
            ['icon' => 'gauge',
                'fa' => ['t' => 'شبکه Low-Latency اختصاصی', 'd' => 'مسیر مستقیم فیبر بین LD4 و NY4 و بروکرهای اصلی — بدون هاپ اضافه.'],
                'en' => ['t' => 'Dedicated low-latency network', 'd' => 'Direct fiber routes between LD4, NY4 and major brokers — zero extra hops.'],
                'tr' => ['t' => 'Özel düşük gecikmeli ağ', 'd' => 'LD4, NY4 ve büyük broker\'lar arasında doğrudan fiber — ek hop yok.']],
        ],
        'faqs' => ['activation',
            ['fa' => ['q' => 'کدام بروکرها نزدیک سرور شما هستند؟', 'a' => 'اکثر بروکرهای بزرگ (IC Markets، Pepperstone، Exness، آلپاری و…) سرورهای اجرا در LD4 لندن یا NY4 نیویورک دارند — دقیقاً همان‌جایی که VPS ترید سرورنت میزبانی می‌شود. پینگ زیر ۱ میلی‌ثانیه.'],
             'en' => ['q' => 'Which brokers are close to your servers?', 'a' => 'Most major brokers (IC Markets, Pepperstone, Exness, Alpari…) run execution servers in London LD4 or New York NY4 — exactly where ServerNet trading VPS lives. Sub-1 ms ping.'],
             'tr' => ['q' => 'Hangi broker\'lar sunucularınıza yakın?', 'a' => 'Büyük broker\'ların çoğu (IC Markets, Pepperstone, Exness, Alpari…) LD4 veya NY4\'te sunucu çalıştırır — ServerNet trade VPS tam orada. 1 ms altı ping.']],
            ['fa' => ['q' => 'آیا متاتریدر از قبل نصب است؟', 'a' => 'بله — MT4 و MT5 نصب و بهینه شده‌اند. فقط لاگین بروکرتان را وارد کنید و اکسپرت‌ها را فعال کنید.'],
             'en' => ['q' => 'Is MetaTrader pre-installed?', 'a' => 'Yes — MT4 and MT5 come installed and optimized. Just enter your broker login and enable your EAs.'],
             'tr' => ['q' => 'MetaTrader önceden kurulu mu?', 'a' => 'Evet — MT4 ve MT5 kurulu ve optimize. Broker girişinizi yapıp EA\'larınızı etkinleştirmeniz yeter.']],
            'upgrade', 'refund',
        ],
    ],

    'gpu' => [
        'icon' => 'monitor', 'group' => 'use',
        'fa' => ['t' => 'سرور مجازی گرافیکی', 'tag' => 'NVIDIA · CUDA 12',
            'hero_t' => 'قدرت گرافیکی NVIDIA،', 'hero_g' => 'بدون خرید سخت‌افزار.',
            'hero_d' => 'GPUهای حرفه‌ای برای رندر، هوش مصنوعی و پردازش سنگین — با درایورهای آماده CUDA و ایمیج‌های از پیش پیکربندی‌شده PyTorch و TensorFlow.'],
        'en' => ['t' => 'GPU VPS', 'tag' => 'NVIDIA · CUDA 12',
            'hero_t' => 'NVIDIA GPU power,', 'hero_g' => 'without buying hardware.',
            'hero_d' => 'Professional GPUs for rendering, AI and heavy compute — with ready CUDA drivers and pre-configured PyTorch and TensorFlow images.'],
        'tr' => ['t' => 'GPU VPS', 'tag' => 'NVIDIA · CUDA 12',
            'hero_t' => 'Donanım almadan', 'hero_g' => 'NVIDIA GPU gücü.',
            'hero_d' => 'Render, yapay zeka ve ağır işlem için profesyonel GPU\'lar — hazır CUDA sürücüleri ve önceden yapılandırılmış PyTorch/TensorFlow imajları.'],
        'chips' => ['CUDA 12', 'PyTorch / TensorFlow', 'NVMe RAID-10', 'Dedicated vGPU', 'Jupyter Ready'],
        'plans' => [
            $mk('G-4000', 93, 4900000, 49.00, ['RTX 4000 Ada · 20 GB', '8 vCPU / 32 GB RAM', '250 GB NVMe', ['fa' => 'درایور و CUDA آماده', 'en' => 'Drivers & CUDA ready', 'tr' => 'Sürücüler ve CUDA hazır'], $traffic]),
            $mk('G-A5000', 94, 7900000, 79.00, ['RTX A5000 · 24 GB', '12 vCPU / 64 GB RAM', '500 GB NVMe', ['fa' => 'درایور و CUDA آماده', 'en' => 'Drivers & CUDA ready', 'tr' => 'Sürücüler ve CUDA hazır'], $traffic], true),
            $mk('G-A100', 95, 14900000, 149.00, ['A100 · 40 GB HBM2e', '16 vCPU / 128 GB RAM', '1 TB NVMe', ['fa' => 'درایور و CUDA آماده', 'en' => 'Drivers & CUDA ready', 'tr' => 'Sürücüler ve CUDA hazır'], $traffic]),
        ],
        'features' => ['instant', 'root', 'scale', 'support', 'uptime',
            ['icon' => 'bot',
                'fa' => ['t' => 'ایمیج‌های آماده AI', 'd' => 'PyTorch، TensorFlow، ComfyUI و Jupyter از پیش نصب — از دقیقه اول آموزش مدل را شروع کنید.'],
                'en' => ['t' => 'Ready AI Images', 'd' => 'PyTorch, TensorFlow, ComfyUI and Jupyter pre-installed — start training from minute one.'],
                'tr' => ['t' => 'Hazır AI İmajları', 'd' => 'PyTorch, TensorFlow, ComfyUI ve Jupyter kurulu — ilk dakikadan eğitime başlayın.']],
        ],
        'faqs' => ['activation', 'os',
            ['fa' => ['q' => 'برای رندر مناسب است یا فقط AI؟', 'a' => 'هر دو — RTX 4000/A5000 برای رندر Blender و 3ds Max و DaVinci عالی‌اند؛ A100 برای آموزش و اجرای مدل‌های بزرگ زبان و تصویری طراحی شده.'],
             'en' => ['q' => 'Is it good for rendering or only AI?', 'a' => 'Both — RTX 4000/A5000 excel at Blender, 3ds Max and DaVinci rendering; the A100 is built for training and serving large language/vision models.'],
             'tr' => ['q' => 'Render için mi uygun, sadece AI mı?', 'a' => 'İkisi de — RTX 4000/A5000 Blender ve DaVinci render\'da mükemmel; A100 büyük modellerin eğitimi için tasarlandı.']],
            'refund',
        ],
    ],

    'cloud' => [
        'icon' => 'cloud', 'group' => 'use',
        'fa' => ['t' => 'سرور مجازی ابری', 'tag' => 'پرداخت ساعتی · مقیاس آنی',
            'hero_t' => 'سرور ابری،', 'hero_g' => 'به اندازه مصرف بپردازید.',
            'hero_d' => 'سرور مجازی نسل ابری با پرداخت ساعتی، اسنپ‌شات لحظه‌ای و ارتقای بدون ری‌استارت — بسازید، تست کنید، حذف کنید؛ فقط همان ساعت‌ها را می‌پردازید.'],
        'en' => ['t' => 'Cloud VPS', 'tag' => 'Hourly billing · Instant scale',
            'hero_t' => 'Cloud VPS —', 'hero_g' => 'pay for what you use.',
            'hero_d' => 'Cloud-generation VPS with hourly billing, instant snapshots and no-restart scaling — create, test, destroy; pay only for the hours used.'],
        'tr' => ['t' => 'Bulut VPS', 'tag' => 'Saatlik ödeme · Anında ölçek',
            'hero_t' => 'Bulut VPS —', 'hero_g' => 'kullandığın kadar öde.',
            'hero_d' => 'Saatlik faturalandırma, anlık snapshot ve yeniden başlatmasız ölçeklendirme — oluştur, test et, sil; sadece kullanılan saatleri öde.'],
        'chips' => ['Hourly Billing', 'API + CLI', 'Instant Snapshots', 'NVMe RAID-10', 'Private Network'],
        'plans' => [
            $mk('CV-1', 96, 590000, 5.90, ['1 vCPU / 2 GB RAM', '25 GB NVMe', ['fa' => 'یا ~۸۲۰ تومان/ساعت', 'en' => 'or ~€0.009/hour', 'tr' => 'veya ~€0,009/saat'], $traffic, $root]),
            $mk('CV-2', 97, 1090000, 10.90, ['2 vCPU / 4 GB RAM', '60 GB NVMe', ['fa' => 'یا ~۱,۵۲۰ تومان/ساعت', 'en' => 'or ~€0.016/hour', 'tr' => 'veya ~€0,016/saat'], $traffic, $root], true),
            $mk('CV-4', 98, 1990000, 19.90, ['4 vCPU / 8 GB RAM', '120 GB NVMe', ['fa' => 'یا ~۲,۷۷۰ تومان/ساعت', 'en' => 'or ~€0.028/hour', 'tr' => 'veya ~€0,028/saat'], $traffic, $root]),
        ],
        'features' => ['hourly', 'scale', 'instant', 'net10', 'backup', 'support'],
        'faqs' => ['activation', 'os',
            ['fa' => ['q' => 'پرداخت ساعتی دقیقاً چطور کار می‌کند؟', 'a' => 'کیف پول خود را شارژ می‌کنید و به ازای هر ساعتی که سرور وجود دارد، هزینه کسر می‌شود. سرور را حذف کنید، کسر هزینه همان لحظه متوقف می‌شود. سقف هزینه ماهانه همان قیمت پلن است.'],
             'en' => ['q' => 'How exactly does hourly billing work?', 'a' => 'Top up your wallet and pay per hour while the server exists. Delete the server and charges stop instantly. Monthly cost is capped at the plan price.'],
             'tr' => ['q' => 'Saatlik ödeme tam olarak nasıl çalışır?', 'a' => 'Cüzdanınızı doldurun, sunucu var olduğu her saat için ödeyin. Sunucuyu silin, ücretlendirme anında durur. Aylık maliyet plan fiyatıyla sınırlıdır.']],
            'manage', 'refund',
        ],
    ],

    'linux' => [
        'icon' => 'code', 'group' => 'os',
        'fa' => ['t' => 'سرور مجازی لینوکس', 'tag' => 'Ubuntu · Debian · Alma · Rocky',
            'hero_t' => 'سرور مجازی لینوکس،', 'hero_g' => 'انتخاب توسعه‌دهنده‌ها.',
            'hero_d' => 'همه توزیع‌های محبوب با نصب یک‌کلیکی، دسترسی کامل روت و کنسول تحت وب — در ایران و اروپا، آماده در کمتر از ۶۰ ثانیه.'],
        'en' => ['t' => 'Linux VPS', 'tag' => 'Ubuntu · Debian · Alma · Rocky',
            'hero_t' => 'Linux VPS,', 'hero_g' => 'the developer\'s choice.',
            'hero_d' => 'Every major distro with one-click install, full root access and a web console — in Iran and Europe, ready in under 60 seconds.'],
        'tr' => ['t' => 'Linux VPS', 'tag' => 'Ubuntu · Debian · Alma · Rocky',
            'hero_t' => 'Linux VPS,', 'hero_g' => 'geliştiricinin seçimi.',
            'hero_d' => 'Tek tıkla kurulan tüm popüler dağıtımlar, tam root erişimi ve web konsolu — İran ve Avrupa\'da, 60 saniyede hazır.'],
        'chips' => ['Ubuntu 24.04', 'Debian 12', 'AlmaLinux 9', 'Docker Ready', 'Web Console'],
        'plans' => [
            $mk('LNX-1', 99, 490000, 4.90, ['1 vCPU / 2 GB RAM', '25 GB NVMe', ['fa' => 'ایران یا اروپا', 'en' => 'Iran or Europe', 'tr' => 'İran veya Avrupa'], $traffic, $root]),
            $mk('LNX-2', 100, 990000, 9.90, ['2 vCPU / 4 GB RAM', '60 GB NVMe', ['fa' => 'ایران یا اروپا', 'en' => 'Iran or Europe', 'tr' => 'İran veya Avrupa'], $traffic, $root], true),
            $mk('LNX-4', 101, 1890000, 18.90, ['4 vCPU / 8 GB RAM', '120 GB NVMe', ['fa' => 'ایران یا اروپا', 'en' => 'Iran or Europe', 'tr' => 'İran veya Avrupa'], $traffic, $root]),
        ],
        'features' => ['instant', 'root', 'scale', 'net10', 'backup', 'support'],
        'faqs' => ['activation', 'os', 'manage', 'refund'],
    ],

    'windows' => [
        'icon' => 'monitor', 'group' => 'os',
        'fa' => ['t' => 'سرور مجازی ویندوز', 'tag' => 'Windows Server 2019 / 2022',
            'hero_t' => 'سرور مجازی ویندوز،', 'hero_g' => 'با لایسنس رایگان.',
            'hero_d' => 'ویندوز سرور اورجینال با لایسنس رایگان روی NVMe — ریموت دسکتاپ آنی برای نرم‌افزارهای ویندوزی، حسابداری و اتوماسیون سازمانی.'],
        'en' => ['t' => 'Windows VPS', 'tag' => 'Windows Server 2019 / 2022',
            'hero_t' => 'Windows VPS', 'hero_g' => 'with a free license.',
            'hero_d' => 'Genuine Windows Server with free licensing on NVMe — instant RDP for Windows software, accounting suites and business automation.'],
        'tr' => ['t' => 'Windows VPS', 'tag' => 'Windows Server 2019 / 2022',
            'hero_t' => 'Ücretsiz lisanslı', 'hero_g' => 'Windows VPS.',
            'hero_d' => 'NVMe üzerinde ücretsiz lisanslı orijinal Windows Server — Windows yazılımları için anında RDP.'],
        'chips' => ['License Included', 'RDP Instant', 'NVMe RAID-10', 'Iran & Europe', 'MSSQL Ready'],
        'plans' => [
            $mk('WVP-1', 102, 890000, 8.90, ['2 vCPU / 4 GB RAM', '60 GB NVMe', ['fa' => 'لایسنس ویندوز رایگان', 'en' => 'Free Windows license', 'tr' => 'Ücretsiz Windows lisansı'], $traffic, ['fa' => 'ریموت دسکتاپ آنی', 'en' => 'Instant RDP', 'tr' => 'Anında RDP']]),
            $mk('WVP-2', 103, 1490000, 14.90, ['4 vCPU / 8 GB RAM', '120 GB NVMe', ['fa' => 'لایسنس ویندوز رایگان', 'en' => 'Free Windows license', 'tr' => 'Ücretsiz Windows lisansı'], $traffic, ['fa' => 'ریموت دسکتاپ آنی', 'en' => 'Instant RDP', 'tr' => 'Anında RDP']], true),
            $mk('WVP-3', 104, 2690000, 26.90, ['8 vCPU / 16 GB RAM', '240 GB NVMe', ['fa' => 'لایسنس ویندوز رایگان', 'en' => 'Free Windows license', 'tr' => 'Ücretsiz Windows lisansı'], $traffic, ['fa' => 'IP اختصاصی', 'en' => 'Dedicated IP', 'tr' => 'Özel IP']]),
        ],
        'features' => ['instant', 'scale', 'backup', 'ddos', 'uptime', 'support'],
        'faqs' => ['activation',
            ['fa' => ['q' => 'هزینه لایسنس ویندوز جداست؟', 'a' => 'خیر — لایسنس ویندوز سرور در قیمت پلن لحاظ شده و هیچ هزینه پنهانی ندارد.'],
             'en' => ['q' => 'Is the Windows license charged separately?', 'a' => 'No — the Windows Server license is included in the plan price with no hidden fees.'],
             'tr' => ['q' => 'Windows lisansı ayrı mı ücretlendiriliyor?', 'a' => 'Hayır — Windows Server lisansı plan fiyatına dahildir, gizli ücret yoktur.']],
            'manage', 'refund',
        ],
    ],
];
